[package]
name = "c3_fold_batch_lib"
type = "lib"
authors = ["Gnosis Guild / Interfold (I5 r9 PoC)"]

[dependencies]
lib = { path = "../../../lib" }
bb_proof_verification = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v5.1.0", directory = "barretenberg/noir/bb_proof_verification" }
