packages:
  - crates/wasm
  - docs
  - examples/CRISP
  - examples/CRISP/client
  - examples/CRISP/packages/crisp-sdk
  - examples/CRISP/packages/crisp-contracts
  - examples/CRISP/packages/crisp-zk-inputs
  - packages/interfold-config
  - packages/interfold-react
  - packages/interfold-sdk
  - packages/interfold-contracts
  - packages/interfold-mcp
  - packages/interfold-dashboard
  - packages/interfold-node
  - templates/default
  - templates/default/client
linkWorkspacePackages: true
overrides:
  '@nomicfoundation/hardhat-keystore': 3.0.3
  '@types/node': 22.7.5
  tsup: 8.5.0
  typescript: 5.8.3
  undici-types: 6.19.8
  viem: 2.38.6
