// SPDX-License-Identifier: LGPL-3.0-only
//
// This file is provided WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE.
pragma solidity >=0.8.27;

import { IInterfold } from "../interfaces/IInterfold.sol";

// Auto-generated by scripts/build-circuits.ts. Active local selection: insecure-512/minimum.
// Mainnet supports secure BFV with minimum, micro, and small committees. Sepolia and local chains
// support insecure and secure BFV with every committee size.
library ActiveCryptoConfig {
    bytes32 internal constant ENCRYPTION_SCHEME_ID = keccak256("fhe.rs:BFV");
    bytes32 internal constant CIRCUIT_VERSION = keccak256("interfold-bfv-v2");

    bytes32 internal constant INSECURE_CONFIG_ID =
        0x19921c8c12f93c3013be57d0859f4ddcdb4464ac856a0c62be1ad617fbbd2e7d;
    uint8 internal constant INSECURE_PARAM_SET = 0;
    bytes32 internal constant INSECURE_PARAM_SET_HASH =
        0x18c6d8650486b997d48aa2d285fae878fb267b268332d056a3e8527d50e87b4f;

    bytes32 internal constant SECURE_CONFIG_ID =
        0xac5490c59e158cbb104642bba0ab7b3fd11ca49dd4bb05ce7bec8089ce3c8c31;
    uint8 internal constant SECURE_PARAM_SET = 2;
    bytes32 internal constant SECURE_PARAM_SET_HASH =
        0x80775a19b6126a12943f9c1c53f92299f0c92ece819b625026ab1406bbbe0721;

    uint8 internal constant MINIMUM_COMMITTEE_SIZE = 0;
    uint32 internal constant MINIMUM_T = 1;
    uint32 internal constant MINIMUM_H = 2;
    uint32 internal constant MINIMUM_N = 3;

    uint8 internal constant MICRO_COMMITTEE_SIZE = 1;
    uint32 internal constant MICRO_T = 4;
    uint32 internal constant MICRO_H = 5;
    uint32 internal constant MICRO_N = 9;

    uint8 internal constant SMALL_COMMITTEE_SIZE = 2;
    uint32 internal constant SMALL_T = 9;
    uint32 internal constant SMALL_H = 14;
    uint32 internal constant SMALL_N = 19;

    // Production default. The public MAX_COMMITTEE_SIZE constant reads N.
    bytes32 internal constant CONFIG_ID = SECURE_CONFIG_ID;
    uint8 internal constant PARAM_SET = SECURE_PARAM_SET;
    bytes32 internal constant PARAM_SET_HASH = SECURE_PARAM_SET_HASH;
    uint8 internal constant COMMITTEE_SIZE = SMALL_COMMITTEE_SIZE;
    uint32 internal constant T = SMALL_T;
    uint32 internal constant H = SMALL_H;
    uint32 internal constant N = SMALL_N;

    // Testnet default. Sepolia can still request secure minimum explicitly.
    bytes32 internal constant TESTNET_CONFIG_ID = INSECURE_CONFIG_ID;
    uint8 internal constant TESTNET_PARAM_SET = INSECURE_PARAM_SET;
    bytes32 internal constant TESTNET_PARAM_SET_HASH = INSECURE_PARAM_SET_HASH;
    uint8 internal constant TESTNET_COMMITTEE_SIZE = MINIMUM_COMMITTEE_SIZE;
    uint32 internal constant TESTNET_T = MINIMUM_T;
    uint32 internal constant TESTNET_H = MINIMUM_H;
    uint32 internal constant TESTNET_N = MINIMUM_N;

    function isTestnetOrLocal() internal view returns (bool) {
        uint256 chainId = block.chainid;
        return chainId == 11155111 || chainId == 31337 || chainId == 1337;
    }

    function configIdForParamSet(
        uint8 paramSet
    ) internal pure returns (bytes32) {
        if (paramSet == INSECURE_PARAM_SET) return INSECURE_CONFIG_ID;
        if (paramSet == SECURE_PARAM_SET) return SECURE_CONFIG_ID;
        revert IInterfold.UnsupportedCryptoConfig();
    }

    function t() internal view returns (uint32) {
        return isTestnetOrLocal() ? TESTNET_T : T;
    }

    function h() internal view returns (uint32) {
        return isTestnetOrLocal() ? TESTNET_H : H;
    }

    function isParamSetSupported(uint8 paramSet) internal view returns (bool) {
        if (isTestnetOrLocal()) {
            return
                paramSet == INSECURE_PARAM_SET || paramSet == SECURE_PARAM_SET;
        }
        return paramSet == SECURE_PARAM_SET;
    }

    function isCommitteeSupported(
        uint8 committeeSize
    ) internal pure returns (bool) {
        return
            committeeSize == MINIMUM_COMMITTEE_SIZE ||
            committeeSize == MICRO_COMMITTEE_SIZE ||
            committeeSize == SMALL_COMMITTEE_SIZE;
    }

    function committeeParams(
        uint8 committeeSize
    ) internal pure returns (uint32 threshold, uint32 honest, uint32 total) {
        if (committeeSize == MINIMUM_COMMITTEE_SIZE) {
            return (MINIMUM_T, MINIMUM_H, MINIMUM_N);
        }
        if (committeeSize == MICRO_COMMITTEE_SIZE) {
            return (MICRO_T, MICRO_H, MICRO_N);
        }
        if (committeeSize == SMALL_COMMITTEE_SIZE) {
            return (SMALL_T, SMALL_H, SMALL_N);
        }
        revert IInterfold.UnsupportedCryptoConfig();
    }

    function validateEncryptionScheme(
        bytes32 encryptionSchemeId
    ) internal pure {
        if (encryptionSchemeId != ENCRYPTION_SCHEME_ID)
            revert IInterfold.UnsupportedCryptoConfig();
    }

    function validateCommittee(
        uint8 committeeSize,
        uint32[2] calldata threshold
    ) internal pure {
        (, uint32 expectedH, uint32 expectedN) = committeeParams(committeeSize);
        if (threshold[0] != expectedH || threshold[1] != expectedN)
            revert IInterfold.UnsupportedCryptoConfig();
    }

    function validateParamSet(
        uint8 paramSet,
        bytes32 paramSetHash
    ) internal view {
        if (!isParamSetSupported(paramSet))
            revert IInterfold.UnsupportedCryptoConfig();
        bytes32 expectedHash = paramSet == INSECURE_PARAM_SET
            ? INSECURE_PARAM_SET_HASH
            : SECURE_PARAM_SET_HASH;
        if (paramSetHash != expectedHash)
            revert IInterfold.UnsupportedCryptoConfig();
    }
}
