// SPDX-License-Identifier: LGPL-3.0-only
//
// This file is provided WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE.
pragma solidity >=0.8.27;

import { IInterfold } from "../interfaces/IInterfold.sol";

// Auto-generated by scripts/build-circuits.ts. Active local selection: insecure-512/minimum.
// Mainnet supports secure BFV with minimum, micro, and small committees. Sepolia and local chains
// support insecure and secure BFV with every committee size.
library ActiveCryptoConfig {
    bytes32 internal constant ENCRYPTION_SCHEME_ID = keccak256("fhe.rs:BFV");
    bytes32 internal constant CIRCUIT_VERSION = keccak256("interfold-bfv-v1");
    /// @dev CKKS scheme id: allowed alongside BFV. The scheme is bound per
    ///      E3 by the program's `validate()` (program address => protocol);
    ///      this config allows both, and the per-scheme verifier
    ///      registries gate which schemes are actually operable.
    bytes32 internal constant CKKS_ENCRYPTION_SCHEME_ID =
        keccak256("fhe.rs:CKKS");

    bytes32 internal constant INSECURE_CONFIG_ID =
        0x04f3677e73b0f5066d6caf5cbd92e3fb2e38338edaf5cfc971ab28f7b684da78;
    uint8 internal constant INSECURE_PARAM_SET = 0;
    bytes32 internal constant INSECURE_PARAM_SET_HASH =
        0x18c6d8650486b997d48aa2d285fae878fb267b268332d056a3e8527d50e87b4f;

    bytes32 internal constant SECURE_CONFIG_ID =
        0xd9c86e581f8291ffb5b63595600e8d096ed30b16e2e0a6634a76c22b1f58fb4e;
    uint8 internal constant SECURE_PARAM_SET = 1;
    bytes32 internal constant SECURE_PARAM_SET_HASH =
        0xd7068fdcc1910f5e49c8b05530cf74f876cadee2a1caf797a40b1ae53ae143ec;

    /// @dev CKKS demo ParamSets. Every one of them shares the INSECURE BFV
    ///      parameter bytes (same crypto-config id, same DKG transport
    ///      encoding on-chain); only the node-side CKKS modulus ladder
    ///      differs. Admitted on testnet/local chains only, like the
    ///      insecure BFV set they piggyback on.
    ///      2: sign-extraction ladder (auction), hybrid relin ceremony.
    ///      3: statistics (relinearised sum-of-squares), level-0 relin.
    ///      4: credit scoring v2 (5-limb, two-level relin ceremony).
    ///      5: coefficient inner products (matching / treasury risk /
    ///         federated averaging), level-0 relin ceremony.
    uint8 internal constant CKKS_LADDER_PARAM_SET = 2;
    uint8 internal constant CKKS_STATISTICS_PARAM_SET = 3;
    uint8 internal constant CKKS_CREDIT_PARAM_SET = 4;
    uint8 internal constant CKKS_COEFFICIENT_PARAM_SET = 5;

    uint8 internal constant MINIMUM_COMMITTEE_SIZE = 0;
    uint32 internal constant MINIMUM_T = 1;
    uint32 internal constant MINIMUM_H = 2;
    uint32 internal constant MINIMUM_N = 3;

    uint8 internal constant MICRO_COMMITTEE_SIZE = 1;
    uint32 internal constant MICRO_T = 4;
    uint32 internal constant MICRO_H = 5;
    uint32 internal constant MICRO_N = 9;

    uint8 internal constant SMALL_COMMITTEE_SIZE = 2;
    uint32 internal constant SMALL_T = 9;
    uint32 internal constant SMALL_H = 10;
    uint32 internal constant SMALL_N = 19;

    // Production default. The public MAX_COMMITTEE_SIZE constant reads N.
    bytes32 internal constant CONFIG_ID = SECURE_CONFIG_ID;
    uint8 internal constant PARAM_SET = SECURE_PARAM_SET;
    bytes32 internal constant PARAM_SET_HASH = SECURE_PARAM_SET_HASH;
    uint8 internal constant COMMITTEE_SIZE = SMALL_COMMITTEE_SIZE;
    uint32 internal constant T = SMALL_T;
    uint32 internal constant H = SMALL_H;
    uint32 internal constant N = SMALL_N;

    // Testnet default. Sepolia can still request secure minimum explicitly.
    bytes32 internal constant TESTNET_CONFIG_ID = INSECURE_CONFIG_ID;
    uint8 internal constant TESTNET_PARAM_SET = INSECURE_PARAM_SET;
    bytes32 internal constant TESTNET_PARAM_SET_HASH = INSECURE_PARAM_SET_HASH;
    uint8 internal constant TESTNET_COMMITTEE_SIZE = MINIMUM_COMMITTEE_SIZE;
    uint32 internal constant TESTNET_T = MINIMUM_T;
    uint32 internal constant TESTNET_H = MINIMUM_H;
    uint32 internal constant TESTNET_N = MINIMUM_N;

    function isTestnetOrLocal() internal view returns (bool) {
        uint256 chainId = block.chainid;
        return chainId == 11155111 || chainId == 31337 || chainId == 1337;
    }

    function isCkksDemoParamSet(uint8 paramSet) internal pure returns (bool) {
        return
            paramSet == CKKS_LADDER_PARAM_SET ||
            paramSet == CKKS_STATISTICS_PARAM_SET ||
            paramSet == CKKS_CREDIT_PARAM_SET ||
            paramSet == CKKS_COEFFICIENT_PARAM_SET;
    }

    function configIdForParamSet(
        uint8 paramSet
    ) internal pure returns (bytes32) {
        if (paramSet == INSECURE_PARAM_SET) return INSECURE_CONFIG_ID;
        if (paramSet == SECURE_PARAM_SET) return SECURE_CONFIG_ID;
        // CKKS demo sets carry the insecure BFV bytes, hence its config id.
        if (isCkksDemoParamSet(paramSet)) return INSECURE_CONFIG_ID;
        revert IInterfold.UnsupportedCryptoConfig();
    }

    function t() internal view returns (uint32) {
        return isTestnetOrLocal() ? TESTNET_T : T;
    }

    function h() internal view returns (uint32) {
        return isTestnetOrLocal() ? TESTNET_H : H;
    }

    function isParamSetSupported(uint8 paramSet) internal view returns (bool) {
        if (isTestnetOrLocal()) {
            return
                paramSet == INSECURE_PARAM_SET ||
                paramSet == SECURE_PARAM_SET ||
                isCkksDemoParamSet(paramSet);
        }
        return paramSet == SECURE_PARAM_SET;
    }

    function isCommitteeSupported(
        uint8 committeeSize
    ) internal pure returns (bool) {
        return
            committeeSize == MINIMUM_COMMITTEE_SIZE ||
            committeeSize == MICRO_COMMITTEE_SIZE ||
            committeeSize == SMALL_COMMITTEE_SIZE;
    }

    function committeeParams(
        uint8 committeeSize
    ) internal pure returns (uint32 threshold, uint32 honest, uint32 total) {
        if (committeeSize == MINIMUM_COMMITTEE_SIZE) {
            return (MINIMUM_T, MINIMUM_H, MINIMUM_N);
        }
        if (committeeSize == MICRO_COMMITTEE_SIZE) {
            return (MICRO_T, MICRO_H, MICRO_N);
        }
        if (committeeSize == SMALL_COMMITTEE_SIZE) {
            return (SMALL_T, SMALL_H, SMALL_N);
        }
        revert IInterfold.UnsupportedCryptoConfig();
    }

    function validateEncryptionScheme(
        bytes32 encryptionSchemeId
    ) internal pure {
        if (
            encryptionSchemeId != ENCRYPTION_SCHEME_ID &&
            encryptionSchemeId != CKKS_ENCRYPTION_SCHEME_ID
        ) revert IInterfold.UnsupportedCryptoConfig();
    }

    function validateCommittee(
        uint8 committeeSize,
        uint32[2] calldata threshold
    ) internal pure {
        (, uint32 expectedH, uint32 expectedN) = committeeParams(committeeSize);
        if (threshold[0] != expectedH || threshold[1] != expectedN)
            revert IInterfold.UnsupportedCryptoConfig();
    }

    function validateParamSet(
        uint8 paramSet,
        bytes32 paramSetHash
    ) internal view {
        if (!isParamSetSupported(paramSet))
            revert IInterfold.UnsupportedCryptoConfig();
        // CKKS demo sets register the insecure BFV bytes.
        bytes32 expectedHash = paramSet == SECURE_PARAM_SET
            ? SECURE_PARAM_SET_HASH
            : INSECURE_PARAM_SET_HASH;
        if (paramSetHash != expectedHash)
            revert IInterfold.UnsupportedCryptoConfig();
    }
}
