[package]
name = "e3-support-host"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
serde = { workspace = true }
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
e3-compute-provider = { workspace = true }
e3-support-types = { workspace = true }
e3-user-program = { workspace = true }

tempfile = "3"
sha2.workspace = true
serde_json.workspace = true
hex.workspace = true

[dev-dependencies]
hex = { workspace = true }
