[workspace]
resolver = "3"
members = [
  "program",
  ".interfold/support/dev",
  ".interfold/support/openvm/service"
]

[workspace.dependencies]
e3-user-program = { path = "./program" }
fhe = { git = "https://github.com/gnosisguild/fhe.rs", rev = "873dc69c07eae251f88c4b5cacf6c4453e2c365a", features = ["experimental-mbfv"] }
fhe-traits = { git = "https://github.com/gnosisguild/fhe.rs", rev = "873dc69c07eae251f88c4b5cacf6c4453e2c365a" }
e3-program-server = { path = "../../crates/program-server" }
e3-bfv-client = { path = "../../crates/bfv-client" }
e3-fhe-params = { path = "../../crates/fhe-params" }
e3-compute-provider = { path = "../../crates/compute-provider" }
e3-openvm-host = { path = "../../crates/openvm-host" }
rand = "0.9"
anyhow = "1.0.86"
