// SPDX-License-Identifier: LGPL-3.0-only
//
// This file is provided WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE.

/**
 * CkksE3Program wired to the ParamSet 3 (statistics) Greco verifiers.
 *
 * Uses a REAL fixture generated by the `ckks_participant` CLI (one
 * `Inputs::compute`, nargo execute + `bb prove -t evm` for the
 * `user_data_encryption_ckks_ct{0,1}_ps3` circuits — value 52000 over
 * cap 100000, slot-replicated). Same program contract as the canonical
 * set; only the verifier pair (and hence the VK-pinned circuit configs:
 * 3 limbs, delta 2^40, B=1) differs.
 */
import { expect } from "chai";
import { readFileSync } from "fs";
import { network } from "hardhat";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const HONK_VERIFY_GAS_LIMIT = 100_000_000;

interface LegFixture {
  proof: string;
  publicInputs: string[];
}
interface GrecoFixture {
  ct0: LegFixture;
  ct1: LegFixture;
  ciphertext: string;
}

const fixturePath = join(
  dirname(fileURLToPath(import.meta.url)),
  "fixtures",
  "ckks_greco_ps3",
  "verified_input.json",
);

describe("CkksE3Program with ParamSet 3 verifiers (Greco-gated survey inputs)", function () {
  let fixture: GrecoFixture;

  before(function () {
    fixture = JSON.parse(readFileSync(fixturePath, "utf-8")) as GrecoFixture;
  });

  async function deployAll() {
    const { ethers, networkHelpers } = await network.connect();
    await networkHelpers.setBlockGasLimit(HONK_VERIFY_GAS_LIMIT);

    // Honk verifiers use external libraries; deploy + link per leg.
    async function deployVerifier(solFile: string, contractName: string) {
      const base = `contracts/verifiers/bfv/honk/${solFile}`;
      const zkLib = await (
        await ethers.getContractFactory(`${base}:ZKTranscriptLib`)
      ).deploy();
      const relLib = await (
        await ethers.getContractFactory(`${base}:RelationsLib`)
      ).deploy();
      const factory = await ethers.getContractFactory(
        `${base}:${contractName}`,
        {
          libraries: {
            [`project/${base}:ZKTranscriptLib`]: await zkLib.getAddress(),
            [`project/${base}:RelationsLib`]: await relLib.getAddress(),
          },
        },
      );
      const verifier = await factory.deploy();
      await verifier.waitForDeployment();
      return verifier;
    }

    const ct0Verifier = await deployVerifier(
      "UserDataEncryptionCkksCt0Ps3Verifier.sol",
      "UserDataEncryptionCkksCt0Ps3Verifier",
    );
    const ct1Verifier = await deployVerifier(
      "UserDataEncryptionCkksCt1Ps3Verifier.sol",
      "UserDataEncryptionCkksCt1Ps3Verifier",
    );
    const program = await (
      await ethers.getContractFactory("CkksE3Program")
    ).deploy(await ct0Verifier.getAddress(), await ct1Verifier.getAddress());
    return { ethers, program };
  }

  function encodeInput(
    ethers: Awaited<ReturnType<typeof network.connect>>["ethers"],
    f: GrecoFixture,
    overrides?: Partial<{
      ct0Proof: string;
    }>,
  ): string {
    return ethers.AbiCoder.defaultAbiCoder().encode(
      ["bytes", "bytes", "bytes32[]", "bytes", "bytes32[]"],
      [
        f.ciphertext,
        overrides?.ct0Proof ?? f.ct0.proof,
        f.ct0.publicInputs,
        f.ct1.proof,
        f.ct1.publicInputs,
      ],
    );
  }

  it("accepts a genuine ps3 participant submission and emits commitments", async function () {
    const { ethers, program } = await deployAll();
    const data = encodeInput(ethers, fixture);
    const tx = await program.publishInput(1n, data, {
      gasLimit: HONK_VERIFY_GAS_LIMIT,
    });
    const receipt = await tx.wait();
    const parsed = receipt!.logs
      .map((l) => program.interface.parseLog(l))
      .find((e) => e?.name === "VerifiedInputPublished");
    expect(parsed, "VerifiedInputPublished must fire").to.not.be.undefined;
    expect(parsed!.args.ciphertextHash).to.equal(
      ethers.keccak256(fixture.ciphertext),
    );
    // u commitment shared across legs (ct0 idx 3 == ct1 idx 2).
    expect(parsed!.args.uCommitment).to.equal(fixture.ct0.publicInputs[3]);
    expect(fixture.ct0.publicInputs[3]).to.equal(fixture.ct1.publicInputs[2]);
  });

  it("rejects a tampered proof", async function () {
    const { ethers, program } = await deployAll();
    const tampered =
      fixture.ct0.proof.slice(0, 200) +
      (fixture.ct0.proof[200] === "0" ? "1" : "0") +
      fixture.ct0.proof.slice(201);
    const data = encodeInput(ethers, fixture, { ct0Proof: tampered });
    await expect(
      program.publishInput(1n, data, { gasLimit: HONK_VERIFY_GAS_LIMIT }),
    ).to.be.revertedWithCustomError(program, "Ct0ProofInvalid");
  });

  it("rejects a duplicate submission (same u commitment)", async function () {
    const { ethers, program } = await deployAll();
    const data = encodeInput(ethers, fixture);
    await program.publishInput(1n, data, { gasLimit: HONK_VERIFY_GAS_LIMIT });
    await expect(
      program.publishInput(1n, data, { gasLimit: HONK_VERIFY_GAS_LIMIT }),
    ).to.be.revertedWithCustomError(program, "DuplicateSubmission");
  });
});
