node:
  address: '${ADDRESS}'
  quic_port: ${QUIC_PORT}
chains:
  - name: 'sepolia'
    chain_id: 11155111
    rpc_url: '${RPC_URL}'
    contracts:
      interfold: '${SEPOLIA_INTERFOLD_ADDRESS}'
      ciphernode_registry: '${SEPOLIA_CIPHERNODE_REGISTRY_ADDRESS}'
      bonding_registry: '${SEPOLIA_BONDING_REGISTRY}'
