node:
  address: '${ADDRESS}'
  quic_port: ${QUIC_PORT}
  peers:
    - '/dns4/cn1/udp/9091/quic-v1'
    - '/dns4/cn3/udp/9093/quic-v1'
    - '/dns4/cn4/udp/9094/quic-v1'
chains:
  - name: 'sepolia'
    chain_id: 11155111
    reorg_confirmations: 64
    rpc_url: '${RPC_URL}'
    contracts:
      interfold:
        address: '${SEPOLIA_INTERFOLD_ADDRESS}'
        deploy_block: ${SEPOLIA_INTERFOLD_DEPLOY_BLOCK}
      ciphernode_registry:
        address: '${SEPOLIA_CIPHERNODE_REGISTRY_ADDRESS}'
        deploy_block: ${SEPOLIA_CIPHERNODE_REGISTRY_DEPLOY_BLOCK}
      bonding_registry:
        address: '${SEPOLIA_BONDING_REGISTRY}'
        deploy_block: ${SEPOLIA_BONDING_REGISTRY_DEPLOY_BLOCK}
      slashing_manager:
        address: '${SEPOLIA_SLASHING_MANAGER_ADDRESS}'
        deploy_block: ${SEPOLIA_SLASHING_MANAGER_DEPLOY_BLOCK}
