[workspace]
members = [
    "pk_generation",
    "pk_generation_ckks_ps0",
    "pk_generation_ckks_ps2",
    "pk_generation_ckks_ps3",
    "pk_generation_ckks_ps4",
    "pk_generation_ckks_ps5",
    "pk_aggregation",
    "user_data_encryption",
    "user_data_encryption_ct0",
    "user_data_encryption_ckks_ct0",
    "user_data_encryption_ckks_ct1",
    "user_data_encryption_ckks_ct0_ps2",
    "user_data_encryption_ckks_ct1_ps2",
    "user_data_encryption_ckks_ct0_ps3",
    "user_data_encryption_ckks_ct1_ps3",
    "user_data_encryption_ckks_ct0_ps4",
    "user_data_encryption_ckks_ct1_ps4",
    "user_data_encryption_ckks_ct0_ps5",
    "user_data_encryption_ckks_ct1_ps5",
    "ckks_salary_validity_ps3",
    "ckks_auction_validity_ps2",
    "ckks_credit_validity_ps4",
    "ckks_fedavg_validity_ps5",
    "ckks_matching_validity_ps5",
    "ckks_treasury_validity_ps5",
    "user_data_encryption_ct1",
    "share_decryption",
    "share_decryption_ckks",
    "share_decryption_ckks_ps2",
    "share_decryption_ckks_ps3",
    "share_decryption_ckks_ps4",
    "share_decryption_ckks_ps5",
    "relin_round1_ckks",
    "relin_round1_hybrid_ckks",
    "relin_round1_hybrid_ckks_digit_ps2",
    "decrypted_shares_aggregation",
    "decrypted_shares_aggregation_ckks",
    "decrypted_shares_aggregation_ckks_ps2",
    "decrypted_shares_aggregation_ckks_ps3",
    "decrypted_shares_aggregation_ckks_ps4",
    "decrypted_shares_aggregation_ckks_ps5",
]