[workspace]
members = [
    "pk_generation",
    "pk_aggregation",
    "user_data_encryption",
    "user_data_encryption_ct0",
    "user_data_encryption_ct1",
    "ct0_chunk_main",
    "ct0_chunk_main_root",
    "ct0_chunk_r1",
    "ct0_chunk_r1_root",
    "ct0_chunk_combine_roots",
    "ct0_chunk_pk_ct_combine",
    "ct0_chunk_gamma",
    "ct0_eval_chunk_main",
    "ct0_eval_chunk_main_root",
    "ct0_eval_chunk_r1",
    "ct0_eval_chunk_r1_root",
    "ct0_eval_chunk_combine_roots",
    "ct0_eval_chunk_pk_ct_combine",
    "ct0_eval_chunk_identity",
    "ct0_pk_commit",
    "ct0_ct_commit",
    "ct0_eval_pk",
    "ct0_eval_ct",
    "ct1_pk_commit",
    "ct1_ct_commit",
    "ct1_eval_pk",
    "ct1_eval_ct",
    "ct1_chunk_main",
    "ct1_chunk_main_root",
    "ct1_chunk_p1",
    "ct1_chunk_p1_root",
    "ct1_chunk_combine_roots",
    "ct1_chunk_pk_ct_combine",
    "ct1_chunk_gamma",
    "ct1_eval_chunk_main",
    "ct1_eval_chunk_main_root",
    "ct1_eval_chunk_p1",
    "ct1_eval_chunk_p1_root",
    "ct1_eval_chunk_combine_roots",
    "ct1_eval_chunk_pk_ct_combine",
    "ct1_eval_chunk_identity",
    "share_decryption",
    "decrypted_shares_aggregation",
]
