// SPDX-License-Identifier: LGPL-3.0-only
//
// This file is provided WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE.

//! Configuration bootstrapping for `interfold setup`.
//!
//! Generates an `interfold.config.yaml` from compiled-in contract deployment
//! addresses. This is a **dev-bootstrap tool** — it couples to the Solidity
//! build artifacts at compile time and is only invoked by the `interfold setup`
//! CLI command. Production deployments should use a proper deployment artifact
//! file instead of this compile-time approach.

use alloy::hex::FromHex;
use alloy::primitives::{Address, FixedBytes};
use alloy::signers::local::PrivateKeySigner;
use anyhow::{anyhow, bail, Result};
use e3_config::{load_config, AppConfig, RPC};
use std::fs;
use std::path::PathBuf;
use tracing::instrument;

// Generated by build.rs from packages/interfold-contracts/deployed_contracts.json
include!(concat!(env!("OUT_DIR"), "/contract_deployments.rs"));

/// The Avail network that carries the data of the Sepolia deployment.
const SEPOLIA_AVAILABILITY_RPC: &str = "https://turing-rpc.avail.so/rpc";

fn get_contract_info(name: &str) -> Result<&ContractInfo> {
    CONTRACT_DEPLOYMENTS
        .get(name)
        .ok_or(anyhow!("Could not get contract info"))
}

pub fn validate_rpc_url(url: &str) -> Result<()> {
    RPC::from_url(url)?;
    Ok(())
}

/// Derive the node's Ethereum address from its private key. Mirrors the
/// derivation in `e3_entrypoint::wallet::set` so the value written to the
/// config matches the address stored in the keystore.
pub fn derive_address(private_key: &str) -> Result<Address> {
    let bytes = FixedBytes::<32>::from_hex(private_key)
        .map_err(|e| anyhow!("Invalid private key: {}", e))?;
    Ok(PrivateKeySigner::from_bytes(&bytes)?.address())
}

/// The name, chain ID and data-availability endpoint that setup writes for `network`, or why it
/// refuses the network. The binary carries only the Sepolia deployment, so a configuration for
/// another chain would hold Sepolia's contract addresses.
pub fn network_chain(network: &str) -> Result<(&'static str, u64, &'static str)> {
    match network {
        "sepolia" => Ok(("sepolia", 11_155_111, SEPOLIA_AVAILABILITY_RPC)),
        "local" | "localhost" => bail!(
            "`interfold ciphernode setup` writes the Sepolia deployment that is built into this \
             binary. For a local chain, start from the project template's interfold.config.yaml, \
             which has the local deployment and a data_availability block."
        ),
        _ => bail!("`interfold ciphernode setup` supports only the sepolia network"),
    }
}

#[instrument(name = "app", skip_all)]
pub fn execute(
    rpc_url: &str,
    address: &Address,
    config_dir: &PathBuf,
    network: &str,
) -> Result<AppConfig> {
    let (network, chain_id, availability_rpc) = network_chain(network)?;
    fs::create_dir_all(config_dir)?;

    let config_path = config_dir.join("interfold.config.yaml");

    let config_content = format!(
        r#"---
# Interfold Configuration File
node:
  network: "{}"
  address: "{}"
chains:
  - name: "{}"
    chain_id: {}
    rpc_url: "{}"
    data_availability:
      mode: avail
      rpc_url: "{}"
    contracts:
      interfold:
        address: "{}"
        deploy_block: {}
      ciphernode_registry:
        address: "{}"
        deploy_block: {}
      bonding_registry:
        address: "{}"
        deploy_block: {}
      slashing_manager:
        address: "{}"
        deploy_block: {}
"#,
        network,
        address,
        network,
        chain_id,
        rpc_url,
        availability_rpc,
        get_contract_info("Interfold")?.address,
        get_contract_info("Interfold")?.deploy_block,
        get_contract_info("CiphernodeRegistryOwnable")?.address,
        get_contract_info("CiphernodeRegistryOwnable")?.deploy_block,
        get_contract_info("BondingRegistry")?.address,
        get_contract_info("BondingRegistry")?.deploy_block,
        get_contract_info("SlashingManager")?.address,
        get_contract_info("SlashingManager")?.deploy_block,
    );

    fs::write(config_path.clone(), config_content)?;

    let config = load_config("_default", Some(config_path.display().to_string()), None)?;

    Ok(config)
}

#[cfg(test)]
mod tests {
    use super::execute;
    use alloy::primitives::Address;
    use anyhow::Result;
    use e3_config::chain_config::DataAvailabilityMode;
    use e3_config::SEPOLIA_BOOTSTRAP_PEER;
    use std::fs;

    #[test]
    fn generated_config_uses_the_sepolia_profile_bootstrap() -> Result<()> {
        let dir = std::env::temp_dir().join(format!(
            "e3-config-setup-test-{}-{}",
            std::process::id(),
            line!()
        ));
        let _ = fs::remove_dir_all(&dir);

        let config = execute("ws://localhost:8545", &Address::ZERO, &dir, "sepolia")?;

        // The loader must actually read the prepopulated peer from `node.peers`.
        assert_eq!(config.network().name(), "sepolia");
        assert_eq!(config.peers(), vec![SEPOLIA_BOOTSTRAP_PEER.to_string()]);
        // `start` needs a data-availability reader for each chain with the Interfold contract.
        let availability = config.chains()[0]
            .data_availability
            .clone()
            .expect("the chain must have a data_availability block");
        assert_eq!(availability.mode, DataAvailabilityMode::Avail);
        assert_eq!(availability.rpc_url, "https://turing-rpc.avail.so/rpc");

        // The binary has no local deployment, so a local configuration is refused.
        let local = execute(
            "ws://localhost:8545",
            &Address::ZERO,
            &dir.join("local"),
            "local",
        )
        .expect_err("setup must refuse a local network");
        assert!(local.to_string().contains("project template"), "{local}");

        let _ = fs::remove_dir_all(&dir);
        Ok(())
    }
}
