// SPDX-License-Identifier: LGPL-3.0-only
//
// This file is provided WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE.

//! Published deployment manifest — the runtime answer to "which addresses is
//! this network on right now".
//!
//! The CLI also carries a compiled-in copy of `deployed_contracts.json` (see
//! `build.rs` and `config_setup`), but that table freezes at build time. An
//! operator running a binary from before a redeploy generates, and keeps, a
//! config pointing at contracts that no longer exist — and the failure is
//! silent, because a node syncing a dead address just never sees an event.
//! Fetching the manifest lets a node tell the operator that without shipping a
//! new binary.
//!
//! Generated by `packages/interfold-contracts/scripts/genManifest.ts` and
//! attached to each GitHub release as `manifest.json`.

use anyhow::{anyhow, Context, Result};
use e3_config::{chain_config::ChainConfig, Contract};
use serde::Deserialize;
use std::collections::BTreeMap;
use std::time::Duration;

const GITHUB_REPO: &str = "theinterfold/interfold";
const MANIFEST_ASSET: &str = "manifest.json";
const REQUEST_TIMEOUT: Duration = Duration::from_secs(20);

/// Schema versions this build knows how to read. A manifest from the future is
/// refused rather than half-parsed, so a shape change cannot make `config check`
/// silently skip contracts it does not recognise.
const SUPPORTED_SCHEMA: u32 = 1;

#[derive(Debug, Clone, Deserialize)]
pub struct Manifest {
    pub schema_version: u32,
    pub networks: BTreeMap<String, NetworkManifest>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct NetworkManifest {
    #[serde(default)]
    pub chain_id: Option<u64>,
    /// True when the deployment includes mock verifiers, i.e. proofs are
    /// accepted without being checked.
    #[serde(default)]
    pub mocks: bool,
    pub contracts: BTreeMap<String, ManifestContract>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct ManifestContract {
    pub address: String,
    #[serde(default)]
    pub deploy_block: Option<u64>,
}

#[derive(Debug, Deserialize)]
struct GitHubRelease {
    tag_name: String,
    assets: Vec<GitHubAsset>,
}

#[derive(Debug, Deserialize)]
struct GitHubAsset {
    name: String,
    browser_download_url: String,
}

/// Where a manifest came from, so the operator can tell a pinned URL from the
/// published release they were expecting.
#[derive(Debug, Clone)]
pub enum ManifestSource {
    Release(String),
    Url(String),
}

impl std::fmt::Display for ManifestSource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ManifestSource::Release(tag) => write!(f, "release {tag}"),
            ManifestSource::Url(url) => write!(f, "{url}"),
        }
    }
}

fn client() -> Result<reqwest::Client> {
    reqwest::Client::builder()
        .user_agent(concat!("interfold/", env!("CARGO_PKG_VERSION")))
        .timeout(REQUEST_TIMEOUT)
        .build()
        .context("Failed to build HTTP client")
}

async fn get_text(client: &reqwest::Client, url: &str) -> Result<String> {
    let response = client
        .get(url)
        .send()
        .await
        .with_context(|| format!("Failed to fetch {url}"))?;
    let status = response.status();
    if !status.is_success() {
        return Err(anyhow!("{url} returned {status}"));
    }
    response
        .text()
        .await
        .with_context(|| format!("Failed to read response body from {url}"))
}

fn parse(body: &str) -> Result<Manifest> {
    let manifest: Manifest =
        serde_json::from_str(body).context("Failed to parse deployment manifest")?;
    if manifest.schema_version > SUPPORTED_SCHEMA {
        return Err(anyhow!(
            "Manifest schema version {} is newer than this build understands ({}). Upgrade the CLI.",
            manifest.schema_version,
            SUPPORTED_SCHEMA
        ));
    }
    Ok(manifest)
}

/// Fetch the manifest from `url` when given, otherwise from the latest GitHub
/// release.
pub async fn fetch(url: Option<&str>) -> Result<(Manifest, ManifestSource)> {
    let client = client()?;

    if let Some(url) = url {
        let body = get_text(&client, url).await?;
        return Ok((parse(&body)?, ManifestSource::Url(url.to_string())));
    }

    let releases_url = format!("https://api.github.com/repos/{GITHUB_REPO}/releases/latest");
    let body = get_text(&client, &releases_url).await?;
    let release: GitHubRelease =
        serde_json::from_str(&body).context("Failed to parse GitHub release response")?;

    let asset = release
        .assets
        .iter()
        .find(|a| a.name == MANIFEST_ASSET)
        .ok_or_else(|| {
            anyhow!(
                "Release {} has no `{}` asset. Pass --manifest-url to point at one directly.",
                release.tag_name,
                MANIFEST_ASSET
            )
        })?;

    let body = get_text(&client, &asset.browser_download_url).await?;
    Ok((parse(&body)?, ManifestSource::Release(release.tag_name)))
}

/// One difference between a chain entry in the operator's config and the
/// manifest. `Missing` is a weaker signal than `AddressMismatch`: several config
/// contracts are optional, so its absence is only worth reporting, not failing.
#[derive(Debug, PartialEq, Eq)]
pub enum Finding {
    AddressMismatch {
        key: String,
        configured: String,
        published: String,
    },
    DeployBlockMismatch {
        key: String,
        configured: Option<u64>,
        published: u64,
    },
    Missing {
        key: String,
        published: String,
    },
    ChainIdMismatch {
        configured: u64,
        published: u64,
    },
}

impl Finding {
    /// Whether this finding means the node is pointed at the wrong chain or the
    /// wrong contracts. A missing optional contract or a stale `deploy_block`
    /// degrades sync, but only these make the node silently do nothing.
    pub fn is_error(&self) -> bool {
        matches!(
            self,
            Finding::AddressMismatch { .. } | Finding::ChainIdMismatch { .. }
        )
    }
}

fn configured_contracts(chain: &ChainConfig) -> Vec<(&'static str, Option<&Contract>)> {
    let c = &chain.contracts;
    vec![
        ("interfold", Some(&c.interfold)),
        ("ciphernode_registry", Some(&c.ciphernode_registry)),
        ("bonding_registry", Some(&c.bonding_registry)),
        ("slashing_manager", c.slashing_manager.as_ref()),
        ("fee_token", c.fee_token.as_ref()),
        ("faucet", c.faucet.as_ref()),
        // `e3_program` is intentionally not compared. A deployment can have many
        // registered E3 programs and each application points at its own, so the
        // protocol manifest cannot say which one a node should use. The manifest
        // does not publish the key either; this list documents the omission.
        (
            "dkg_fold_attestation_verifier",
            c.dkg_fold_attestation_verifier.as_ref(),
        ),
    ]
}

/// Compare one configured chain against its published network entry.
///
/// Contracts present in the config but absent from the manifest are not
/// reported: a local or custom deployment legitimately has addresses the
/// published manifest never describes, and flagging those would train operators
/// to ignore the output.
pub fn compare(chain: &ChainConfig, network: &NetworkManifest) -> Vec<Finding> {
    let mut findings = Vec::new();

    // Catches the copy-paste failure where a chain entry keeps a name like
    // `sepolia` but points at another network's RPC. The addresses would all
    // match the manifest while resolving to nothing on the wire.
    if let (Some(configured), Some(published)) = (chain.chain_id, network.chain_id) {
        if configured != published {
            findings.push(Finding::ChainIdMismatch {
                configured,
                published,
            });
        }
    }

    for (key, configured) in configured_contracts(chain) {
        let Some(published) = network.contracts.get(key) else {
            continue;
        };

        let Some(configured) = configured else {
            findings.push(Finding::Missing {
                key: key.to_string(),
                published: published.address.clone(),
            });
            continue;
        };

        // Addresses are compared case-insensitively: EIP-55 checksumming is
        // presentational, and an operator who lowercased an address by hand has
        // not misconfigured anything.
        if !configured
            .address_str()
            .eq_ignore_ascii_case(&published.address)
        {
            findings.push(Finding::AddressMismatch {
                key: key.to_string(),
                configured: configured.address_str().to_string(),
                published: published.address.clone(),
            });
            continue;
        }

        if let Some(published_block) = published.deploy_block {
            if configured.deploy_block() != Some(published_block) {
                findings.push(Finding::DeployBlockMismatch {
                    key: key.to_string(),
                    configured: configured.deploy_block(),
                    published: published_block,
                });
            }
        }
    }

    findings
}

#[cfg(test)]
mod tests {
    use super::*;

    fn network(contracts: &[(&str, &str, Option<u64>)]) -> NetworkManifest {
        NetworkManifest {
            chain_id: Some(11155111),
            mocks: false,
            contracts: contracts
                .iter()
                .map(|(k, addr, block)| {
                    (
                        k.to_string(),
                        ManifestContract {
                            address: addr.to_string(),
                            deploy_block: *block,
                        },
                    )
                })
                .collect(),
        }
    }

    fn chain_with_id(interfold: &str, chain_id: Option<u64>) -> ChainConfig {
        let yaml = format!(
            r#"
name: sepolia
rpc_url: "wss://example.invalid"
{}
contracts:
  interfold:
    address: "{interfold}"
    deploy_block: 10
  ciphernode_registry: "0x0000000000000000000000000000000000000002"
  bonding_registry: "0x0000000000000000000000000000000000000003"
"#,
            chain_id
                .map(|id| format!("chain_id: {id}"))
                .unwrap_or_default()
        );
        serde_yaml::from_str(&yaml).expect("test chain config should parse")
    }

    fn chain(interfold: &str, deploy_block: Option<u64>) -> ChainConfig {
        let yaml = format!(
            r#"
name: sepolia
rpc_url: "wss://example.invalid"
contracts:
  interfold:
    address: "{interfold}"
    deploy_block: {}
  ciphernode_registry: "0x0000000000000000000000000000000000000002"
  bonding_registry: "0x0000000000000000000000000000000000000003"
"#,
            deploy_block
                .map(|b| b.to_string())
                .unwrap_or_else(|| "~".to_string())
        );
        serde_yaml::from_str(&yaml).expect("test chain config should parse")
    }

    #[test]
    fn matching_config_yields_no_findings() {
        let c = chain("0x0000000000000000000000000000000000000001", Some(10));
        let n = network(&[
            (
                "interfold",
                "0x0000000000000000000000000000000000000001",
                Some(10),
            ),
            (
                "ciphernode_registry",
                "0x0000000000000000000000000000000000000002",
                None,
            ),
            (
                "bonding_registry",
                "0x0000000000000000000000000000000000000003",
                None,
            ),
        ]);
        assert_eq!(compare(&c, &n), vec![]);
    }

    #[test]
    fn stale_address_is_an_error() {
        let c = chain("0x000000000000000000000000000000000000dead", Some(10));
        let n = network(&[(
            "interfold",
            "0x0000000000000000000000000000000000000001",
            Some(10),
        )]);
        let findings = compare(&c, &n);
        assert_eq!(findings.len(), 1);
        assert!(findings[0].is_error());
    }

    #[test]
    fn checksum_casing_is_not_a_mismatch() {
        let c = chain("0xd49990bcba083dcf05eda2b201e7e091dfbb4642", Some(10));
        let n = network(&[(
            "interfold",
            "0xd49990bcBA083dcF05eda2b201e7e091dFbb4642",
            Some(10),
        )]);
        assert_eq!(compare(&c, &n), vec![]);
    }

    #[test]
    fn stale_deploy_block_is_reported_but_not_an_error() {
        let c = chain("0x0000000000000000000000000000000000000001", Some(1));
        let n = network(&[(
            "interfold",
            "0x0000000000000000000000000000000000000001",
            Some(99),
        )]);
        let findings = compare(&c, &n);
        assert_eq!(findings.len(), 1);
        assert!(!findings[0].is_error());
    }

    #[test]
    fn wrong_chain_id_is_an_error_even_when_addresses_match() {
        let c = chain_with_id("0x0000000000000000000000000000000000000001", Some(31337));
        let n = network(&[(
            "interfold",
            "0x0000000000000000000000000000000000000001",
            Some(10),
        )]);
        let findings = compare(&c, &n);
        assert_eq!(
            findings,
            vec![Finding::ChainIdMismatch {
                configured: 31337,
                published: 11155111,
            }]
        );
        assert!(findings[0].is_error());
    }

    #[test]
    fn absent_chain_id_is_not_compared() {
        let c = chain_with_id("0x0000000000000000000000000000000000000001", None);
        let n = network(&[(
            "interfold",
            "0x0000000000000000000000000000000000000001",
            Some(10),
        )]);
        assert_eq!(compare(&c, &n), vec![]);
    }

    #[test]
    fn future_schema_version_is_refused() {
        let body = r#"{"schema_version": 999, "networks": {}}"#;
        assert!(parse(body).is_err());
    }
}
