// SPDX-License-Identifier: LGPL-3.0-only
//
// This file is provided WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE.

//! Code generation for the CKKS Decrypted Shares Aggregation circuit:
//! Prover.toml and configs fragment.

use crate::circuits::computation::Computation;
use crate::threshold::decrypted_shares_aggregation_ckks::circuit::{
    DecryptedSharesAggregationCkksCircuit, DecryptedSharesAggregationCkksCircuitData,
};
use crate::threshold::decrypted_shares_aggregation_ckks::computation::{Configs, Inputs};
use crate::threshold::user_data_encryption_ckks::CkksPreset;
use crate::Circuit;
use crate::CircuitCodegen;
use crate::CircuitsErrors;
use crate::{Artifacts, CodegenConfigs, CodegenToml};

impl CircuitCodegen for DecryptedSharesAggregationCkksCircuit {
    type Preset = CkksPreset;
    type Data = DecryptedSharesAggregationCkksCircuitData;
    type Error = CircuitsErrors;

    fn codegen(&self, preset: Self::Preset, data: &Self::Data) -> Result<Artifacts, Self::Error> {
        let inputs = Inputs::compute(preset.clone(), data)?;
        let configs = Configs::compute(preset, &())?;

        let toml = generate_toml(inputs)?;
        let configs_str = generate_configs(&configs);

        Ok(Artifacts {
            toml,
            configs: configs_str,
        })
    }
}

pub fn generate_toml(inputs: Inputs) -> Result<CodegenToml, CircuitsErrors> {
    let json = inputs.to_json().map_err(CircuitsErrors::SerdeJson)?;
    Ok(toml::to_string(&json)?)
}

/// Noir config module for a CKKS on-chain `ParamSet`: set 0 keeps the
/// canonical `ckks_aggregation` (bin `decrypted_shares_aggregation_ckks`);
/// other sets get `ckks_aggregation_ps<N>` (bin
/// `decrypted_shares_aggregation_ckks_ps<N>`).
pub fn config_module_for_param_set(param_set: u8) -> String {
    if param_set == 0 {
        "ckks_aggregation".to_string()
    } else {
        format!("ckks_aggregation_ps{param_set}")
    }
}

/// Bin package for a CKKS on-chain `ParamSet` (see [`config_module_for_param_set`]).
pub fn bin_package_for_param_set(param_set: u8) -> String {
    if param_set == 0 {
        "decrypted_shares_aggregation_ckks".to_string()
    } else {
        format!("decrypted_shares_aggregation_ckks_ps{param_set}")
    }
}

/// Full `.nr` file (header + fragment) for one on-chain `ParamSet`,
/// level 0. Same global names in every set so the bin `main.nr` bodies
/// are identical.
pub fn generate_configs_nr_for_param_set(param_set: u8, configs: &Configs) -> String {
    format!(
        "// SPDX-License-Identifier: LGPL-3.0-only\n//\n// This file is provided WITHOUT ANY WARRANTY;\n// without even the implied warranty of MERCHANTABILITY\n// or FITNESS FOR A PARTICULAR PURPOSE.\n//\n// Auto-generated by e3-zk-helpers decrypted_shares_aggregation_ckks codegen\n// (example gen_ckks_agg_prover --param-set {param_set}). Do not hand-edit.\n// CKKS on-chain ParamSet {param_set}, level 0: L={}.\n\n{}",
        configs.l,
        generate_configs(configs)
    )
}

/// Generates the decrypted_shares_aggregation_ckks config fragment.
///
/// The emitted `QIS` are the preset's LEVEL-0 moduli (what `Configs::compute`
/// derives). The current pipeline decrypts at level 0; for a rescaled
/// ciphertext the witnesses carry fewer limbs than `L` here, so the configs
/// must be regenerated from the shares' level before proving — `nargo
/// execute` fails loudly on the shape mismatch otherwise.
pub fn generate_configs(configs: &Configs) -> CodegenConfigs {
    let prefix = <DecryptedSharesAggregationCkksCircuit as Circuit>::PREFIX;
    let qis_str = configs
        .moduli
        .iter()
        .map(|q| q.to_string())
        .collect::<Vec<_>>()
        .join(", ");

    format!(
        r#"use crate::core::threshold::decrypted_shares_aggregation_ckks::Configs as DecryptedSharesAggregationCkksConfigs;

/************************************
-------------------------------------
decrypted_shares_aggregation_ckks (CIRCUIT 7-CKKS)
-------------------------------------
************************************/

pub global {prefix}_L: u32 = {};
pub global {prefix}_QIS: [Field; {prefix}_L] = [{}];
pub global {prefix}_BIT_D_NATIVE: u32 = {};

pub global {prefix}_CONFIGS: DecryptedSharesAggregationCkksConfigs<{prefix}_L>
     = DecryptedSharesAggregationCkksConfigs::new({prefix}_QIS);
"#,
        configs.l, qis_str, configs.bits.d_native_bit,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::threshold::user_data_encryption_ckks::insecure_512_ckks;

    #[test]
    fn test_configs_generation() {
        let preset = insecure_512_ckks().unwrap();
        let configs = Configs::compute(preset, &()).unwrap();
        let prefix: &str = <DecryptedSharesAggregationCkksCircuit as Circuit>::PREFIX;

        let codegen_configs = generate_configs(&configs);

        assert!(codegen_configs.contains("decrypted_shares_aggregation_ckks"));
        assert!(codegen_configs.contains(&format!(
            "{}_BIT_D_NATIVE: u32 = {}",
            prefix, configs.bits.d_native_bit
        )));
        assert!(codegen_configs.contains(&format!("{prefix}_CONFIGS:")));
    }
}
