// SPDX-License-Identifier: LGPL-3.0-only
//
// This file is provided WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE.

//! Code generation for the CKKS Decrypted Shares Aggregation circuit:
//! Prover.toml and configs fragment.

use crate::circuits::computation::Computation;
use crate::threshold::decrypted_shares_aggregation_ckks::circuit::{
    DecryptedSharesAggregationCkksCircuit, DecryptedSharesAggregationCkksCircuitData,
};
use crate::threshold::decrypted_shares_aggregation_ckks::computation::{Configs, Inputs};
use crate::threshold::user_data_encryption_ckks::CkksPreset;
use crate::Circuit;
use crate::CircuitCodegen;
use crate::CircuitsErrors;
use crate::{Artifacts, CodegenConfigs, CodegenToml};

impl CircuitCodegen for DecryptedSharesAggregationCkksCircuit {
    type Preset = CkksPreset;
    type Data = DecryptedSharesAggregationCkksCircuitData;
    type Error = CircuitsErrors;

    fn codegen(&self, preset: Self::Preset, data: &Self::Data) -> Result<Artifacts, Self::Error> {
        let inputs = Inputs::compute(preset.clone(), data)?;
        // Configs at the SHARES' level (the opening-level rule).
        let level = preset
            .params
            .moduli()
            .len()
            .saturating_sub(data.d_share_polys[0].ctx().moduli().len());
        let configs = Configs::compute_at_level(&preset, level)?;

        let toml = generate_toml(inputs)?;
        let configs_str = generate_configs(&configs);

        Ok(Artifacts {
            toml,
            configs: configs_str,
        })
    }
}

pub fn generate_toml(inputs: Inputs) -> Result<CodegenToml, CircuitsErrors> {
    let json = inputs.to_json().map_err(CircuitsErrors::SerdeJson)?;
    Ok(toml::to_string(&json)?)
}

/// Noir config module for a CKKS on-chain `ParamSet`: set 0 keeps the
/// canonical `ckks_aggregation` (bin `decrypted_shares_aggregation_ckks`);
/// other sets get `ckks_aggregation_ps<N>` (bin
/// `decrypted_shares_aggregation_ckks_ps<N>`).
pub fn config_module_for_param_set(param_set: u8) -> String {
    if param_set == 0 {
        "ckks_aggregation".to_string()
    } else {
        format!("ckks_aggregation_ps{param_set}")
    }
}

/// Bin package for a CKKS on-chain `ParamSet` (see [`config_module_for_param_set`]).
pub fn bin_package_for_param_set(param_set: u8) -> String {
    if param_set == 0 {
        "decrypted_shares_aggregation_ckks".to_string()
    } else {
        format!("decrypted_shares_aggregation_ckks_ps{param_set}")
    }
}

/// Full `.nr` file (header + fragment) for one on-chain `ParamSet` at
/// the level `configs` were computed at (the set's OPENING level for the
/// checked-in files). Same global names in every set so the bin
/// `main.nr` bodies are identical.
pub fn generate_configs_nr_for_param_set(param_set: u8, configs: &Configs) -> String {
    format!(
        "// SPDX-License-Identifier: LGPL-3.0-only\n//\n// This file is provided WITHOUT ANY WARRANTY;\n// without even the implied warranty of MERCHANTABILITY\n// or FITNESS FOR A PARTICULAR PURPOSE.\n//\n// Auto-generated by e3-zk-helpers decrypted_shares_aggregation_ckks codegen\n// (example gen_ckks_agg_prover --param-set {param_set} --level {}). Do not hand-edit.\n// CKKS on-chain ParamSet {param_set}, OPENING level {}: L={} moduli remain.\n\n{}",
        configs.level,
        configs.level,
        configs.l,
        generate_configs(configs)
    )
}

/// The C7-CKKS configs for an on-chain `ParamSet` at its OPENING level
/// (`ckks_opening_level_for_param_set`).
pub fn configs_for_param_set(param_set: u8) -> Result<Configs, CircuitsErrors> {
    let level = e3_fhe_params::ckks_presets::ckks_opening_level_for_param_set(param_set)
        .map_err(|e| CircuitsErrors::Other(e.to_string()))?;
    configs_for_param_set_at_level(param_set, level)
}

/// [`configs_for_param_set`] at an explicit level.
pub fn configs_for_param_set_at_level(
    param_set: u8,
    level: usize,
) -> Result<Configs, CircuitsErrors> {
    let preset = crate::threshold::user_data_encryption_ckks::ckks_preset_for_param_set(param_set)?;
    Configs::compute_at_level(&preset, level)
}

/// Generates the decrypted_shares_aggregation_ckks config fragment.
///
/// The emitted `QIS` are the moduli that remain at `configs.level`
/// (`Configs::compute_at_level`); the witnesses of a share at another
/// level carry a different limb count and `nargo execute` fails loudly
/// on the shape mismatch.
pub fn generate_configs(configs: &Configs) -> CodegenConfigs {
    use num_bigint::BigUint;
    let prefix = <DecryptedSharesAggregationCkksCircuit as Circuit>::PREFIX;
    let qis_str = configs
        .moduli
        .iter()
        .map(|q| q.to_string())
        .collect::<Vec<_>>()
        .join(", ");
    // Q_l and Q_l / q_l: the bounds that make the C7-CKKS CRT glue sound
    // (`verify_crt_reconstruction_ckks` range-checks u_global < Q_l and
    // each quotient r_l < Q_l / q_l so the field identity pins the lift).
    let q_full = configs
        .moduli
        .iter()
        .fold(BigUint::from(1u8), |acc, q| acc * BigUint::from(*q));
    let q_over_ql_str = configs
        .moduli
        .iter()
        .map(|q| (&q_full / BigUint::from(*q)).to_string())
        .collect::<Vec<_>>()
        .join(", ");

    format!(
        r#"use crate::core::threshold::decrypted_shares_aggregation_ckks::Configs as DecryptedSharesAggregationCkksConfigs;

/************************************
-------------------------------------
decrypted_shares_aggregation_ckks (CIRCUIT 7-CKKS)
-------------------------------------
************************************/

pub global {prefix}_L: u32 = {};
pub global {prefix}_QIS: [Field; {prefix}_L] = [{}];
pub global {prefix}_BIT_D_NATIVE: u32 = {};
/// Coefficient window = ring degree N. CKKS has no sparse-message
/// assumption, and this MUST equal C6-CKKS's `SHARE_DECRYPTION_CKKS_N` so
/// both circuits hash the same window into `d_commitment`.
pub global {prefix}_N: u32 = {};
/// Q_l = prod(QIS); must be < 2^253 (fits the scalar field).
pub global {prefix}_Q_FULL: Field = {};
/// Q_l / q_l per limb: exclusive bound of the honest CRT quotient.
pub global {prefix}_Q_OVER_QL: [Field; {prefix}_L] = [{}];

pub global {prefix}_CONFIGS: DecryptedSharesAggregationCkksConfigs<{prefix}_L>
     = DecryptedSharesAggregationCkksConfigs::new(
    {prefix}_QIS,
    {prefix}_Q_FULL,
    {prefix}_Q_OVER_QL,
);
"#,
        configs.l,
        qis_str,
        configs.bits.d_native_bit,
        configs.max_msg_non_zero_coeffs,
        q_full,
        q_over_ql_str,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::threshold::user_data_encryption_ckks::insecure_512_ckks;

    #[test]
    fn test_configs_generation() {
        let preset = insecure_512_ckks().unwrap();
        let configs = Configs::compute(preset, &()).unwrap();
        let prefix: &str = <DecryptedSharesAggregationCkksCircuit as Circuit>::PREFIX;

        let codegen_configs = generate_configs(&configs);

        assert!(codegen_configs.contains("decrypted_shares_aggregation_ckks"));
        assert!(codegen_configs.contains(&format!(
            "{}_BIT_D_NATIVE: u32 = {}",
            prefix, configs.bits.d_native_bit
        )));
        assert!(codegen_configs.contains(&format!("{prefix}_CONFIGS:")));
    }

    /// Per-set configs are generated at the OPENING level: the limbs
    /// that remain there, not the full chain.
    #[test]
    fn per_param_set_configs_are_at_the_opening_level() {
        for (set, level, l) in [(0u8, 0usize, 2usize), (2, 37, 1), (3, 1, 2), (4, 3, 2)] {
            let c = configs_for_param_set(set).unwrap();
            assert_eq!((c.level, c.l), (level, l), "param set {set}");
            let nr = generate_configs_nr_for_param_set(set, &c);
            assert!(nr.contains(&format!("DECRYPTED_SHARES_AGGREGATION_CKKS_L: u32 = {l};")));
            assert!(nr.contains(&format!("OPENING level {level}")));
        }
        assert_eq!(configs_for_param_set_at_level(4, 0).unwrap().l, 5);
    }

    /// Checked-in per-set configs match fresh opening-level codegen.
    #[test]
    fn checked_in_per_set_configs_match_codegen() {
        let root = concat!(env!("CARGO_MANIFEST_DIR"), "/../..");
        let strip = |s: &str| {
            s.chars()
                .filter(|c| !c.is_whitespace())
                .collect::<String>()
                .replace(",]", "]")
        };
        for set in [0u8, 2, 3, 4, 5] {
            let c = configs_for_param_set(set).unwrap();
            let module = config_module_for_param_set(set);
            let path = format!("{root}/circuits/lib/src/configs/{module}.nr");
            let on_disk = std::fs::read_to_string(&path).unwrap_or_else(|e| {
                panic!("{path}: {e} (run gen_ckks_agg_prover --param-set {set})")
            });
            assert_eq!(
                strip(&on_disk),
                strip(&generate_configs_nr_for_param_set(set, &c)),
                "drift in {path}"
            );
        }
    }
}
