// SPDX-License-Identifier: LGPL-3.0-only
//
// This file is provided WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE.

//! Replay-safe gate for value-bearing compute effects.

use actix::{Actor, Context, Handler, Recipient};
use e3_events::{
    ComputeRequestKind, E3Stage, E3id, Event, EventContextAccessors, EventSubscriber, EventType,
    InterfoldEvent, InterfoldEventData,
};
use e3_utils::MAILBOX_LIMIT;
use std::collections::HashMap;
use tracing::info;

use e3_events::BusHandle;

type RequestKey = (E3id, ComputeRequestKind);

/// Buffers compute effects observed during EventStore replay. Identical
/// semantic requests are deduplicated independently of their correlation ID;
/// the newest HLC context wins so a request regenerated by a hydrated actor is
/// preferred over its stale pre-crash copy.
pub(crate) struct ComputeEffectGate {
    target: Recipient<InterfoldEvent>,
    enabled: bool,
    pending: HashMap<RequestKey, InterfoldEvent>,
}

impl ComputeEffectGate {
    fn new(target: Recipient<InterfoldEvent>) -> Self {
        Self {
            target,
            enabled: false,
            pending: HashMap::new(),
        }
    }

    pub(crate) fn attach(bus: &BusHandle, target: Recipient<InterfoldEvent>) {
        let gate = Self::new(target).start();
        bus.subscribe_all(
            &[
                EventType::ComputeRequest,
                EventType::EffectsEnabled,
                EventType::E3RequestComplete,
                EventType::E3Failed,
                EventType::E3StageChanged,
            ],
            gate.recipient(),
        );
    }

    fn queue(&mut self, event: InterfoldEvent) {
        let InterfoldEventData::ComputeRequest(request) = event.get_data() else {
            return;
        };
        let key = (request.e3_id.clone(), request.request.clone());
        match self.pending.entry(key) {
            std::collections::hash_map::Entry::Occupied(mut entry)
                if event.ts() > entry.get().ts() =>
            {
                entry.insert(event);
            }
            std::collections::hash_map::Entry::Vacant(entry) => {
                entry.insert(event);
            }
            _ => {}
        }
    }

    fn enable(&mut self) {
        self.enabled = true;
        let mut pending: Vec<_> = self.pending.drain().map(|(_, event)| event).collect();
        pending.sort_by_key(EventContextAccessors::ts);
        let count = pending.len();
        for event in pending {
            self.target.do_send(event);
        }
        info!(count, "released replay-safe compute effects");
    }

    fn cancel(&mut self, e3_id: &E3id) {
        self.pending
            .retain(|(pending_id, _), _| pending_id != e3_id);
    }
}

impl Actor for ComputeEffectGate {
    type Context = Context<Self>;

    fn started(&mut self, ctx: &mut Self::Context) {
        ctx.set_mailbox_capacity(MAILBOX_LIMIT);
    }
}

impl Handler<InterfoldEvent> for ComputeEffectGate {
    type Result = ();

    fn handle(&mut self, event: InterfoldEvent, _: &mut Self::Context) {
        match event.get_data() {
            InterfoldEventData::ComputeRequest(_) if self.enabled => self.target.do_send(event),
            InterfoldEventData::ComputeRequest(_) => self.queue(event),
            InterfoldEventData::EffectsEnabled(_) => self.enable(),
            InterfoldEventData::E3RequestComplete(complete) => self.cancel(&complete.e3_id),
            InterfoldEventData::E3Failed(failed) => self.cancel(&failed.e3_id),
            InterfoldEventData::E3StageChanged(stage)
                if matches!(stage.new_stage, E3Stage::Complete | E3Stage::Failed) =>
            {
                self.cancel(&stage.e3_id)
            }
            _ => {}
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use actix::{Message, ResponseFuture};
    use e3_events::{
        ComputeRequest, CorrelationId, E3RequestComplete, EffectsEnabled,
        EventConstructorWithTimestamp, EventSource, InterfoldEvent, PkBfvProofRequest, Unsequenced,
        ZkRequest,
    };
    use e3_fhe_params::BfvPreset;
    use e3_utils::ArcBytes;
    use e3_zk_helpers::CiphernodesCommitteeSize;

    #[derive(Message)]
    #[rtype(result = "Vec<CorrelationId>")]
    struct Received;

    #[derive(Default)]
    struct Recorder(Vec<CorrelationId>);

    impl Actor for Recorder {
        type Context = Context<Self>;
    }

    impl Handler<InterfoldEvent> for Recorder {
        type Result = ();

        fn handle(&mut self, event: InterfoldEvent, _: &mut Self::Context) {
            if let InterfoldEventData::ComputeRequest(request) = event.get_data() {
                self.0.push(request.correlation_id);
            }
        }
    }

    impl Handler<Received> for Recorder {
        type Result = ResponseFuture<Vec<CorrelationId>>;

        fn handle(&mut self, _: Received, _: &mut Self::Context) -> Self::Result {
            let received = self.0.clone();
            Box::pin(async move { received })
        }
    }

    fn compute(correlation_id: CorrelationId, timestamp: u128) -> InterfoldEvent {
        let request = ComputeRequest::zk(
            ZkRequest::PkBfv(PkBfvProofRequest::new(
                ArcBytes::from_bytes(&[]),
                BfvPreset::default(),
                CiphernodesCommitteeSize::Micro,
            )),
            correlation_id,
            E3id::new("4", 1),
        );
        InterfoldEvent::<Unsequenced>::new_with_timestamp(
            request.into(),
            None,
            timestamp,
            None,
            EventSource::Local,
        )
        .into_sequenced(1)
    }

    fn effects_enabled() -> InterfoldEvent {
        InterfoldEvent::<Unsequenced>::new_with_timestamp(
            EffectsEnabled::new().into(),
            None,
            30,
            None,
            EventSource::Local,
        )
        .into_sequenced(2)
    }

    fn completed() -> InterfoldEvent {
        InterfoldEvent::<Unsequenced>::new_with_timestamp(
            E3RequestComplete {
                e3_id: E3id::new("4", 1),
            }
            .into(),
            None,
            25,
            None,
            EventSource::Local,
        )
        .into_sequenced(2)
    }

    #[actix::test]
    async fn buffers_until_enabled_and_keeps_newest_semantic_retry() {
        let recorder = Recorder::default().start();
        let gate = ComputeEffectGate::new(recorder.clone().recipient()).start();
        let stale = CorrelationId::new();
        let regenerated = CorrelationId::new();

        gate.send(compute(stale, 10)).await.unwrap();
        gate.send(compute(regenerated, 20)).await.unwrap();
        assert!(recorder.send(Received).await.unwrap().is_empty());

        gate.send(effects_enabled()).await.unwrap();
        assert_eq!(recorder.send(Received).await.unwrap(), vec![regenerated]);
    }

    #[actix::test]
    async fn terminal_e3_cancels_buffered_effects() {
        let recorder = Recorder::default().start();
        let gate = ComputeEffectGate::new(recorder.clone().recipient()).start();

        gate.send(compute(CorrelationId::new(), 10)).await.unwrap();
        gate.send(completed()).await.unwrap();
        gate.send(effects_enabled()).await.unwrap();

        assert!(recorder.send(Received).await.unwrap().is_empty());
    }
}
