// SPDX-License-Identifier: LGPL-3.0-only
//
// This file is provided WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE.

//! Replay-safe gate for value-bearing compute effects.

use actix::{Actor, Context, Handler, Recipient};
use e3_events::{
    BusHandle, ComputeRequestError, ComputeRequestKind, ComputeResponse, CorrelationId, E3Stage,
    E3id, Event, EventContextAccessors, EventPublisher, EventSubscriber, EventType, InterfoldEvent,
    InterfoldEventData, ProofType, VerifyShareProofsRequest, ZkRequest,
};
use e3_utils::MAILBOX_LIMIT;
use std::collections::HashMap;
use tracing::{debug, info};

use e3_trbfv::lbfv_operation::LbfvOperationId;

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
enum RequestIdentity {
    Legacy(ComputeRequestKind),
    Lbfv(LbfvOperationId),
}

type RequestKey = (E3id, RequestIdentity);

#[derive(Clone)]
enum ComputeOutcome {
    Response(ComputeResponse),
    Error(ComputeRequestError),
}

struct ForwardedRequest {
    correlation_id: CorrelationId,
    waiting: Vec<CorrelationId>,
    outcome: Option<ComputeOutcome>,
    /// Unix seconds when the request was forwarded. An entry without an outcome
    /// older than `stale_after_secs` is evicted so a retry can run again.
    sent_at: u64,
}

/// A forwarded request without an outcome becomes re-forwardable after this many
/// seconds, so a response the event bus dropped cannot park retries forever. The
/// value must stay below the public-key aggregator's l-BFV correlation timeouts,
/// which bound the only in-process re-publishers of an identical request. The
/// eviction applies to every compute kind: a re-published legacy request (for
/// example a streaming nodes-fold step) must also run again, and a duplicated
/// job is harmless because responses still resolve by correlation ID.
const FORWARDED_STALE_AFTER_SECS: u64 = 300;

fn now_unix_secs() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}

/// Buffers compute effects observed during EventStore replay. Legacy requests
/// use their complete payload as the deduplication key. l-BFV requests use
/// their stable operation ID. Identical semantic requests are deduplicated
/// independently of their correlation ID; the newest HLC context wins so a
/// request regenerated by a hydrated actor is preferred over its stale
/// pre-crash copy.
///
/// Deduplication spans the replay-to-live boundary. A later request with the

/// same identity does not repeat the compute. The gate sends the result to each
/// requester's correlation ID, including IDs created after restart. Terminal
/// events clear the per-E3 keys.
pub(crate) struct ComputeEffectGate {
    target: Recipient<InterfoldEvent>,
    bus: Option<BusHandle>,
    enabled: bool,
    pending: HashMap<RequestKey, InterfoldEvent>,
    forwarded: HashMap<RequestKey, ForwardedRequest>,
    request_keys_by_correlation: HashMap<CorrelationId, RequestKey>,
    replayed_responses: HashMap<RequestKey, ComputeOutcome>,
    stages: HashMap<E3id, E3Stage>,
    /// Age after which a forwarded request without an outcome is evicted.
    stale_after_secs: u64,
}

impl ComputeEffectGate {
    fn new(target: Recipient<InterfoldEvent>, initial_stages: HashMap<E3id, E3Stage>) -> Self {
        Self {
            target,
            bus: None,
            enabled: false,
            pending: HashMap::new(),
            forwarded: HashMap::new(),
            request_keys_by_correlation: HashMap::new(),
            replayed_responses: HashMap::new(),
            stages: initial_stages,
            stale_after_secs: FORWARDED_STALE_AFTER_SECS,
        }
    }

    fn with_bus(mut self, bus: BusHandle) -> Self {
        self.bus = Some(bus);
        self
    }

    fn stage_rank(stage: &E3Stage) -> u8 {
        match stage {
            E3Stage::None => 0,
            E3Stage::Requested => 1,
            E3Stage::CommitteeFinalized => 2,
            E3Stage::KeyPublished => 3,
            E3Stage::CiphertextReady => 4,
            E3Stage::Complete => 5,
            E3Stage::Failed => 6,
        }
    }

    fn is_dkg_request(kind: &ComputeRequestKind) -> bool {
        match kind {
            ComputeRequestKind::TrBFV(request) => matches!(
                request,
                e3_trbfv::TrBFVRequest::GenEsiSss(_)
                    | e3_trbfv::TrBFVRequest::GenPkShareAndSkSss(_)
                    | e3_trbfv::TrBFVRequest::CalculateDecryptionKey(_)
                    | e3_trbfv::TrBFVRequest::GenLbfvKeyShares(_)
            ),
            ComputeRequestKind::Zk(request) => {
                matches!(
                    request,
                    ZkRequest::PkBfv(_)
                        | ZkRequest::PkGeneration(_)
                        | ZkRequest::ShareComputation(_)
                        | ZkRequest::ShareEncryption(_)
                        | ZkRequest::DkgShareDecryption(_)
                        | ZkRequest::VerifyShareDecryptionProofs(_)
                        | ZkRequest::PkAggregation(_)
                        | ZkRequest::NodeDkgFold(_)
                        | ZkRequest::NodesFoldStep(_)
                        | ZkRequest::DkgAggregation(_)
                        | ZkRequest::LbfvPkGeneration(_)
                        | ZkRequest::RlkGeneration(_)
                        | ZkRequest::LbfvPkAggregation(_)
                        | ZkRequest::RlkAggregation(_)
                        | ZkRequest::LbfvGenerationFold(_)
                        | ZkRequest::NodeDkgFoldV2(_)
                        | ZkRequest::NodesFoldV2Step(_)
                        | ZkRequest::LbfvAggregationFold(_)
                        | ZkRequest::DkgAggregationV2(_)
                ) || matches!(
                    request,
                    ZkRequest::VerifyShareProofs(request)
                        if !Self::is_threshold_decryption_verification(request)
                )
            }
        }
    }

    /// `VerifyShareProofs` carries both DKG proofs (C1-C3) and final
    /// threshold-decryption proofs (C6). Inspect the signed proof type so a
    /// lifecycle filter cannot discard valid C6 work after key publication.
    fn is_threshold_decryption_verification(request: &VerifyShareProofsRequest) -> bool {
        let mut proofs = request
            .party_proofs
            .iter()
            .flat_map(|party| party.signed_proofs.iter());
        let Some(first) = proofs.next() else {
            return false;
        };

        first.payload.proof_type == ProofType::C6ThresholdShareDecryption
            && proofs.all(|proof| proof.payload.proof_type == ProofType::C6ThresholdShareDecryption)
    }

    fn request_is_obsolete(&self, e3_id: &E3id, kind: &ComputeRequestKind) -> bool {
        Self::request_is_obsolete_at_stage(self.stages.get(e3_id), kind)
    }

    fn request_is_obsolete_at_stage(stage: Option<&E3Stage>, kind: &ComputeRequestKind) -> bool {
        match stage {
            Some(E3Stage::Complete | E3Stage::Failed) => true,
            Some(stage) if Self::stage_rank(stage) >= Self::stage_rank(&E3Stage::KeyPublished) => {
                Self::is_dkg_request(kind)
            }
            _ => false,
        }
    }

    fn record_stage(&mut self, e3_id: E3id, new_stage: E3Stage) {
        let should_advance = self
            .stages
            .get(&e3_id)
            .map(|current| Self::stage_rank(&new_stage) > Self::stage_rank(current))
            .unwrap_or(true);
        if should_advance {
            self.stages.insert(e3_id.clone(), new_stage);
        }

        let current_stage = self.stages.get(&e3_id).cloned();
        self.pending.retain(|(pending_id, _), event| {
            let kind = match event.get_data() {
                InterfoldEventData::ComputeRequest(request) => Some(&request.request),
                _ => None,
            };
            pending_id != &e3_id
                || !kind.is_some_and(|kind| {
                    Self::request_is_obsolete_at_stage(current_stage.as_ref(), kind)
                })
        });
    }

    fn request_identity(kind: &ComputeRequestKind) -> RequestIdentity {
        let operation_id = match kind {
            ComputeRequestKind::TrBFV(request) => request.lbfv_operation_id(),
            ComputeRequestKind::Zk(request) => request.lbfv_operation_id(),
        };
        operation_id
            .map(RequestIdentity::Lbfv)
            .unwrap_or_else(|| RequestIdentity::Legacy(kind.clone()))
    }

    /// Forward a compute once. Send its outcome to later request IDs.
    fn forward(&mut self, event: InterfoldEvent) -> bool {
        if let InterfoldEventData::ComputeRequest(request) = event.get_data() {
            if self.request_is_obsolete(&request.e3_id, &request.request) {
                debug!(e3_id = %request.e3_id, "dropping compute effect made obsolete by lifecycle stage");
                return false;
            }
            let key = (
                request.e3_id.clone(),
                Self::request_identity(&request.request),
            );
            let correlation_id = request.correlation_id;
            self.request_keys_by_correlation
                .insert(correlation_id, key.clone());
            if let Some(outcome) = self.replayed_responses.get(&key) {
                self.publish_outcome(outcome, correlation_id, &event);
                debug!(
                    e3_id = %key.0,
                    "reused a durable compute response instead of repeating completed work"
                );
                return false;
            }

            let now = now_unix_secs();
            let existing = self.forwarded.get(&key).map(|forwarded| {
                (
                    forwarded.correlation_id == correlation_id,
                    forwarded.outcome.clone(),
                    forwarded.sent_at,
                    forwarded.waiting.contains(&correlation_id),
                )
            });
            match existing {
                Some((true, ..)) => {
                    debug!("dropping duplicate compute effect with the same correlation ID");
                    return false;
                }
                Some((_, Some(outcome), ..)) => {
                    self.publish_outcome(&outcome, correlation_id, &event);
                    return false;
                }
                Some((_, None, sent_at, already_waiting)) => {
                    if now.saturating_sub(sent_at) > self.stale_after_secs {
                        // The worker finished but its outcome never arrived, so
                        // parked retries cannot recover. Evict the entry and
                        // forward this request again, keeping the parked
                        // waiters so the retry outcome still fans out to them.
                        debug!("evicting a stale forwarded compute effect without an outcome");
                        let mut entry = self.forwarded.remove(&key).expect("entry exists");
                        entry.correlation_id = correlation_id;
                        entry.sent_at = now;
                        self.forwarded.insert(key, entry);
                    } else {
                        if !already_waiting {
                            if let Some(forwarded) = self.forwarded.get_mut(&key) {
                                forwarded.waiting.push(correlation_id);
                            }
                        }
                        return false;
                    }
                }
                None => {
                    self.forwarded.insert(
                        key,
                        ForwardedRequest {
                            correlation_id,
                            waiting: Vec::new(),
                            outcome: None,
                            sent_at: now,
                        },
                    );
                }
            }
        }
        self.target.do_send(event);
        true
    }

    fn on_outcome(&mut self, event: &InterfoldEvent) {
        let (correlation_id, outcome) = match event.get_data() {
            InterfoldEventData::ComputeResponse(response) => (
                response.correlation_id,
                ComputeOutcome::Response(response.clone()),
            ),
            InterfoldEventData::ComputeRequestError(error) => (
                *error.correlation_id(),
                ComputeOutcome::Error(error.clone()),
            ),
            _ => return,
        };
        let key = self
            .request_keys_by_correlation
            .get(&correlation_id)
            .cloned();
        let forwarded_key = key.as_ref().filter(|key| {
            self.forwarded
                .get(*key)
                .is_some_and(|forwarded| forwarded.correlation_id == correlation_id)
        });
        let Some(forwarded_key) = forwarded_key else {
            // During EventStore replay, a successful response can arrive before effects are
            // enabled. Keep it by semantic request so a freshly hydrated actor receives the same
            // value under its new correlation ID. Do not cache errors: an old OOM or process
            // failure must not suppress a fresh recovery attempt.
            if matches!(outcome, ComputeOutcome::Response(_)) {
                if let Some(key) = key {
                    self.replayed_responses.insert(key, outcome);
                }
            }
            return;
        };
        let forwarded = self
            .forwarded
            .get_mut(forwarded_key)
            .expect("forwarded key was checked above");
        forwarded.outcome = Some(outcome.clone());
        let waiting = std::mem::take(&mut forwarded.waiting);
        for waiting_id in waiting {
            self.publish_outcome(&outcome, waiting_id, event);
        }
    }

    fn publish_outcome(
        &self,
        outcome: &ComputeOutcome,
        correlation_id: CorrelationId,
        cause: &InterfoldEvent,
    ) {
        let Some(bus) = &self.bus else {
            return;
        };
        let result = match outcome {
            ComputeOutcome::Response(response) => bus.publish(
                ComputeResponse::new(
                    response.response.clone(),
                    correlation_id,
                    response.e3_id.clone(),
                ),
                cause.get_ctx().clone(),
            ),
            ComputeOutcome::Error(error) => {
                let mut request = error.request().clone();
                request.correlation_id = correlation_id;
                bus.publish(
                    ComputeRequestError::new(error.get_err().clone(), request),
                    cause.get_ctx().clone(),
                )
            }
        };
        if let Err(error) = result {
            tracing::error!("failed to send compute outcome to a retried request: {error}");
        }
    }

    pub(crate) fn attach(
        bus: &BusHandle,
        target: Recipient<InterfoldEvent>,
        initial_stages: HashMap<E3id, E3Stage>,
    ) {
        let gate = Self::new(target, initial_stages)
            .with_bus(bus.clone())
            .start();
        bus.subscribe_all(
            &[
                EventType::ComputeRequest,
                EventType::ComputeResponse,
                EventType::ComputeRequestError,
                EventType::EffectsEnabled,
                EventType::E3RequestComplete,
                EventType::E3Failed,
                EventType::E3StageChanged,
            ],
            gate.recipient(),
        );
    }

    fn queue(&mut self, event: InterfoldEvent) {
        let InterfoldEventData::ComputeRequest(request) = event.get_data() else {
            return;
        };

        let key = (
            request.e3_id.clone(),
            Self::request_identity(&request.request),
        );
        self.request_keys_by_correlation
            .insert(request.correlation_id, key.clone());
        match self.pending.entry(key) {
            std::collections::hash_map::Entry::Occupied(mut entry)
                if event.ts() > entry.get().ts() =>
            {
                entry.insert(event);
            }
            std::collections::hash_map::Entry::Vacant(entry) => {
                entry.insert(event);
            }
            _ => {}
        }
    }

    fn enable(&mut self) {
        self.enabled = true;
        let mut pending: Vec<_> = self.pending.drain().map(|(_, event)| event).collect();
        pending.sort_by_key(EventContextAccessors::ts);
        let count = pending.len();
        for event in pending {
            self.forward(event);
        }
        info!(count, "released replay-safe compute effects");
    }

    fn cancel(&mut self, e3_id: &E3id) {
        self.pending
            .retain(|(pending_id, _), _| pending_id != e3_id);
        self.forwarded
            .retain(|(forwarded_id, _), _| forwarded_id != e3_id);
        self.replayed_responses
            .retain(|(response_id, _), _| response_id != e3_id);
        self.request_keys_by_correlation
            .retain(|_, (request_id, _)| request_id != e3_id);
    }
}

impl Actor for ComputeEffectGate {
    type Context = Context<Self>;

    fn started(&mut self, ctx: &mut Self::Context) {
        ctx.set_mailbox_capacity(MAILBOX_LIMIT);
    }
}

impl Handler<InterfoldEvent> for ComputeEffectGate {
    type Result = ();

    fn handle(&mut self, event: InterfoldEvent, _: &mut Self::Context) {
        match event.get_data() {
            InterfoldEventData::ComputeRequest(_) if self.enabled => {
                self.forward(event);
            }
            InterfoldEventData::ComputeRequest(_) => self.queue(event),
            InterfoldEventData::ComputeResponse(_) | InterfoldEventData::ComputeRequestError(_) => {
                self.on_outcome(&event);
            }
            InterfoldEventData::EffectsEnabled(_) => self.enable(),
            InterfoldEventData::E3RequestComplete(complete) => {
                self.record_stage(complete.e3_id.clone(), E3Stage::Complete);
                self.cancel(&complete.e3_id);
            }
            InterfoldEventData::E3Failed(failed) => {
                self.record_stage(failed.e3_id.clone(), E3Stage::Failed);
                self.cancel(&failed.e3_id);
            }
            InterfoldEventData::E3StageChanged(stage) => {
                self.record_stage(stage.e3_id.clone(), stage.new_stage.clone());
                if matches!(stage.new_stage, E3Stage::Complete | E3Stage::Failed) {
                    self.cancel(&stage.e3_id);
                }
            }
            _ => {}
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use actix::{Addr, Message, ResponseFuture};
    use e3_crypto::SensitiveBytes;
    use e3_events::{
        hlc_factory::HlcFactory, CircuitName, ComputeRequest, ComputeRequestErrorKind,
        ComputeResponseKind, CorrelationId, E3RequestComplete, EffectsEnabled, EventBus,
        EventBusConfig, EventConstructorWithTimestamp, EventSource, HistoryCollector,
        InterfoldEvent, LbfvPkAggregationProofRequest, LbfvPkGenerationProofRequest,
        PartyProofsToVerify, PkBfvProofRequest, Proof, ProofPayload, RlkAggregationProofRequest,
        RlkGenerationProofRequest, Sequencer, SignedProofPayload, StoreEventRequested,
        StoreEventResponse, TakeEvents, Unsequenced, VerifyShareProofsRequest, ZkError, ZkRequest,
        ZkResponse,
    };
    use e3_fhe_params::BfvPreset;
    use e3_trbfv::lbfv_operation::LbfvOperationId;
    use e3_utils::ArcBytes;
    use e3_zk_helpers::CiphernodesCommitteeSize;

    fn proof_domain() -> e3_committee_hash::LbfvProofDomainContext {
        e3_zk_helpers::threshold::lbfv_proof_domain::sample_lbfv_proof_domain()
    }

    #[derive(Message)]
    #[rtype(result = "Vec<CorrelationId>")]
    struct Received;

    #[derive(Default)]
    struct Recorder(Vec<CorrelationId>);

    impl Actor for Recorder {
        type Context = Context<Self>;
    }

    impl Handler<InterfoldEvent> for Recorder {
        type Result = ();

        fn handle(&mut self, event: InterfoldEvent, _: &mut Self::Context) {
            if let InterfoldEventData::ComputeRequest(request) = event.get_data() {
                self.0.push(request.correlation_id);
            }
        }
    }

    impl Handler<Received> for Recorder {
        type Result = ResponseFuture<Vec<CorrelationId>>;

        fn handle(&mut self, _: Received, _: &mut Self::Context) -> Self::Result {
            let received = self.0.clone();
            Box::pin(async move { received })
        }
    }

    #[derive(Default)]
    struct TestEventStore {
        next_seq: u64,
    }

    impl Actor for TestEventStore {
        type Context = Context<Self>;
    }

    impl Handler<StoreEventRequested> for TestEventStore {
        type Result = ();

        fn handle(&mut self, msg: StoreEventRequested, _: &mut Self::Context) {
            let StoreEventRequested { event, sender } = msg;
            let seq = self.next_seq;
            self.next_seq += 1;
            let _ = sender.try_send(StoreEventResponse(event.into_sequenced(seq)));
        }
    }

    fn test_bus() -> (BusHandle, Addr<HistoryCollector<InterfoldEvent>>) {
        let event_bus =
            EventBus::<InterfoldEvent>::new(EventBusConfig { deduplicate: true }).start();
        let store = TestEventStore::default().start();
        let sequencer = Sequencer::new(&event_bus, store.recipient()).start();
        let bus = BusHandle::new(event_bus, sequencer, HlcFactory::new()).enable("test-gate");
        let history = bus.history();
        (bus, history)
    }

    fn outcome_event(data: impl Into<InterfoldEventData>) -> InterfoldEvent {
        InterfoldEvent::<Unsequenced>::new_with_timestamp(
            data.into(),
            None,
            50,
            None,
            EventSource::Local,
        )
        .into_sequenced(4)
    }

    async fn next_outcome(history: &Addr<HistoryCollector<InterfoldEvent>>) -> InterfoldEvent {
        let mut result = history
            .send(TakeEvents::<InterfoldEvent>::new(1))
            .await
            .unwrap();
        assert!(!result.timed_out, "expected a mirrored compute outcome");
        result.events.pop().unwrap()
    }

    fn response(correlation_id: CorrelationId) -> ComputeResponse {
        ComputeResponse::new(
            ComputeResponseKind::Zk(ZkResponse::PkBfv(e3_events::PkBfvProofResponse::new(
                Proof::new(
                    CircuitName::PkBfv,
                    ArcBytes::from_bytes(&[1]),
                    ArcBytes::from_bytes(&[2]),
                ),
            ))),
            correlation_id,
            E3id::new("4", 1),
        )
    }

    fn failure(correlation_id: CorrelationId) -> ComputeRequestError {
        let InterfoldEventData::ComputeRequest(request) = compute(correlation_id, 10).into_data()
        else {
            unreachable!();
        };
        ComputeRequestError::new(
            ComputeRequestErrorKind::Zk(ZkError::ProofGenerationFailed("failed".into())),
            request,
        )
    }

    fn compute(correlation_id: CorrelationId, timestamp: u128) -> InterfoldEvent {
        let request = ComputeRequest::zk(
            ZkRequest::PkBfv(PkBfvProofRequest::new(
                ArcBytes::from_bytes(&[]),
                BfvPreset::default(),
                CiphernodesCommitteeSize::Micro,
            )),
            correlation_id,
            E3id::new("4", 1),
        );
        InterfoldEvent::<Unsequenced>::new_with_timestamp(
            request.into(),
            None,
            timestamp,
            None,
            EventSource::Local,
        )
        .into_sequenced(1)
    }

    fn lbfv_compute(
        correlation_id: CorrelationId,
        timestamp: u128,
        artifact: &[u8],
    ) -> InterfoldEvent {
        let mut proof_request = LbfvPkGenerationProofRequest {
            operation_id: LbfvOperationId([0; 32]),
            proof_domain: proof_domain(),
            party_id: 0,
            public_key_share_bytes: ArcBytes::from_bytes(artifact),
            secret_key_bytes: SensitiveBytes::from_encrypted(&[]),
            row_index: 0,
            params_preset: BfvPreset::SecureThreshold16384,
            committee_size: CiphernodesCommitteeSize::Minimum,
        };
        proof_request.operation_id = proof_request.expected_operation_id();
        let request = ComputeRequest::zk(
            ZkRequest::LbfvPkGeneration(proof_request),
            correlation_id,
            E3id::new("4", 1),
        );
        InterfoldEvent::<Unsequenced>::new_with_timestamp(
            request.into(),
            None,
            timestamp,
            None,
            EventSource::Local,
        )
        .into_sequenced(1)
    }

    fn share_verification_compute(
        correlation_id: CorrelationId,
        timestamp: u128,
        proof_type: ProofType,
        circuit: CircuitName,
    ) -> InterfoldEvent {
        let proof = SignedProofPayload {
            payload: ProofPayload {
                e3_id: E3id::new("4", 1),
                proof_type,
                proof: Proof::new(
                    circuit,
                    ArcBytes::from_bytes(&[1]),
                    ArcBytes::from_bytes(&[2]),
                ),
            },
            signature: ArcBytes::from_bytes(&[3]),
        };
        let request = ComputeRequest::zk(
            ZkRequest::VerifyShareProofs(VerifyShareProofsRequest {
                party_proofs: vec![PartyProofsToVerify {
                    sender_party_id: 0,
                    signed_proofs: vec![proof],
                }],
                params_preset: BfvPreset::default(),
                committee_size: CiphernodesCommitteeSize::Micro,
            }),
            correlation_id,
            E3id::new("4", 1),
        );
        InterfoldEvent::<Unsequenced>::new_with_timestamp(
            request.into(),
            None,
            timestamp,
            None,
            EventSource::Local,
        )
        .into_sequenced(1)
    }

    fn effects_enabled() -> InterfoldEvent {
        InterfoldEvent::<Unsequenced>::new_with_timestamp(
            EffectsEnabled::new().into(),
            None,
            30,
            None,
            EventSource::Local,
        )
        .into_sequenced(2)
    }

    fn completed() -> InterfoldEvent {
        InterfoldEvent::<Unsequenced>::new_with_timestamp(
            E3RequestComplete {
                e3_id: E3id::new("4", 1),
            }
            .into(),
            None,
            25,
            None,
            EventSource::Local,
        )
        .into_sequenced(2)
    }

    #[test]
    fn classifies_all_lbfv_row_requests_as_dkg_work() {
        let preset = BfvPreset::SecureThreshold16384;
        let committee_size = CiphernodesCommitteeSize::Minimum;
        let bytes = || ArcBytes::from_bytes(&[]);
        let sensitive = || SensitiveBytes::from_encrypted(&[]);
        let requests = [
            ZkRequest::LbfvPkGeneration(LbfvPkGenerationProofRequest {
                operation_id: LbfvOperationId([1; 32]),
                proof_domain: proof_domain(),
                party_id: 0,
                public_key_share_bytes: bytes(),
                secret_key_bytes: sensitive(),
                row_index: 0,
                params_preset: preset,
                committee_size,
            }),
            ZkRequest::RlkGeneration(RlkGenerationProofRequest {
                operation_id: LbfvOperationId([2; 32]),
                proof_domain: proof_domain(),
                party_id: 0,
                rlk_share_bytes: bytes(),
                secret_key_bytes: sensitive(),
                r_bytes: sensitive(),
                errors_d0_bytes: Vec::new(),
                errors_d2_bytes: Vec::new(),
                row_index: 0,
                params_preset: preset,
                committee_size,
            }),
            ZkRequest::LbfvPkAggregation(LbfvPkAggregationProofRequest {
                operation_id: LbfvOperationId([3; 32]),
                proof_domain: proof_domain(),
                aggregator_party_id: 0,
                party_ids: Vec::new(),
                share_bytes: Vec::new(),
                row_index: 0,
                params_preset: preset,
                committee_size,
            }),
            ZkRequest::RlkAggregation(RlkAggregationProofRequest {
                operation_id: LbfvOperationId([4; 32]),
                proof_domain: proof_domain(),
                aggregator_party_id: 0,
                party_ids: Vec::new(),
                share_bytes: Vec::new(),
                row_index: 0,
                params_preset: preset,
                committee_size,
            }),
        ];

        assert!(requests.into_iter().all(|request| {
            ComputeEffectGate::is_dkg_request(&ComputeRequestKind::Zk(request))
        }));

        assert!(ComputeEffectGate::is_dkg_request(
            &ComputeRequestKind::TrBFV(e3_trbfv::TrBFVRequest::GenLbfvKeyShares(
                e3_trbfv::gen_lbfv_key_shares::GenLbfvKeySharesRequest {
                    operation_id: LbfvOperationId([0; 32]),
                    session_id: [1; 32],
                    party_id: 0,
                    secret_key_bytes: sensitive(),
                    generation_seed: sensitive(),
                    params_preset: preset,
                    ciphertext_level: 0,
                    key_level: 0,
                }
            ))
        ));
    }

    #[actix::test]
    async fn buffers_until_enabled_and_keeps_newest_semantic_retry() {
        let recorder = Recorder::default().start();
        let gate = ComputeEffectGate::new(recorder.clone().recipient(), HashMap::new()).start();
        let stale = CorrelationId::new();
        let regenerated = CorrelationId::new();

        gate.send(compute(stale, 10)).await.unwrap();
        gate.send(compute(regenerated, 20)).await.unwrap();
        assert!(recorder.send(Received).await.unwrap().is_empty());

        gate.send(effects_enabled()).await.unwrap();
        assert_eq!(recorder.send(Received).await.unwrap(), vec![regenerated]);
    }

    #[actix::test]
    async fn replayed_success_satisfies_regenerated_request_without_recomputing() {
        let (bus, history) = test_bus();
        let recorder = Recorder::default().start();
        let gate = ComputeEffectGate::new(recorder.clone().recipient(), HashMap::new())
            .with_bus(bus)
            .start();
        let durable = CorrelationId::new();
        let regenerated = CorrelationId::new();

        gate.send(compute(durable, 10)).await.unwrap();
        gate.send(outcome_event(response(durable))).await.unwrap();
        gate.send(compute(regenerated, 20)).await.unwrap();
        gate.send(effects_enabled()).await.unwrap();

        assert!(recorder.send(Received).await.unwrap().is_empty());
        assert!(matches!(
            next_outcome(&history).await.into_data(),
            InterfoldEventData::ComputeResponse(result)
                if result.correlation_id == regenerated
        ));
    }

    #[actix::test]
    async fn replayed_success_survives_actor_redrive_interleaving() {
        let (bus, history) = test_bus();
        let recorder = Recorder::default().start();
        let gate = ComputeEffectGate::new(recorder.clone().recipient(), HashMap::new())
            .with_bus(bus)
            .start();
        let durable = CorrelationId::new();
        let regenerated = CorrelationId::new();

        // A hydrated actor can redrive work while historical events are still reaching other
        // subscribers. The newer request must remain selected even if its historical request and
        // successful response arrive afterward.
        gate.send(compute(regenerated, 20)).await.unwrap();
        gate.send(compute(durable, 10)).await.unwrap();
        gate.send(outcome_event(response(durable))).await.unwrap();
        gate.send(effects_enabled()).await.unwrap();

        assert!(recorder.send(Received).await.unwrap().is_empty());
        assert!(matches!(
            next_outcome(&history).await.into_data(),
            InterfoldEventData::ComputeResponse(result)
                if result.correlation_id == regenerated
        ));
    }

    #[actix::test]
    async fn replayed_failure_does_not_suppress_a_recovery_attempt() {
        let recorder = Recorder::default().start();
        let gate = ComputeEffectGate::new(recorder.clone().recipient(), HashMap::new()).start();
        let failed = CorrelationId::new();
        let regenerated = CorrelationId::new();

        gate.send(compute(failed, 10)).await.unwrap();
        gate.send(outcome_event(failure(failed))).await.unwrap();
        gate.send(compute(regenerated, 20)).await.unwrap();
        gate.send(effects_enabled()).await.unwrap();

        assert_eq!(recorder.send(Received).await.unwrap(), vec![regenerated]);
    }

    #[actix::test]
    async fn terminal_e3_cancels_buffered_effects() {
        let recorder = Recorder::default().start();
        let gate = ComputeEffectGate::new(recorder.clone().recipient(), HashMap::new()).start();

        gate.send(compute(CorrelationId::new(), 10)).await.unwrap();
        gate.send(completed()).await.unwrap();
        gate.send(effects_enabled()).await.unwrap();

        assert!(recorder.send(Received).await.unwrap().is_empty());
    }

    #[actix::test]
    async fn drops_redriven_duplicate_after_enable() {
        let recorder = Recorder::default().start();
        let gate = ComputeEffectGate::new(recorder.clone().recipient(), HashMap::new()).start();
        let buffered = CorrelationId::new();
        let redriven = CorrelationId::new();

        // Released from the replay buffer on enable.
        gate.send(compute(buffered, 10)).await.unwrap();
        gate.send(effects_enabled()).await.unwrap();
        assert_eq!(recorder.send(Received).await.unwrap(), vec![buffered]);

        // Same (e3_id, kind) re-driven by a hydrated actor after EffectsEnabled
        // is suppressed — only one compute reaches the target.
        gate.send(compute(redriven, 40)).await.unwrap();
        assert_eq!(recorder.send(Received).await.unwrap(), vec![buffered]);
    }

    fn request_key(event: &InterfoldEvent) -> RequestKey {
        let InterfoldEventData::ComputeRequest(request) = event.get_data() else {
            unreachable!("expected a compute request event");
        };
        (
            request.e3_id.clone(),
            ComputeEffectGate::request_identity(&request.request),
        )
    }

    #[actix::test]
    async fn stale_outcome_less_entry_is_evicted_and_run_again() {
        let recorder = Recorder::default().start();
        let mut gate = ComputeEffectGate::new(recorder.clone().recipient(), HashMap::new());
        let first = CorrelationId::new();
        let parked = CorrelationId::new();
        let retry = CorrelationId::new();

        let event = compute(first, 10);
        let key = request_key(&event);
        assert!(gate.forward(event));
        assert_eq!(recorder.send(Received).await.unwrap(), vec![first]);

        // Same payload, fresh entry: parked while the first outcome is pending.
        assert!(!gate.forward(compute(parked, 11)));
        assert_eq!(recorder.send(Received).await.unwrap(), vec![first]);

        // The first outcome never arrives. After the stale threshold the retry
        // must run again instead of parking forever.
        let aged = now_unix_secs().saturating_sub(gate.stale_after_secs + 1);
        gate.forwarded.get_mut(&key).unwrap().sent_at = aged;
        assert!(gate.forward(compute(retry, 12)));
        assert_eq!(recorder.send(Received).await.unwrap(), vec![first, retry]);
    }

    #[actix::test]
    async fn evicted_entry_keeps_parked_waiters_for_the_retry_outcome() {
        let recorder = Recorder::default().start();
        let (bus, history) = test_bus();
        let mut gate =
            ComputeEffectGate::new(recorder.clone().recipient(), HashMap::new()).with_bus(bus);
        let first = CorrelationId::new();
        let parked = CorrelationId::new();
        let retry = CorrelationId::new();

        let event = compute(first, 10);
        let key = request_key(&event);
        assert!(gate.forward(event));
        assert!(!gate.forward(compute(parked, 11)));
        gate.forwarded.get_mut(&key).unwrap().sent_at = 0;
        assert!(gate.forward(compute(retry, 12)));
        gate.on_outcome(&outcome_event(response(retry)));

        // The waiter parked behind the evicted entry receives the retry
        // outcome under its own correlation ID.
        assert!(matches!(
            next_outcome(&history).await.into_data(),
            InterfoldEventData::ComputeResponse(result) if result.correlation_id == parked
        ));
        assert_eq!(recorder.send(Received).await.unwrap(), vec![first, retry]);
    }

    #[actix::test]
    async fn forwarded_entry_with_outcome_is_never_evicted() {
        let recorder = Recorder::default().start();
        let mut gate = ComputeEffectGate::new(recorder.clone().recipient(), HashMap::new());
        let first = CorrelationId::new();
        let retry = CorrelationId::new();

        let event = compute(first, 10);
        let key = request_key(&event);
        assert!(gate.forward(event));
        gate.on_outcome(&outcome_event(response(first)));

        // An aged entry with an outcome still answers the retry from the
        // outcome instead of running the compute again.
        gate.forwarded.get_mut(&key).unwrap().sent_at = 0;
        assert!(!gate.forward(compute(retry, 11)));
        assert_eq!(recorder.send(Received).await.unwrap(), vec![first]);
        assert!(gate.forwarded.get(&key).unwrap().outcome.is_some());
    }

    #[actix::test]
    async fn lbfv_effects_deduplicate_by_operation_id() {
        let recorder = Recorder::default().start();
        let gate = ComputeEffectGate::new(recorder.clone().recipient(), HashMap::new()).start();
        let first = CorrelationId::new();
        let retry = CorrelationId::new();
        let distinct = CorrelationId::new();

        gate.send(effects_enabled()).await.unwrap();
        gate.send(lbfv_compute(first, 40, &[1])).await.unwrap();
        gate.send(lbfv_compute(retry, 41, &[1])).await.unwrap();
        gate.send(lbfv_compute(distinct, 42, &[2])).await.unwrap();

        assert_eq!(
            recorder.send(Received).await.unwrap(),
            vec![first, distinct]
        );
    }

    #[actix::test]
    async fn redriven_request_receives_success_under_its_own_id() {
        let (bus, history) = test_bus();
        let recorder = Recorder::default().start();
        let gate = ComputeEffectGate::new(recorder.clone().recipient(), HashMap::new())
            .with_bus(bus)
            .start();
        let old = CorrelationId::new();
        let current = CorrelationId::new();

        gate.send(compute(old, 10)).await.unwrap();
        gate.send(effects_enabled()).await.unwrap();
        gate.send(compute(current, 40)).await.unwrap();
        assert_eq!(recorder.send(Received).await.unwrap(), vec![old]);
        gate.send(outcome_event(response(old))).await.unwrap();

        assert!(matches!(
            next_outcome(&history).await.into_data(),
            InterfoldEventData::ComputeResponse(result) if result.correlation_id == current
        ));
    }

    #[actix::test]
    async fn redriven_request_receives_failure_under_its_own_id() {
        let (bus, history) = test_bus();
        let recorder = Recorder::default().start();
        let gate = ComputeEffectGate::new(recorder.clone().recipient(), HashMap::new())
            .with_bus(bus)
            .start();
        let old = CorrelationId::new();
        let current = CorrelationId::new();

        gate.send(compute(old, 10)).await.unwrap();
        gate.send(effects_enabled()).await.unwrap();
        gate.send(compute(current, 40)).await.unwrap();
        assert_eq!(recorder.send(Received).await.unwrap(), vec![old]);
        gate.send(outcome_event(failure(old))).await.unwrap();

        let InterfoldEventData::ComputeRequestError(result) =
            next_outcome(&history).await.into_data()
        else {
            panic!("expected a compute error");
        };
        assert_eq!(result.correlation_id(), &current);
        assert_eq!(result.request().request, failure(old).request().request);
    }

    #[actix::test]
    async fn late_redriven_request_receives_cached_outcome() {
        let (bus, history) = test_bus();
        let recorder = Recorder::default().start();
        let gate = ComputeEffectGate::new(recorder.clone().recipient(), HashMap::new())
            .with_bus(bus)
            .start();
        let old = CorrelationId::new();
        let current = CorrelationId::new();

        gate.send(compute(old, 10)).await.unwrap();
        gate.send(effects_enabled()).await.unwrap();
        gate.send(outcome_event(response(old))).await.unwrap();
        gate.send(compute(current, 40)).await.unwrap();
        assert_eq!(recorder.send(Received).await.unwrap(), vec![old]);

        assert!(matches!(
            next_outcome(&history).await.into_data(),
            InterfoldEventData::ComputeResponse(result) if result.correlation_id == current
        ));
    }

    #[actix::test]
    async fn key_published_snapshot_discards_obsolete_dkg_work() {
        let recorder = Recorder::default().start();
        let stages = HashMap::from([(E3id::new("4", 1), E3Stage::KeyPublished)]);
        let gate = ComputeEffectGate::new(recorder.clone().recipient(), stages).start();

        gate.send(compute(CorrelationId::new(), 10)).await.unwrap();
        gate.send(effects_enabled()).await.unwrap();
        gate.send(compute(CorrelationId::new(), 40)).await.unwrap();

        assert!(recorder.send(Received).await.unwrap().is_empty());
    }

    #[actix::test]
    async fn key_published_snapshot_keeps_threshold_decryption_verification() {
        let recorder = Recorder::default().start();
        let stages = HashMap::from([(E3id::new("4", 1), E3Stage::CiphertextReady)]);
        let gate = ComputeEffectGate::new(recorder.clone().recipient(), stages).start();
        let dkg_correlation_id = CorrelationId::new();
        let correlation_id = CorrelationId::new();

        gate.send(share_verification_compute(
            dkg_correlation_id,
            5,
            ProofType::C1PkGeneration,
            CircuitName::PkGeneration,
        ))
        .await
        .unwrap();
        gate.send(share_verification_compute(
            correlation_id,
            10,
            ProofType::C6ThresholdShareDecryption,
            CircuitName::ThresholdShareDecryption,
        ))
        .await
        .unwrap();
        gate.send(effects_enabled()).await.unwrap();

        assert_eq!(recorder.send(Received).await.unwrap(), vec![correlation_id]);
    }
}
