// SPDX-License-Identifier: LGPL-3.0-only
//
// This file is provided WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE.

//! Replay-safe gate for value-bearing compute effects.

use actix::{Actor, Context, Handler, Recipient};
use e3_events::{
    BusHandle, ComputeRequestError, ComputeRequestKind, ComputeResponse, CorrelationId, E3Stage,
    E3id, Event, EventContextAccessors, EventPublisher, EventSubscriber, EventType, InterfoldEvent,
    InterfoldEventData, ProofType, VerifyShareProofsRequest, ZkRequest,
};
use e3_utils::MAILBOX_LIMIT;
use std::collections::HashMap;
use std::sync::{Arc, Mutex, MutexGuard, PoisonError};
use std::time::{Duration, Instant};
use tracing::{debug, info};

type RequestKey = (E3id, ComputeRequestKind);

#[derive(Clone)]
#[allow(clippy::large_enum_variant)]
enum ComputeOutcome {
    Response(ComputeResponse),
    Error(ComputeRequestError),
}

struct ForwardedRequest {
    /// IDs under which the request went to the worker, the first one first.
    correlation_ids: Vec<CorrelationId>,
    forwarded_at: Instant,
    waiting: Vec<CorrelationId>,
    outcome: Option<ComputeOutcome>,
}

/// A request that comes again under a new ID this long after it went to the worker, with no
/// result in the gate and no run of it left in the worker, goes to the worker again. EventBus
/// fan-out can drop the result on its way to the gate, and the gate would otherwise keep every
/// later ID waiting for good.
const REFORWARD_AFTER: Duration = Duration::from_secs(10 * 60);

/// The compute requests that the worker runs, queued ones included, by correlation ID with the
/// number of runs: IDs restart from 1 in each process, so a replayed request can share its ID with
/// a new one. The gate sends a request to the worker again only when no earlier run of it is left,
/// so a slow proof under load runs once instead of once per retry.
#[derive(Clone, Default)]
pub(crate) struct RunningJobs(Arc<Mutex<HashMap<CorrelationId, usize>>>);

impl RunningJobs {
    /// Note that the worker runs `id` until the returned guard drops.
    pub(crate) fn start(&self, id: CorrelationId) -> RunningJob {
        *self.lock().entry(id).or_default() += 1;
        RunningJob {
            jobs: self.clone(),
            id,
        }
    }

    pub(crate) fn any(&self, ids: &[CorrelationId]) -> bool {
        let running = self.lock();
        ids.iter().any(|id| running.contains_key(id))
    }

    fn lock(&self) -> MutexGuard<'_, HashMap<CorrelationId, usize>> {
        self.0.lock().unwrap_or_else(PoisonError::into_inner)
    }
}

/// A compute request that the worker runs. Dropping it ends the run.
pub(crate) struct RunningJob {
    jobs: RunningJobs,
    id: CorrelationId,
}

impl Drop for RunningJob {
    fn drop(&mut self) {
        let mut running = self.jobs.lock();
        if let Some(runs) = running.get_mut(&self.id) {
            *runs -= 1;
            if *runs == 0 {
                running.remove(&self.id);
            }
        }
    }
}

/// Buffers compute effects observed during EventStore replay. Identical
/// semantic requests are deduplicated independently of their correlation ID;
/// the newest HLC context wins so a request regenerated by a hydrated actor is
/// preferred over its stale pre-crash copy.
///
/// Deduplication spans the replay-to-live boundary. A later request with the
/// same payload does not repeat the compute. A successful response found during
/// replay satisfies a regenerated request, while a replayed error leaves that
/// request eligible for recovery. The gate sends the result to each requester's
/// correlation ID, including IDs created after restart. Terminal events clear
/// the per-E3 keys.
pub(crate) struct ComputeEffectGate {
    target: Recipient<InterfoldEvent>,
    bus: Option<BusHandle>,
    enabled: bool,
    pending: HashMap<RequestKey, InterfoldEvent>,
    forwarded: HashMap<RequestKey, ForwardedRequest>,
    request_keys_by_correlation: HashMap<CorrelationId, RequestKey>,
    replayed_responses: HashMap<RequestKey, ComputeOutcome>,
    stages: HashMap<E3id, E3Stage>,
    canonical_keys: e3_request::canonical_key::CanonicalPublicKeys,
    running: RunningJobs,
    reforward_after: Duration,
}

impl ComputeEffectGate {
    fn new(target: Recipient<InterfoldEvent>, initial_stages: HashMap<E3id, E3Stage>) -> Self {
        Self {
            target,
            bus: None,
            enabled: false,
            pending: HashMap::new(),
            forwarded: HashMap::new(),
            request_keys_by_correlation: HashMap::new(),
            replayed_responses: HashMap::new(),
            stages: initial_stages,
            canonical_keys: Default::default(),
            running: RunningJobs::default(),
            reforward_after: REFORWARD_AFTER,
        }
    }

    fn with_bus(mut self, bus: BusHandle) -> Self {
        self.bus = Some(bus);
        self
    }

    fn stage_rank(stage: &E3Stage) -> u8 {
        match stage {
            E3Stage::None => 0,
            E3Stage::Requested => 1,
            E3Stage::CommitteeFinalized => 2,
            E3Stage::KeyPublished => 3,
            E3Stage::CiphertextReady => 4,
            E3Stage::Complete => 5,
            E3Stage::Failed => 6,
        }
    }

    fn is_dkg_request(kind: &ComputeRequestKind) -> bool {
        match kind {
            ComputeRequestKind::TrBFV(request) => matches!(
                request,
                e3_trbfv::TrBFVRequest::GenEsiSss(_)
                    | e3_trbfv::TrBFVRequest::GenPkShareAndSkSss(_)
                    | e3_trbfv::TrBFVRequest::CalculateDecryptionKey(_)
            ),
            ComputeRequestKind::Zk(request) => {
                matches!(
                    request,
                    ZkRequest::PkBfv(_)
                        | ZkRequest::PkGeneration(_)
                        | ZkRequest::ShareComputation(_)
                        | ZkRequest::ShareEncryption(_)
                        | ZkRequest::DkgShareDecryption(_)
                        | ZkRequest::VerifyShareDecryptionProofs(_)
                        | ZkRequest::PkAggregation(_)
                        | ZkRequest::NodeDkgFold(_)
                        | ZkRequest::NodesFoldStep(_)
                        | ZkRequest::DkgAggregation(_)
                ) || matches!(
                    request,
                    ZkRequest::VerifyShareProofs(request)
                        if !Self::is_threshold_decryption_verification(request)
                )
            }
        }
    }

    /// `VerifyShareProofs` carries both DKG proofs (C1-C3) and final
    /// threshold-decryption proofs (C6). Inspect the signed proof type so a
    /// lifecycle filter cannot discard valid C6 work after key publication.
    fn is_threshold_decryption_verification(request: &VerifyShareProofsRequest) -> bool {
        let mut proofs = request
            .party_proofs
            .iter()
            .flat_map(|party| party.signed_proofs.iter());
        let Some(first) = proofs.next() else {
            return false;
        };

        first.payload.proof_type == ProofType::C6ThresholdShareDecryption
            && proofs.all(|proof| proof.payload.proof_type == ProofType::C6ThresholdShareDecryption)
    }

    fn request_is_obsolete(&self, e3_id: &E3id, kind: &ComputeRequestKind) -> bool {
        Self::request_is_obsolete_at_stage(self.stages.get(e3_id), kind)
    }

    /// Accusation work of a failed E3 runs until the request completes, so that a node can still
    /// vote on an accusation whose proof it has not verified.
    fn is_accusation_request(kind: &ComputeRequestKind) -> bool {
        matches!(
            kind,
            ComputeRequestKind::Zk(ZkRequest::ReverifyAccusedProof(_))
        )
    }

    fn request_is_obsolete_at_stage(stage: Option<&E3Stage>, kind: &ComputeRequestKind) -> bool {
        match stage {
            Some(E3Stage::Failed) if Self::is_accusation_request(kind) => false,
            Some(E3Stage::Complete | E3Stage::Failed) => true,
            Some(stage) if Self::stage_rank(stage) >= Self::stage_rank(&E3Stage::KeyPublished) => {
                Self::is_dkg_request(kind)
            }
            _ => false,
        }
    }

    fn record_stage(&mut self, e3_id: E3id, new_stage: E3Stage) {
        // A complete request is final, also after a failure: its accusation work ended too.
        let should_advance = self
            .stages
            .get(&e3_id)
            .map(|current| {
                *current != E3Stage::Complete
                    && Self::stage_rank(&new_stage) > Self::stage_rank(current)
            })
            .unwrap_or(true);
        if should_advance {
            self.stages.insert(e3_id.clone(), new_stage);
        }

        let current_stage = self.stages.get(&e3_id).cloned();
        self.pending.retain(|(pending_id, kind), _| {
            pending_id != &e3_id
                || !Self::request_is_obsolete_at_stage(current_stage.as_ref(), kind)
        });
    }

    /// Extract the dedup key from a ComputeRequest event, if it is one.
    fn request_key(event: &InterfoldEvent) -> Option<RequestKey> {
        match event.get_data() {
            InterfoldEventData::ComputeRequest(request) => {
                Some((request.e3_id.clone(), request.request.clone()))
            }
            _ => None,
        }
    }

    /// Forward a compute once. Send its outcome to later request IDs.
    fn forward(&mut self, event: InterfoldEvent) -> bool {
        if let Some(key) = Self::request_key(&event) {
            if self.request_is_obsolete(&key.0, &key.1) {
                debug!(e3_id = %key.0, "dropping compute effect made obsolete by lifecycle stage");
                return false;
            }
            let InterfoldEventData::ComputeRequest(request) = event.get_data() else {
                return false;
            };
            if let ComputeRequestKind::Zk(ZkRequest::ThresholdShareDecryption(proof)) =
                &request.request
            {
                if !self.canonical_keys.accepts_request(&request.e3_id, proof) {
                    debug!(e3_id = %request.e3_id, "Discarding C6 compute work without canonical public inputs");
                    return false;
                }
            }
            let correlation_id = request.correlation_id;
            self.request_keys_by_correlation
                .insert(correlation_id, key.clone());
            if let Some(outcome) = self.replayed_responses.get(&key) {
                self.publish_outcome(outcome, correlation_id, &event);
                debug!(
                    e3_id = %key.0,
                    "reused a durable compute response instead of repeating completed work"
                );
                return false;
            }
            match self.forwarded.get_mut(&key) {
                Some(forwarded) if forwarded.correlation_ids.contains(&correlation_id) => {
                    debug!("dropping duplicate compute effect with the same correlation ID");
                    return false;
                }
                Some(forwarded) => {
                    if let Some(outcome) = forwarded.outcome.clone() {
                        self.publish_outcome(&outcome, correlation_id, &event);
                        return false;
                    }
                    if forwarded.forwarded_at.elapsed() < self.reforward_after
                        || self.running.any(&forwarded.correlation_ids)
                    {
                        if !forwarded.waiting.contains(&correlation_id) {
                            forwarded.waiting.push(correlation_id);
                        }
                        return false;
                    }
                    info!(
                        e3_id = %key.0,
                        "Sending a compute request to the worker again: its result has not reached the gate"
                    );
                    forwarded.correlation_ids.push(correlation_id);
                    forwarded.forwarded_at = Instant::now();
                }
                None => {
                    self.forwarded.insert(
                        key,
                        ForwardedRequest {
                            correlation_ids: vec![correlation_id],
                            forwarded_at: Instant::now(),
                            waiting: Vec::new(),
                            outcome: None,
                        },
                    );
                }
            }
        }
        self.target.do_send(event);
        true
    }

    fn on_outcome(&mut self, event: &InterfoldEvent) {
        let (correlation_id, outcome) = match event.get_data() {
            InterfoldEventData::ComputeResponse(response) => (
                response.correlation_id,
                ComputeOutcome::Response(response.clone()),
            ),
            InterfoldEventData::ComputeRequestError(error) => (
                *error.correlation_id(),
                ComputeOutcome::Error(error.clone()),
            ),
            _ => return,
        };
        let key = self
            .request_keys_by_correlation
            .get(&correlation_id)
            .cloned();
        let forwarded_key = key.as_ref().filter(|key| {
            self.forwarded
                .get(*key)
                .is_some_and(|forwarded| forwarded.correlation_ids.contains(&correlation_id))
        });
        let Some(forwarded_key) = forwarded_key else {
            // During EventStore replay, a successful response can arrive before effects are
            // enabled. Keep it by semantic request so a freshly hydrated actor receives the same
            // value under its new correlation ID. Do not cache errors: an old OOM or process
            // failure must not suppress a fresh recovery attempt.
            if matches!(outcome, ComputeOutcome::Response(_)) {
                if let Some(key) = key {
                    self.replayed_responses.insert(key, outcome);
                }
            }
            return;
        };
        let forwarded = self
            .forwarded
            .get_mut(forwarded_key)
            .expect("forwarded key was checked above");
        if matches!(forwarded.outcome, Some(ComputeOutcome::Response(_))) {
            // A request sent to the worker again can finish twice. Keep the first success.
            return;
        }
        forwarded.outcome = Some(outcome.clone());
        // The worker answers each ID it ran itself.
        let waiting = std::mem::take(&mut forwarded.waiting);
        for waiting_id in waiting {
            self.publish_outcome(&outcome, waiting_id, event);
        }
    }

    fn publish_outcome(
        &self,
        outcome: &ComputeOutcome,
        correlation_id: CorrelationId,
        cause: &InterfoldEvent,
    ) {
        let Some(bus) = &self.bus else {
            return;
        };
        let result = match outcome {
            ComputeOutcome::Response(response) => bus.publish(
                ComputeResponse::new(
                    response.response.clone(),
                    correlation_id,
                    response.e3_id.clone(),
                ),
                cause.get_ctx().clone(),
            ),
            ComputeOutcome::Error(error) => {
                let mut request = error.request().clone();
                request.correlation_id = correlation_id;
                bus.publish(
                    ComputeRequestError::new(error.get_err().clone(), request),
                    cause.get_ctx().clone(),
                )
            }
        };
        if let Err(error) = result {
            tracing::error!("failed to send compute outcome to a retried request: {error}");
        }
    }

    pub(crate) fn attach(
        bus: &BusHandle,
        target: Recipient<InterfoldEvent>,
        initial_stages: HashMap<E3id, E3Stage>,
        canonical_keys: e3_request::canonical_key::CanonicalPublicKeys,
        running: RunningJobs,
    ) {
        let mut gate = Self::new(target, initial_stages).with_bus(bus.clone());
        gate.canonical_keys = canonical_keys;
        gate.running = running;
        let gate = gate.start();
        bus.subscribe_all(
            &[
                EventType::ComputeRequest,
                EventType::ComputeResponse,
                EventType::ComputeRequestError,
                EventType::EffectsEnabled,
                EventType::E3RequestComplete,
                EventType::E3Failed,
                EventType::E3StageChanged,
            ],
            gate.recipient(),
        );
    }

    fn queue(&mut self, event: InterfoldEvent) {
        let InterfoldEventData::ComputeRequest(request) = event.get_data() else {
            return;
        };
        let key = (request.e3_id.clone(), request.request.clone());
        self.request_keys_by_correlation
            .insert(request.correlation_id, key.clone());
        match self.pending.entry(key) {
            std::collections::hash_map::Entry::Occupied(mut entry)
                if event.ts() > entry.get().ts() =>
            {
                entry.insert(event);
            }
            std::collections::hash_map::Entry::Vacant(entry) => {
                entry.insert(event);
            }
            _ => {}
        }
    }

    fn enable(&mut self) {
        self.enabled = true;
        let mut pending: Vec<_> = self.pending.drain().map(|(_, event)| event).collect();
        pending.sort_by_key(EventContextAccessors::ts);
        let count = pending.len();
        for event in pending {
            self.forward(event);
        }
        info!(count, "released replay-safe compute effects");
    }

    /// Clear the keys of the work of `e3_id` that its stage makes obsolete. A failure keeps the
    /// accusation work; a complete request keeps nothing.
    fn cancel(&mut self, e3_id: &E3id) {
        let stage = self.stages.get(e3_id).cloned();
        let ends = |(request_id, kind): &RequestKey| {
            request_id == e3_id && Self::request_is_obsolete_at_stage(stage.as_ref(), kind)
        };
        self.pending.retain(|key, _| !ends(key));
        self.forwarded.retain(|key, _| !ends(key));
        self.replayed_responses.retain(|key, _| !ends(key));
        self.request_keys_by_correlation.retain(|_, key| !ends(key));
    }
}

impl Actor for ComputeEffectGate {
    type Context = Context<Self>;

    fn started(&mut self, ctx: &mut Self::Context) {
        ctx.set_mailbox_capacity(MAILBOX_LIMIT);
    }
}

impl Handler<InterfoldEvent> for ComputeEffectGate {
    type Result = ();

    fn handle(&mut self, event: InterfoldEvent, _: &mut Self::Context) {
        match event.get_data() {
            InterfoldEventData::ComputeRequest(_) if self.enabled => {
                self.forward(event);
            }
            InterfoldEventData::ComputeRequest(_) => self.queue(event),
            InterfoldEventData::ComputeResponse(_) | InterfoldEventData::ComputeRequestError(_) => {
                self.on_outcome(&event);
            }
            InterfoldEventData::EffectsEnabled(_) => self.enable(),
            InterfoldEventData::E3RequestComplete(complete) => {
                // The request ends after a failure too, so Complete replaces Failed here.
                self.stages
                    .insert(complete.e3_id.clone(), E3Stage::Complete);
                self.cancel(&complete.e3_id);
            }
            InterfoldEventData::E3Failed(failed) => {
                self.record_stage(failed.e3_id.clone(), E3Stage::Failed);
                self.cancel(&failed.e3_id);
            }
            InterfoldEventData::E3StageChanged(stage) => {
                self.record_stage(stage.e3_id.clone(), stage.new_stage.clone());
                if stage.new_stage.is_terminal() {
                    self.cancel(&stage.e3_id);
                }
            }
            _ => {}
        }
    }
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;
    use actix::{Addr, Message, ResponseFuture};
    use e3_events::{
        hlc_factory::HlcFactory, CircuitName, ComputeRequest, ComputeRequestErrorKind,
        ComputeResponseKind, E3RequestComplete, EffectsEnabled, EventBus, EventBusConfig,
        EventConstructorWithTimestamp, EventSource, HistoryCollector, PartyProofsToVerify,
        PkBfvProofRequest, Proof, ProofPayload, Sequencer, SignedProofPayload, StoreEventRequested,
        StoreEventResponse, TakeEvents, Unsequenced, VerifyShareProofsRequest, ZkError, ZkRequest,
        ZkResponse,
    };
    use e3_fhe_params::BfvPreset;
    use e3_utils::ArcBytes;
    use e3_zk_helpers::CiphernodesCommitteeSize;

    #[derive(Message)]
    #[rtype(result = "Vec<CorrelationId>")]
    struct Received;

    #[derive(Default)]
    struct Recorder(Vec<CorrelationId>);

    impl Actor for Recorder {
        type Context = Context<Self>;
    }

    impl Handler<InterfoldEvent> for Recorder {
        type Result = ();

        fn handle(&mut self, event: InterfoldEvent, _: &mut Self::Context) {
            if let InterfoldEventData::ComputeRequest(request) = event.get_data() {
                self.0.push(request.correlation_id);
            }
        }
    }

    impl Handler<Received> for Recorder {
        type Result = ResponseFuture<Vec<CorrelationId>>;

        fn handle(&mut self, _: Received, _: &mut Self::Context) -> Self::Result {
            let received = self.0.clone();
            Box::pin(async move { received })
        }
    }

    #[derive(Default)]
    struct TestEventStore {
        next_seq: u64,
    }

    impl Actor for TestEventStore {
        type Context = Context<Self>;
    }

    impl Handler<StoreEventRequested> for TestEventStore {
        type Result = ();

        fn handle(&mut self, msg: StoreEventRequested, _: &mut Self::Context) {
            let StoreEventRequested { event, sender } = msg;
            let seq = self.next_seq;
            self.next_seq += 1;
            let _ = sender.try_send(StoreEventResponse(event.into_sequenced(seq)));
        }
    }

    pub(crate) fn test_bus() -> (BusHandle, Addr<HistoryCollector<InterfoldEvent>>) {
        let event_bus =
            EventBus::<InterfoldEvent>::new(EventBusConfig { deduplicate: true }).start();
        let store = TestEventStore::default().start();
        let sequencer = Sequencer::new(&event_bus, store.recipient()).start();
        let bus = BusHandle::new(event_bus, sequencer, HlcFactory::new()).enable("test-gate");
        let history = bus.history();
        (bus, history)
    }

    fn outcome_event(data: impl Into<InterfoldEventData>) -> InterfoldEvent {
        InterfoldEvent::<Unsequenced>::new_with_timestamp(
            data.into(),
            None,
            50,
            None,
            EventSource::Local,
        )
        .into_sequenced(4)
    }

    async fn next_outcome(history: &Addr<HistoryCollector<InterfoldEvent>>) -> InterfoldEvent {
        let mut result = history
            .send(TakeEvents::<InterfoldEvent>::new(1))
            .await
            .unwrap();
        assert!(!result.timed_out, "expected a mirrored compute outcome");
        result.events.pop().unwrap()
    }

    fn response(correlation_id: CorrelationId) -> ComputeResponse {
        ComputeResponse::new(
            ComputeResponseKind::Zk(ZkResponse::PkBfv(e3_events::PkBfvProofResponse::new(
                Proof::new(
                    CircuitName::PkBfv,
                    ArcBytes::from_bytes(&[1]),
                    ArcBytes::from_bytes(&[2]),
                ),
            ))),
            correlation_id,
            E3id::new("4", 1),
        )
    }

    fn failure(correlation_id: CorrelationId) -> ComputeRequestError {
        let InterfoldEventData::ComputeRequest(request) = compute(correlation_id, 10).into_data()
        else {
            unreachable!();
        };
        ComputeRequestError::new(
            ComputeRequestErrorKind::Zk(ZkError::ProofGenerationFailed("failed".into())),
            request,
        )
    }

    fn compute(correlation_id: CorrelationId, timestamp: u128) -> InterfoldEvent {
        let request = ComputeRequest::zk(
            ZkRequest::PkBfv(PkBfvProofRequest::new(
                ArcBytes::from_bytes(&[]),
                BfvPreset::default(),
                CiphernodesCommitteeSize::Micro,
            )),
            correlation_id,
            E3id::new("4", 1),
        );
        InterfoldEvent::<Unsequenced>::new_with_timestamp(
            request.into(),
            None,
            timestamp,
            None,
            EventSource::Local,
        )
        .into_sequenced(1)
    }

    fn share_verification_compute(
        correlation_id: CorrelationId,
        timestamp: u128,
        proof_type: ProofType,
        circuit: CircuitName,
    ) -> InterfoldEvent {
        let proof = SignedProofPayload {
            payload: ProofPayload {
                e3_id: E3id::new("4", 1),
                proof_type,
                proof: Proof::new(
                    circuit,
                    ArcBytes::from_bytes(&[1]),
                    ArcBytes::from_bytes(&[2]),
                ),
            },
            signature: ArcBytes::from_bytes(&[3]),
        };
        let request = ComputeRequest::zk(
            ZkRequest::VerifyShareProofs(VerifyShareProofsRequest {
                party_proofs: vec![PartyProofsToVerify {
                    sender_party_id: 0,
                    signed_proofs: vec![proof],
                }],
                params_preset: BfvPreset::default(),
                committee_size: CiphernodesCommitteeSize::Micro,
            }),
            correlation_id,
            E3id::new("4", 1),
        );
        InterfoldEvent::<Unsequenced>::new_with_timestamp(
            request.into(),
            None,
            timestamp,
            None,
            EventSource::Local,
        )
        .into_sequenced(1)
    }

    /// An accusation's re-verification of the forwarded C3a proof of `party`.
    fn accusation_compute(
        correlation_id: CorrelationId,
        timestamp: u128,
        party: u64,
    ) -> InterfoldEvent {
        let InterfoldEventData::ComputeRequest(mut request) = share_verification_compute(
            correlation_id,
            timestamp,
            ProofType::C3aSkShareEncryption,
            CircuitName::ShareEncryption,
        )
        .into_data() else {
            unreachable!();
        };
        let ComputeRequestKind::Zk(ZkRequest::VerifyShareProofs(mut proofs)) = request.request
        else {
            unreachable!();
        };
        proofs.party_proofs[0].sender_party_id = party;
        request.request = ComputeRequestKind::Zk(ZkRequest::ReverifyAccusedProof(proofs));
        InterfoldEvent::<Unsequenced>::new_with_timestamp(
            request.into(),
            None,
            timestamp,
            None,
            EventSource::Local,
        )
        .into_sequenced(1)
    }

    fn failed() -> InterfoldEvent {
        InterfoldEvent::<Unsequenced>::new_with_timestamp(
            e3_events::E3Failed {
                e3_id: E3id::new("4", 1),
                failed_at_stage: E3Stage::CommitteeFinalized,
                reason: e3_events::FailureReason::DKGInvalidShares,
            }
            .into(),
            None,
            35,
            None,
            EventSource::Evm,
        )
        .into_sequenced(3)
    }

    fn effects_enabled() -> InterfoldEvent {
        InterfoldEvent::<Unsequenced>::new_with_timestamp(
            EffectsEnabled::new().into(),
            None,
            30,
            None,
            EventSource::Local,
        )
        .into_sequenced(2)
    }

    fn completed() -> InterfoldEvent {
        InterfoldEvent::<Unsequenced>::new_with_timestamp(
            E3RequestComplete {
                e3_id: E3id::new("4", 1),
            }
            .into(),
            None,
            25,
            None,
            EventSource::Local,
        )
        .into_sequenced(2)
    }

    #[actix::test]
    async fn buffers_until_enabled_and_keeps_newest_semantic_retry() {
        let recorder = Recorder::default().start();
        let gate = ComputeEffectGate::new(recorder.clone().recipient(), HashMap::new()).start();
        let stale = CorrelationId::new();
        let regenerated = CorrelationId::new();

        gate.send(compute(stale, 10)).await.unwrap();
        gate.send(compute(regenerated, 20)).await.unwrap();
        assert!(recorder.send(Received).await.unwrap().is_empty());

        gate.send(effects_enabled()).await.unwrap();
        assert_eq!(recorder.send(Received).await.unwrap(), vec![regenerated]);
    }

    #[actix::test]
    async fn replayed_success_satisfies_regenerated_request_without_recomputing() {
        let (bus, history) = test_bus();
        let recorder = Recorder::default().start();
        let gate = ComputeEffectGate::new(recorder.clone().recipient(), HashMap::new())
            .with_bus(bus)
            .start();
        let durable = CorrelationId::new();
        let regenerated = CorrelationId::new();

        gate.send(compute(durable, 10)).await.unwrap();
        gate.send(outcome_event(response(durable))).await.unwrap();
        gate.send(compute(regenerated, 20)).await.unwrap();
        gate.send(effects_enabled()).await.unwrap();

        assert!(recorder.send(Received).await.unwrap().is_empty());
        assert!(matches!(
            next_outcome(&history).await.into_data(),
            InterfoldEventData::ComputeResponse(result)
                if result.correlation_id == regenerated
        ));
    }

    #[actix::test]
    async fn replayed_success_survives_actor_redrive_interleaving() {
        let (bus, history) = test_bus();
        let recorder = Recorder::default().start();
        let gate = ComputeEffectGate::new(recorder.clone().recipient(), HashMap::new())
            .with_bus(bus)
            .start();
        let durable = CorrelationId::new();
        let regenerated = CorrelationId::new();

        // A hydrated actor can redrive work while historical events are still reaching other
        // subscribers. The newer request must remain selected even if its historical request and
        // successful response arrive afterward.
        gate.send(compute(regenerated, 20)).await.unwrap();
        gate.send(compute(durable, 10)).await.unwrap();
        gate.send(outcome_event(response(durable))).await.unwrap();
        gate.send(effects_enabled()).await.unwrap();

        assert!(recorder.send(Received).await.unwrap().is_empty());
        assert!(matches!(
            next_outcome(&history).await.into_data(),
            InterfoldEventData::ComputeResponse(result)
                if result.correlation_id == regenerated
        ));
    }

    #[actix::test]
    async fn replayed_failure_does_not_suppress_a_recovery_attempt() {
        let recorder = Recorder::default().start();
        let gate = ComputeEffectGate::new(recorder.clone().recipient(), HashMap::new()).start();
        let failed = CorrelationId::new();
        let regenerated = CorrelationId::new();

        gate.send(compute(failed, 10)).await.unwrap();
        gate.send(outcome_event(failure(failed))).await.unwrap();
        gate.send(compute(regenerated, 20)).await.unwrap();
        gate.send(effects_enabled()).await.unwrap();

        assert_eq!(recorder.send(Received).await.unwrap(), vec![regenerated]);
    }

    #[actix::test]
    async fn terminal_e3_cancels_buffered_effects() {
        let recorder = Recorder::default().start();
        let gate = ComputeEffectGate::new(recorder.clone().recipient(), HashMap::new()).start();

        gate.send(compute(CorrelationId::new(), 10)).await.unwrap();
        gate.send(completed()).await.unwrap();
        gate.send(effects_enabled()).await.unwrap();

        assert!(recorder.send(Received).await.unwrap().is_empty());
    }

    #[actix::test]
    async fn drops_redriven_duplicate_after_enable() {
        let recorder = Recorder::default().start();
        let gate = ComputeEffectGate::new(recorder.clone().recipient(), HashMap::new()).start();
        let buffered = CorrelationId::new();
        let redriven = CorrelationId::new();

        // Released from the replay buffer on enable.
        gate.send(compute(buffered, 10)).await.unwrap();
        gate.send(effects_enabled()).await.unwrap();
        assert_eq!(recorder.send(Received).await.unwrap(), vec![buffered]);

        // Same (e3_id, kind) re-driven by a hydrated actor after EffectsEnabled
        // is suppressed — only one compute reaches the target.
        gate.send(compute(redriven, 40)).await.unwrap();
        assert_eq!(recorder.send(Received).await.unwrap(), vec![buffered]);
    }

    #[actix::test]
    async fn redriven_request_receives_success_under_its_own_id() {
        let (bus, history) = test_bus();
        let recorder = Recorder::default().start();
        let gate = ComputeEffectGate::new(recorder.clone().recipient(), HashMap::new())
            .with_bus(bus)
            .start();
        let old = CorrelationId::new();
        let current = CorrelationId::new();

        gate.send(compute(old, 10)).await.unwrap();
        gate.send(effects_enabled()).await.unwrap();
        gate.send(compute(current, 40)).await.unwrap();
        assert_eq!(recorder.send(Received).await.unwrap(), vec![old]);
        gate.send(outcome_event(response(old))).await.unwrap();

        assert!(matches!(
            next_outcome(&history).await.into_data(),
            InterfoldEventData::ComputeResponse(result) if result.correlation_id == current
        ));
    }

    #[actix::test]
    async fn redriven_request_receives_failure_under_its_own_id() {
        let (bus, history) = test_bus();
        let recorder = Recorder::default().start();
        let gate = ComputeEffectGate::new(recorder.clone().recipient(), HashMap::new())
            .with_bus(bus)
            .start();
        let old = CorrelationId::new();
        let current = CorrelationId::new();

        gate.send(compute(old, 10)).await.unwrap();
        gate.send(effects_enabled()).await.unwrap();
        gate.send(compute(current, 40)).await.unwrap();
        assert_eq!(recorder.send(Received).await.unwrap(), vec![old]);
        gate.send(outcome_event(failure(old))).await.unwrap();

        let InterfoldEventData::ComputeRequestError(result) =
            next_outcome(&history).await.into_data()
        else {
            panic!("expected a compute error");
        };
        assert_eq!(result.correlation_id(), &current);
        assert_eq!(result.request().request, failure(old).request().request);
    }

    #[actix::test]
    async fn late_redriven_request_receives_cached_outcome() {
        let (bus, history) = test_bus();
        let recorder = Recorder::default().start();
        let gate = ComputeEffectGate::new(recorder.clone().recipient(), HashMap::new())
            .with_bus(bus)
            .start();
        let old = CorrelationId::new();
        let current = CorrelationId::new();

        gate.send(compute(old, 10)).await.unwrap();
        gate.send(effects_enabled()).await.unwrap();
        gate.send(outcome_event(response(old))).await.unwrap();
        gate.send(compute(current, 40)).await.unwrap();
        assert_eq!(recorder.send(Received).await.unwrap(), vec![old]);

        assert!(matches!(
            next_outcome(&history).await.into_data(),
            InterfoldEventData::ComputeResponse(result) if result.correlation_id == current
        ));
    }

    #[actix::test]
    async fn a_failed_e3_keeps_its_accusation_work_until_the_request_completes() {
        let recorder = Recorder::default().start();
        let stages = HashMap::from([(E3id::new("4", 1), E3Stage::Failed)]);
        let gate = ComputeEffectGate::new(recorder.clone().recipient(), stages).start();
        let dkg = CorrelationId::new();
        let accusation = CorrelationId::new();

        gate.send(effects_enabled()).await.unwrap();
        gate.send(share_verification_compute(
            dkg,
            40,
            ProofType::C3aSkShareEncryption,
            CircuitName::ShareEncryption,
        ))
        .await
        .unwrap();
        gate.send(accusation_compute(accusation, 41, 0))
            .await
            .unwrap();
        assert_eq!(recorder.send(Received).await.unwrap(), vec![accusation]);

        // Another accused proof after the request completed.
        gate.send(completed()).await.unwrap();
        gate.send(accusation_compute(CorrelationId::new(), 42, 1))
            .await
            .unwrap();
        assert_eq!(recorder.send(Received).await.unwrap(), vec![accusation]);
    }

    #[actix::test]
    async fn a_failure_keeps_queued_accusation_work_and_drops_the_rest() {
        let recorder = Recorder::default().start();
        let gate = ComputeEffectGate::new(recorder.clone().recipient(), HashMap::new()).start();
        let accusation = CorrelationId::new();

        gate.send(compute(CorrelationId::new(), 10)).await.unwrap();
        gate.send(accusation_compute(accusation, 11, 0))
            .await
            .unwrap();
        gate.send(failed()).await.unwrap();
        gate.send(effects_enabled()).await.unwrap();

        assert_eq!(recorder.send(Received).await.unwrap(), vec![accusation]);
    }

    #[actix::test]
    async fn stalled_request_goes_to_the_worker_again() {
        let (bus, history) = test_bus();
        let recorder = Recorder::default().start();
        let mut gate =
            ComputeEffectGate::new(recorder.clone().recipient(), HashMap::new()).with_bus(bus);
        gate.reforward_after = Duration::from_millis(500);
        let gate = gate.start();
        let lost = CorrelationId::new();
        let waiting = CorrelationId::new();
        let again = CorrelationId::new();
        let late = CorrelationId::new();

        // The answer to `lost` never reaches the gate. A new ID soon after waits for it, and a
        // new ID after the window sends the request to the worker again.
        gate.send(compute(lost, 10)).await.unwrap();
        gate.send(effects_enabled()).await.unwrap();
        gate.send(compute(waiting, 40)).await.unwrap();
        assert_eq!(recorder.send(Received).await.unwrap(), vec![lost]);
        actix::clock::sleep(Duration::from_millis(600)).await;
        gate.send(compute(again, 50)).await.unwrap();
        gate.send(compute(again, 50)).await.unwrap();
        assert_eq!(recorder.send(Received).await.unwrap(), vec![lost, again]);

        // The second run answers the waiting ID. A late error from the first run does not
        // replace that success.
        gate.send(outcome_event(response(again))).await.unwrap();
        gate.send(outcome_event(failure(lost))).await.unwrap();
        gate.send(compute(late, 60)).await.unwrap();
        for expected in [waiting, late] {
            assert!(matches!(
                next_outcome(&history).await.into_data(),
                InterfoldEventData::ComputeResponse(result) if result.correlation_id == expected
            ));
        }
        assert_eq!(recorder.send(Received).await.unwrap(), vec![lost, again]);
    }

    #[actix::test]
    async fn a_request_that_the_worker_still_runs_goes_to_it_once() {
        let (bus, history) = test_bus();
        let recorder = Recorder::default().start();
        let running = RunningJobs::default();
        let mut gate =
            ComputeEffectGate::new(recorder.clone().recipient(), HashMap::new()).with_bus(bus);
        gate.reforward_after = Duration::from_millis(100);
        gate.running = running.clone();
        let gate = gate.start();
        let first = CorrelationId::new();
        let waiting = CorrelationId::new();
        let again = CorrelationId::new();

        // The worker still runs `first` after the window, as a slow proof under load does: a new
        // ID waits for that run.
        let job = running.start(first);
        gate.send(compute(first, 10)).await.unwrap();
        gate.send(effects_enabled()).await.unwrap();
        actix::clock::sleep(Duration::from_millis(200)).await;
        gate.send(compute(waiting, 40)).await.unwrap();
        assert_eq!(recorder.send(Received).await.unwrap(), vec![first]);

        // The run ends, and its result never reaches the gate: a new ID sends the request again,
        // and that result answers the waiting ID.
        drop(job);
        gate.send(compute(again, 50)).await.unwrap();
        assert_eq!(recorder.send(Received).await.unwrap(), vec![first, again]);
        gate.send(outcome_event(response(again))).await.unwrap();
        assert!(matches!(
            next_outcome(&history).await.into_data(),
            InterfoldEventData::ComputeResponse(result) if result.correlation_id == waiting
        ));
    }

    /// A replayed run can share its correlation ID with a new run, since IDs restart in each
    /// process. The ID runs until both end.
    #[test]
    fn an_id_runs_until_its_last_run_ends() {
        let running = RunningJobs::default();
        let id = CorrelationId::new();
        let replayed = running.start(id);
        let new = running.start(id);
        drop(replayed);
        assert!(running.any(&[id]));
        drop(new);
        assert!(!running.any(&[id]));
    }

    #[actix::test]
    async fn key_published_snapshot_discards_obsolete_dkg_work() {
        let recorder = Recorder::default().start();
        let stages = HashMap::from([(E3id::new("4", 1), E3Stage::KeyPublished)]);
        let gate = ComputeEffectGate::new(recorder.clone().recipient(), stages).start();

        gate.send(compute(CorrelationId::new(), 10)).await.unwrap();
        gate.send(effects_enabled()).await.unwrap();
        gate.send(compute(CorrelationId::new(), 40)).await.unwrap();

        assert!(recorder.send(Received).await.unwrap().is_empty());
    }

    #[actix::test]
    async fn key_published_snapshot_keeps_threshold_decryption_verification() {
        let recorder = Recorder::default().start();
        let stages = HashMap::from([(E3id::new("4", 1), E3Stage::CiphertextReady)]);
        let gate = ComputeEffectGate::new(recorder.clone().recipient(), stages).start();
        let dkg_correlation_id = CorrelationId::new();
        let correlation_id = CorrelationId::new();

        gate.send(share_verification_compute(
            dkg_correlation_id,
            5,
            ProofType::C1PkGeneration,
            CircuitName::PkGeneration,
        ))
        .await
        .unwrap();
        gate.send(share_verification_compute(
            correlation_id,
            10,
            ProofType::C6ThresholdShareDecryption,
            CircuitName::ThresholdShareDecryption,
        ))
        .await
        .unwrap();
        gate.send(effects_enabled()).await.unwrap();

        assert_eq!(recorder.send(Received).await.unwrap(), vec![correlation_id]);
    }
    #[actix::test]
    async fn replayed_c6_compute_requires_canonical_public_inputs() -> anyhow::Result<()> {
        use alloy::primitives::Address;
        use e3_fhe_params::BfvParamSet;
        use e3_request::canonical_key::{CanonicalPublicKey, CanonicalPublicKeys};
        let id = E3id::new("84", 1);
        let params = BfvParamSet::from(BfvPreset::InsecureThreshold512);
        let bytes = e3_bfv_client::client::generate_public_key(
            params.degree,
            params.plaintext_modulus,
            params.moduli.to_vec(),
        )?;
        let key = CanonicalPublicKey {
            pk_commitment: e3_bfv_client::compute_pk_commitment(
                bytes.clone(),
                params.degree,
                params.plaintext_modulus,
                params.moduli.to_vec(),
            )?,
            committee: vec![
                Address::repeat_byte(1),
                Address::repeat_byte(2),
                Address::repeat_byte(3),
            ],
            honest_committee: vec![Address::repeat_byte(1), Address::repeat_byte(3)],
            params_preset: BfvPreset::InsecureThreshold512,
            committee_size: CiphernodesCommitteeSize::Minimum,
            interfold_address: Address::repeat_byte(9),
            sk_agg_commits: vec![],
            esm_agg_commits: vec![],
        };
        let keys = CanonicalPublicKeys::default();
        keys.insert(id.clone(), key.clone())?;
        let mut request = e3_events::ThresholdShareDecryptionProofRequest {
            ciphertext_bytes: vec![ArcBytes::from_bytes(&[5])],
            aggregated_pk_bytes: ArcBytes::from_bytes(&bytes),
            sk_poly_sum: e3_crypto::SensitiveBytes::from_encrypted(&[2]),
            es_poly_sum: vec![e3_crypto::SensitiveBytes::from_encrypted(&[3])],
            d_share_bytes: vec![ArcBytes::from_bytes(&[4])],
            decryption_domain: key.domain(Address::ZERO),
            params_preset: key.params_preset,
            committee_size: key.committee_size,
        };
        let target = Recorder::default().start();
        let mut gate = ComputeEffectGate::new(target.clone().recipient(), HashMap::new());
        gate.canonical_keys = keys;
        let gate = gate.start();
        gate.send(outcome_event(ComputeRequest::zk(
            ZkRequest::ThresholdShareDecryption(request.clone()),
            CorrelationId::new(),
            id.clone(),
        )))
        .await?;
        request.decryption_domain = key.domain(key.interfold_address);
        let accepted = CorrelationId::new();
        gate.send(outcome_event(ComputeRequest::zk(
            ZkRequest::ThresholdShareDecryption(request),
            accepted,
            id,
        )))
        .await?;
        assert!(target.send(Received).await?.is_empty());
        gate.send(outcome_event(EffectsEnabled::new())).await?;
        assert_eq!(target.send(Received).await?, vec![accepted]);
        Ok(())
    }
}
