# SPDX-License-Identifier: LGPL-3.0-only
#
# This file is provided WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.

[package]
name = "lbfv_pk_aggregation"
type = "bin"
authors = ["Gnosis Guild / Interfold"]

[dependencies]
lib = { path = "../../../lib" }
