// SPDX-License-Identifier: LGPL-3.0-only
//
// This file is provided WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE.

//! Asserts that the Rust input tree reproduces a root a real contract actually produced.
//!
//! The fixture is generated by `tests/input-tree-e2e.test.ts` in `crisp-contracts`, which publishes
//! a real ballot — real BFV ciphertext, real Noir proof — through `publishInput` and records the
//! resulting on-chain `inputRoot`. Regenerate with
//! `UPDATE_INPUT_TREE_FIXTURE=1 pnpm test` in that package.
//!
//! This is the one check that catches a divergence between `CRISPProgram.inputLeaf` and
//! `MerkleTreeBuilder`. Such a divergence makes every round fail with no other symptom, and no
//! single-language test can see it.

use e3_compute_provider::{ComputeInput, FHEInputs, PublishedData};
use e3_fhe_params::{build_pair_for_preset, encode_bfv_params, BfvPreset};
use e3_user_program::policy::crisp;
use sha3::Digest as _;

const FIXTURE: &str = include_str!("../../packages/crisp-contracts/tests/fixtures/input-tree.json");

/// Reads the fixture entries into the shapes `ComputeInput` takes.
///
/// The metadata is `slot || parentIndexPlusOne`, byte for byte what `CRISPProgram` hashes into the
/// leaf as `abi.encodePacked(address, uint40)`.
fn load(entries: &[serde_json::Value]) -> (Vec<(Vec<u8>, u64)>, Vec<PublishedData>) {
    let mut ciphertexts = Vec::new();
    let mut published = Vec::new();
    for (index, entry) in entries.iter().enumerate() {
        ciphertexts.push((
            unhex(entry["encryptedVote"].as_str().expect("encryptedVote")),
            index as u64,
        ));

        let parent = entry["parentIndexPlusOne"]
            .as_u64()
            .expect("parentIndexPlusOne");
        let mut metadata = unhex(entry["slot"].as_str().expect("slot"));
        metadata.extend_from_slice(&parent.to_be_bytes()[3..]);

        published.push(PublishedData {
            commitment: Some(
                <[u8; 32]>::try_from(
                    unhex(entry["commitment"].as_str().expect("commitment")).as_slice(),
                )
                .expect("32-byte commitment"),
            ),
            metadata,
        });
    }
    (ciphertexts, published)
}

fn unhex(value: &str) -> Vec<u8> {
    hex::decode(value.trim_start_matches("0x")).expect("fixture hex")
}

#[test]
fn rust_reproduces_the_root_the_contract_produced() {
    let fixture: serde_json::Value = serde_json::from_str(FIXTURE).expect("fixture json");
    let expected_root = unhex(fixture["inputRoot"].as_str().expect("inputRoot"));

    let entries = fixture["inputs"].as_array().expect("inputs");
    let (ciphertexts, published) = load(entries);

    // The SDK builds ballots under the insecure threshold preset.
    let (params, _) = build_pair_for_preset(BfvPreset::InsecureThreshold).unwrap();
    let result = ComputeInput {
        fhe_inputs: FHEInputs {
            ciphertexts,
            params: encode_bfv_params(&params),
            committee_key: Vec::new(),
        },
        published,
    }
    .process(
        |inputs| {
            // Membership of the tree is what this test asserts, so the processor only has to be
            // deterministic over the selected set.
            inputs
                .ciphertexts
                .iter()
                .flat_map(|(bytes, _)| bytes.clone())
                .collect()
        },
        crisp(),
    )
    .expect("the fixture round must process");

    assert_eq!(
        hex::encode(&result.merkle_root),
        hex::encode(&expected_root),
        "the Rust input tree diverged from the root CRISPProgram produced"
    );
}

/// The TypeScript SDK and Rust must agree on `compute_ct_commitment`, or the Secure Process would
/// reject every honest input as contradicting its commitment.
#[test]
fn the_sdk_and_rust_agree_on_the_ciphertext_commitment() {
    let fixture: serde_json::Value = serde_json::from_str(FIXTURE).unwrap();
    let entry = &fixture["inputs"][0];
    let bytes = unhex(entry["encryptedVote"].as_str().unwrap());
    let stored = unhex(entry["commitment"].as_str().unwrap());

    let (params, _) = build_pair_for_preset(BfvPreset::InsecureThreshold).unwrap();
    let recomputed = e3_bfv_client::client::compute_ct_commitment(
        bytes,
        params.degree(),
        params.plaintext(),
        params.moduli().to_vec(),
    )
    .expect("a ciphertext the SDK produced must deserialize");

    assert_eq!(
        hex::encode(recomputed),
        hex::encode(&stored),
        "the SDK commitment and the Rust commitment diverged"
    );
}

const APPEND_FIXTURE: &str =
    include_str!("../../packages/crisp-contracts/tests/fixtures/input-tree-append.json");

/// The poisoning case, against a tree a real contract built.
///
/// The fixture holds three entries for one slot: an honest ballot, a genuine mask proof published
/// beside bytes that are not the summed ciphertext it proved, and an honest mask naming the same
/// parent that poisoned one named. The Secure Process must reproduce the on-chain root over all
/// three, skip the poisoned entry, and select the honest mask.
///
/// The recovery is the point. A poisoned entry is never selected, so it is never a valid parent
/// either, and the slot stays maskable. A slot that could be frozen against masking would be one
/// where every later input is provably its owner voting again.
#[test]
fn rust_selects_the_honest_mask_that_follows_a_poisoned_one() {
    let fixture: serde_json::Value = serde_json::from_str(APPEND_FIXTURE).expect("fixture json");
    let expected_root = unhex(fixture["inputRoot"].as_str().expect("inputRoot"));
    let honest_index = fixture["honestIndex"].as_u64().expect("honestIndex") as usize;

    let entries = fixture["inputs"].as_array().expect("inputs");
    let (ciphertexts, published) = load(entries);
    assert_eq!(entries.len(), 3, "the fixture must hold all three entries");
    assert!(
        published
            .iter()
            .all(|entry| entry.metadata[..20] == published[0].metadata[..20]),
        "every entry belongs to one slot"
    );

    let honest_bytes = ciphertexts[honest_index].0.clone();
    let (params, _) = build_pair_for_preset(BfvPreset::InsecureThreshold).unwrap();

    // The processor records what it was handed, so the selection is observable.
    let result = ComputeInput {
        fhe_inputs: FHEInputs {
            ciphertexts,
            params: encode_bfv_params(&params),
            committee_key: Vec::new(),
        },
        published,
    }
    .process(
        |inputs| {
            inputs
                .ciphertexts
                .iter()
                .flat_map(|(bytes, _)| bytes.clone())
                .collect()
        },
        crisp(),
    )
    .expect("a poisoned append must not stop the round");

    assert_eq!(
        hex::encode(&result.merkle_root),
        hex::encode(&expected_root),
        "the Rust input tree diverged from the root CRISPProgram produced"
    );

    // The processor saw exactly the honest ballot: the poisoned append was skipped, and the entry
    // it tried to replace survived.
    assert_eq!(
        result.ciphertext_hash,
        sha3::Keccak256::digest(&honest_bytes).to_vec(),
        "the Secure Process must select the honest mask that followed the poisoned entry"
    );
}

const REVOTE_FIXTURE: &str =
    include_str!("../../packages/crisp-contracts/tests/fixtures/input-tree-revote.json");

/// A voter who changes their mind must have the new ballot tallied, not the first one.
///
/// The fixture is a real round: a ballot, then a real re-vote to the same slot, both accepted by
/// `CRISPProgram`. If the published bytes and the stored commitment describe different ciphertexts
/// the Secure Process cannot verify the re-vote, silently drops it, and the voter is stuck with
/// their first choice while the round still completes.
#[test]
fn rust_tallies_the_re_vote() {
    let fixture: serde_json::Value = serde_json::from_str(REVOTE_FIXTURE).expect("fixture json");
    let expected_root = unhex(fixture["inputRoot"].as_str().expect("inputRoot"));
    let re_vote_index = fixture["reVoteIndex"].as_u64().expect("reVoteIndex") as usize;
    let entries = fixture["inputs"].as_array().expect("inputs");
    let (ciphertexts, published) = load(entries);

    let re_vote_bytes = ciphertexts[re_vote_index].0.clone();
    let (params, _) = build_pair_for_preset(BfvPreset::InsecureThreshold).unwrap();

    // Does the published ciphertext reproduce the commitment the contract stored for it?
    let recomputed = e3_bfv_client::client::compute_ct_commitment(
        re_vote_bytes.clone(),
        params.degree(),
        params.plaintext(),
        params.moduli().to_vec(),
    )
    .expect("the re-vote ciphertext must deserialize");
    assert_eq!(
        hex::encode(recomputed),
        hex::encode(published[re_vote_index].commitment.unwrap()),
        "the re-vote's published bytes must be the ciphertext its stored commitment describes"
    );

    let result = ComputeInput {
        fhe_inputs: FHEInputs {
            ciphertexts,
            params: encode_bfv_params(&params),
            committee_key: Vec::new(),
        },
        published,
    }
    .process(
        |inputs| {
            inputs
                .ciphertexts
                .iter()
                .flat_map(|(bytes, _)| bytes.clone())
                .collect()
        },
        crisp(),
    )
    .expect("a round with a re-vote must process");

    assert_eq!(
        hex::encode(&result.merkle_root),
        hex::encode(&expected_root),
        "the Rust input tree diverged from the root CRISPProgram produced"
    );
    assert_eq!(
        result.ciphertext_hash,
        sha3::Keccak256::digest(&re_vote_bytes).to_vec(),
        "the re-vote must be the entry that is tallied"
    );
}
