// SPDX-License-Identifier: LGPL-3.0-only
//
// This file is provided WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE.

// Sync server/.env + client/.env from
// packages/interfold-contracts/deployed_contracts.json (like CRISP's
// `pnpm dev:setup`): the coordinator and the browser must point at the
// SAME deployed Interfold / CkksSalaryE3Program addresses.
//
//   node scripts/sync-config.mjs [--network localhost] [--relin-key-dir /tmp/ckks-relin-keys]

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.join(here, '..')
const interfold = path.join(root, '../..')
const args = process.argv.slice(2)
const opt = (n, d) => {
  const i = args.indexOf(n)
  return i >= 0 ? args[i + 1] : d
}
const network = opt('--network', 'localhost')
const relinKeyDir = opt('--relin-key-dir', process.env.CKKS_RELIN_KEY_DIR ?? '/tmp/ckks-relin-keys')
const port = opt('--port', '8091')

const deployed = JSON.parse(readFileSync(path.join(interfold, 'packages/interfold-contracts/deployed_contracts.json'), 'utf8'))
const chain = deployed[network]
if (!chain) throw new Error(`no ${network} entry in deployed_contracts.json — run pnpm evm:deploy first`)
const addr = (name) => {
  const a = chain[name]?.address
  if (!a) throw new Error(`${name} not deployed on ${network}`)
  return a
}

// anvil account #0 — the relayer/admin (CRISP uses the same on localhost).
const DEFAULT_KEY = '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'
const serverEnvPath = path.join(root, 'server/.env')
const prev = existsSync(serverEnvPath) ? readFileSync(serverEnvPath, 'utf8') : ''
const prevKey = /^PRIVATE_KEY=(.*)$/m.exec(prev)?.[1]

const serverEnv = `# Generated by scripts/sync-config.mjs from deployed_contracts.json (${network}). Re-run after each deploy.
PRIVATE_KEY=${prevKey ?? DEFAULT_KEY}
HTTP_RPC_URL=http://127.0.0.1:8545
WS_RPC_URL=ws://127.0.0.1:8545
CHAIN_ID=31337
INTERFOLD_ADDRESS=${addr('Interfold')}
CIPHERNODE_REGISTRY_ADDRESS=${addr('CiphernodeRegistryOwnable')}
FEE_TOKEN_ADDRESS=${addr('MockUSDC')}
E3_PROGRAM_ADDRESS=${addr('CkksSalaryE3Program')}
RELIN_KEY_DIR=${relinKeyDir}
SALARY_CAP=500000
E3_DURATION=${opt('--duration', '120')}
E3_COMMITTEE_SIZE=0
BIND_ADDR=0.0.0.0:${port}
DATABASE_PATH=database/server
ADMIN_KEY=
RUST_LOG=info,alloy=warn,e3_evm_helpers=warn
`
writeFileSync(serverEnvPath, serverEnv)
writeFileSync(
  path.join(root, 'client/.env'),
  `VITE_SURVEY_API=http://127.0.0.1:${port}\nVITE_CHAIN_ID=31337\nVITE_EXPLORER_TX=\n`,
)
console.log(`server/.env + client/.env synced: program ${addr('CkksSalaryE3Program')}, interfold ${addr('Interfold')}`)
