// SPDX-License-Identifier: LGPL-3.0-only
//
// This file is provided WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE.

import assert from 'node:assert/strict'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, unlinkSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import test from 'node:test'
import {
  CIRCUIT_GROUPS,
  CIRCUIT_PRESETS,
  NoirCircuitBuilder,
  configModuleFiles,
  generatedConfigDrift,
  requiredLbfvBinMarkers,
  requiredLbfvDistMarkers,
  syncGeneratedConfigModules,
} from './build-circuits'

function writeFiles(files: string[]): void {
  for (const file of files) {
    mkdirSync(join(file, '..'), { recursive: true })
    writeFileSync(file, file)
  }
}

test('synchronizes and verifies nested l-BFV config modules', () => {
  const root = mkdtempSync(join(tmpdir(), 'interfold-config-sync-'))
  const generated = join(root, 'generated')
  const committed = join(root, 'committed')
  const modules = ['mod.nr', 'threshold.nr', 'dkg.nr', 'lbfv/mod.nr', 'lbfv/crs.nr', 'lbfv/urs.nr']

  try {
    writeFiles(modules.map((file) => join(generated, file)))
    writeFiles([join(committed, 'stale.nr')])
    syncGeneratedConfigModules(generated, committed)

    assert.deepEqual(configModuleFiles(committed), modules.toSorted())
    assert.equal(generatedConfigDrift(generated, committed), null)
    assert.equal(existsSync(join(committed, 'stale.nr')), false)

    writeFileSync(join(committed, 'lbfv', 'crs.nr'), 'stale CRS')
    assert.equal(generatedConfigDrift(generated, committed), 'lbfv/crs.nr')
    unlinkSync(join(committed, 'lbfv', 'urs.nr'))
    assert.equal(generatedConfigDrift(generated, committed), 'file set')
  } finally {
    rmSync(root, { recursive: true, force: true })
  }
})

test('requires complete l-BFV row artifacts only for secure-16384', () => {
  const root = '/artifacts'
  assert.equal(requiredLbfvDistMarkers(root, CIRCUIT_PRESETS.SECURE_16384).length, 36)
  assert.equal(requiredLbfvBinMarkers(root, CIRCUIT_PRESETS.SECURE_16384).length, 28)
  assert.deepEqual(requiredLbfvDistMarkers(root, CIRCUIT_PRESETS.SECURE_8192), [])
  assert.deepEqual(requiredLbfvBinMarkers(root, CIRCUIT_PRESETS.INSECURE_512), [])
})

test('source hash covers compile-bearing Noir inputs but ignores active selectors', () => {
  const root = mkdtempSync(join(tmpdir(), 'interfold-source-hash-'))
  const sharedSource = join(root, 'circuits', 'lib', 'src', 'core', 'shared.nr')
  const sharedManifest = join(root, 'circuits', 'lib', 'Nargo.toml')
  const defaultConfig = join(root, 'circuits', 'lib', 'src', 'configs', 'default', 'mod.nr')
  const activeCommittee = join(root, 'circuits', 'lib', 'src', 'configs', 'committee', 'active.nr')
  const presetSource = join(root, 'circuits', 'lib', 'src', 'configs', 'insecure', 'threshold.nr')
  const committeeSource = join(root, 'circuits', 'lib', 'src', 'configs', 'committee', 'minimum', 'mod.nr')
  const microCommitteeSource = join(root, 'circuits', 'lib', 'src', 'configs', 'committee', 'micro', 'mod.nr')
  const smallCommitteeSource = join(root, 'circuits', 'lib', 'src', 'configs', 'committee', 'small', 'mod.nr')
  const workspaceManifest = join(root, 'circuits', 'bin', 'threshold', 'Nargo.toml')
  const defaultContent = (preset: string, maxCoefficients: number) =>
    [
      `// Auto-generated by build-circuits.ts for preset: ${preset}`,
      'pub use super::committee::active::{H, N_PARTIES, T};',
      `pub use super::${preset}::dkg;`,
      `pub use super::${preset}::threshold;`,
      `pub global MAX_MSG_NON_ZERO_COEFFS: u32 = ${maxCoefficients};`,
    ].join('\n')
  try {
    writeFiles([
      sharedSource,
      sharedManifest,
      join(root, 'circuits', 'lib', 'src', 'lib.nr'),
      join(root, 'circuits', 'lib', 'src', 'configs', 'mod.nr'),
      join(root, 'circuits', 'lib', 'src', 'configs', 'committee', 'mod.nr'),
      defaultConfig,
      activeCommittee,
      presetSource,
      committeeSource,
      microCommitteeSource,
      smallCommitteeSource,
      workspaceManifest,
      join(root, 'circuits', 'bin', 'threshold', 'example', 'Nargo.toml'),
      join(root, 'circuits', 'bin', 'threshold', 'example', 'src', 'main.nr'),
    ])
    writeFileSync(sharedSource, 'shared relation')
    writeFileSync(sharedManifest, 'shared manifest')
    writeFileSync(defaultConfig, defaultContent('insecure', 100))
    writeFileSync(activeCommittee, 'minimum selector')
    writeFileSync(presetSource, 'preset constants')
    writeFileSync(committeeSource, 'committee constants')
    writeFileSync(microCommitteeSource, 'micro committee constants')
    writeFileSync(smallCommitteeSource, 'small committee constants')
    writeFileSync(workspaceManifest, '[workspace]\nmembers = ["example"]')
    const builder = new NoirCircuitBuilder(root, {
      groups: [CIRCUIT_GROUPS.THRESHOLD],
      preset: CIRCUIT_PRESETS.INSECURE_512,
      committee: 'minimum',
    })

    const before = builder.computeSourceHash(CIRCUIT_PRESETS.INSECURE_512, 'minimum')
    writeFileSync(defaultConfig, defaultContent('secure_16384', 100))
    writeFileSync(activeCommittee, 'changed active committee')
    assert.equal(builder.computeSourceHash(CIRCUIT_PRESETS.INSECURE_512, 'minimum'), before)

    writeFileSync(defaultConfig, defaultContent('secure_16384', 101))
    assert.notEqual(builder.computeSourceHash(CIRCUIT_PRESETS.INSECURE_512, 'minimum'), before)
    writeFileSync(defaultConfig, defaultContent('secure_16384', 100))

    writeFileSync(sharedSource, 'changed shared relation')
    assert.notEqual(builder.computeSourceHash(CIRCUIT_PRESETS.INSECURE_512, 'minimum'), before)
    writeFileSync(sharedSource, 'shared relation')

    writeFileSync(sharedManifest, 'changed shared manifest')
    assert.notEqual(builder.computeSourceHash(CIRCUIT_PRESETS.INSECURE_512, 'minimum'), before)
    writeFileSync(sharedManifest, 'shared manifest')

    writeFileSync(workspaceManifest, '[workspace]\nmembers = []')
    assert.notEqual(builder.computeSourceHash(CIRCUIT_PRESETS.INSECURE_512, 'minimum'), before)
    writeFileSync(workspaceManifest, '[workspace]\nmembers = ["example"]')

    writeFileSync(presetSource, 'changed preset constants')
    assert.notEqual(builder.computeSourceHash(CIRCUIT_PRESETS.INSECURE_512, 'minimum'), before)
    writeFileSync(presetSource, 'preset constants')

    writeFileSync(committeeSource, 'changed committee constants')
    assert.notEqual(builder.computeSourceHash(CIRCUIT_PRESETS.INSECURE_512, 'minimum'), before)

    const archiveBefore = builder.computeSourceHash()
    writeFileSync(microCommitteeSource, 'changed micro committee constants')
    assert.notEqual(builder.computeSourceHash(), archiveBefore)
  } finally {
    rmSync(root, { recursive: true, force: true })
  }
})

function hydrationFixture(): {
  root: string
  outputDir: string
  hydrate: () => void
} {
  const root = mkdtempSync(join(tmpdir(), 'interfold-rlk-hydration-'))
  const bin = join(root, 'circuits', 'bin')
  const outputDir = join(root, 'dist', 'circuits')
  const pairDir = join(outputDir, CIRCUIT_PRESETS.SECURE_16384, 'minimum')

  for (const circuit of ['lbfv_pk_generation', 'lbfv_pk_aggregation', 'rlk_generation', 'rlk_aggregation']) {
    const circuitDir = join(bin, CIRCUIT_GROUPS.THRESHOLD, circuit)
    mkdirSync(circuitDir, { recursive: true })
    writeFileSync(join(circuitDir, 'Nargo.toml'), `[package]\nname = "${circuit}"\ntype = "bin"\n`)
    const targetDir = join(circuitDir, 'target')
    mkdirSync(targetDir, { recursive: true })
    writeFileSync(join(targetDir, `${circuit}.obsolete`), 'stale')
  }

  writeFiles([
    join(pairDir, 'default', CIRCUIT_GROUPS.DKG, 'pk', 'pk.json'),
    join(pairDir, 'default', CIRCUIT_GROUPS.THRESHOLD, 'pk_aggregation', 'pk_aggregation.json'),
    join(pairDir, 'default', CIRCUIT_GROUPS.AGGREGATION, 'dkg_aggregator', 'dkg_aggregator.json'),
    join(pairDir, 'default', CIRCUIT_GROUPS.AGGREGATION, 'decryption_aggregator', 'decryption_aggregator.json'),
    ...requiredLbfvDistMarkers(pairDir, CIRCUIT_PRESETS.SECURE_16384),
  ])

  const builder = new NoirCircuitBuilder(root, {
    groups: [CIRCUIT_GROUPS.THRESHOLD],
    outputDir,
    preset: CIRCUIT_PRESETS.SECURE_16384,
    committee: 'minimum',
  })
  const hydrate = () =>
    (
      builder as unknown as {
        hydrateBinFromDist(preset: typeof CIRCUIT_PRESETS.SECURE_16384, committee: 'minimum', sourceHash: string): void
      }
    ).hydrateBinFromDist(CIRCUIT_PRESETS.SECURE_16384, 'minimum', 'source-hash')

  return { root, outputDir, hydrate }
}

test('hydrates all l-BFV row targets and removes stale target artifacts', () => {
  const fixture = hydrationFixture()
  try {
    fixture.hydrate()
    for (const marker of requiredLbfvBinMarkers(join(fixture.root, 'circuits', 'bin'), CIRCUIT_PRESETS.SECURE_16384)) {
      assert.equal(existsSync(marker), true)
    }
    assert.equal(
      existsSync(join(fixture.root, 'circuits', 'bin', 'threshold', 'rlk_generation', 'target', 'rlk_generation.obsolete')),
      false,
    )
    assert.equal(JSON.parse(readFileSync(join(fixture.root, 'circuits', 'bin', '.active-preset.json'), 'utf8')).sourceHash, 'source-hash')
  } finally {
    rmSync(fixture.root, { recursive: true, force: true })
  }
})

test('rejects l-BFV hydration before writing a stamp when an artifact is missing', () => {
  const fixture = hydrationFixture()
  try {
    const missing = requiredLbfvDistMarkers(
      join(fixture.outputDir, CIRCUIT_PRESETS.SECURE_16384, 'minimum'),
      CIRCUIT_PRESETS.SECURE_16384,
    )[0]
    unlinkSync(missing)

    assert.throws(fixture.hydrate, /Cannot hydrate circuits\/bin: missing artifact/)
    assert.equal(existsSync(join(fixture.root, 'circuits', 'bin', '.active-preset.json')), false)
  } finally {
    rmSync(fixture.root, { recursive: true, force: true })
  }
})
