#!/usr/bin/env bash
set -euo pipefail

# Circuit lint is a release gate. A missing compiler is a failure unless a
# caller deliberately opts into a local diagnostic skip.
if ! command -v nargo >/dev/null 2>&1; then
    if [ "${ALLOW_SKIP_NARGO:-0}" = "1" ]; then
        echo "nargo command not found; skipping because ALLOW_SKIP_NARGO=1" >&2
        exit 0
    fi
    echo "Error: nargo command not found; no circuit checks ran" >&2
    exit 1
fi

# Ensure we're in the right directory.
cd circuits

# Directories to check
DIRS=(
  "lib"
  "bin/config"
  "bin/recursive_aggregation/c2ab_fold"
  "bin/recursive_aggregation/c3_fold"
  "bin/recursive_aggregation/c3_fold_kernel"
  "bin/recursive_aggregation/c6_fold"
  "bin/recursive_aggregation/c6_fold_kernel"
  "bin/recursive_aggregation/c3ab_fold"
  "bin/recursive_aggregation/c4ab_fold"
  "bin/recursive_aggregation/node_fold"
  "bin/recursive_aggregation/nodes_fold"
  "bin/recursive_aggregation/nodes_fold_kernel"
  "bin/recursive_aggregation/dkg_aggregator"
  "bin/recursive_aggregation/decryption_aggregator"
  "bin/dkg"
  "bin/threshold"
)

checked=0

for dir in "${DIRS[@]}"; do
    if [ ! -d "$dir" ]; then
        echo "Warning: Directory $dir does not exist, skipping..."
        continue
    fi
    
    echo "Checking $dir..."
    cd "$dir"
    
    # Checking circuit format.
    if ! (nargo fmt --check); then
        echo "Error: Circuit format check failed in $dir"
        exit 1
    fi
    
    # Check/validate the circuit libraries.
    if ! (nargo check); then
        echo "Error: Noir circuit check failed in $dir"
        exit 1
    fi

    checked=$((checked + 1))
    
    # Remove all Prover.toml files (they're generated by nargo and in .gitignore)
    find . -name "Prover.toml" -type f -delete
    
    cd - > /dev/null
done

if [ "$checked" -eq 0 ]; then
    echo "Error: no Noir circuit directories were checked" >&2
    exit 1
fi

echo "Noir circuits checked successfully ($checked packages)"
