#!/usr/bin/env bash
# SPDX-License-Identifier: LGPL-3.0-only
#
# Scaffolds the per-ParamSet C6-CKKS / C7-CKKS bin packages
# (share_decryption_ckks_ps{2,3,4}, decrypted_shares_aggregation_ckks_ps{2,3,4}) from
# the canonical ps0 packages: identical main.nr bodies, per-set config module.
# Idempotent. ParamSet 0 keeps its canonical package names.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BIN="$ROOT/circuits/bin/threshold"
for SET in 2 3 4 5; do
  for PAIR in "share_decryption_ckks:ckks_share_decryption" "decrypted_shares_aggregation_ckks:ckks_aggregation"; do
    BASE="${PAIR%%:*}"; MODULE="${PAIR##*:}"
    DIR="$BIN/${BASE}_ps${SET}"
    mkdir -p "$DIR/src"
    cat > "$DIR/Nargo.toml" <<EOF
[package]
name = "${BASE}_ps${SET}"
type = "bin"
authors = ["Gnosis Guild / Interfold"]

[dependencies]
lib = { path = "../../../lib" }
EOF
    {
      echo "// SPDX-License-Identifier: LGPL-3.0-only"
      echo "//"
      echo "// This file is provided WITHOUT ANY WARRANTY;"
      echo "// without even the implied warranty of MERCHANTABILITY"
      echo "// or FITNESS FOR A PARTICULAR PURPOSE."
      echo "//"
      echo "// ${BASE} for CKKS on-chain ParamSet ${SET} (level-0 shape). Same body as the"
      echo "// canonical ${BASE} package; the config module is ${MODULE}_ps${SET}."
      echo "// Generated by scripts/scaffold-ckks-c6c7-bins.sh — do not hand-edit."
      echo
      # Body of the canonical package minus its SPDX header, with the config
      # module swapped.
      sed -e '1,/^$/d' -e "s/lib::configs::${MODULE}::/lib::configs::${MODULE}_ps${SET}::/" \
        "$BIN/${BASE}/src/main.nr"
    } > "$DIR/src/main.nr"
    echo "scaffolded $DIR"
  done
done
