// SPDX-License-Identifier: LGPL-3.0-only
//
// This file is provided WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE.

//! Code generation for the CKKS user-data-encryption circuit: Prover.toml and
//! configs.nr (the `configs::ckks` module in the Noir lib).

use crate::circuits::computation::Computation;
use crate::threshold::user_data_encryption_ckks::circuit::CkksPreset;
use crate::threshold::user_data_encryption_ckks::circuit::UserDataEncryptionCkksCircuit;
use crate::threshold::user_data_encryption_ckks::circuit::UserDataEncryptionCkksCircuitData;
use crate::threshold::user_data_encryption_ckks::computation::{Configs, Inputs};
use crate::utils::join_display;
use crate::Circuit;
use crate::CircuitCodegen;
use crate::CircuitsErrors;
use crate::{Artifacts, CodegenConfigs, CodegenToml};

impl CircuitCodegen for UserDataEncryptionCkksCircuit {
    type Preset = CkksPreset;
    type Data = UserDataEncryptionCkksCircuitData;
    type Error = CircuitsErrors;

    fn codegen(&self, preset: Self::Preset, data: &Self::Data) -> Result<Artifacts, Self::Error> {
        let inputs = Inputs::compute(preset.clone(), data)?;
        let configs = Configs::compute(preset.clone(), &())?;

        let toml = generate_toml(inputs)?;
        let configs = generate_configs(&preset, &configs);

        Ok(Artifacts { toml, configs })
    }
}

pub fn generate_toml(inputs: Inputs) -> Result<CodegenToml, CircuitsErrors> {
    let json = inputs.to_json().map_err(CircuitsErrors::SerdeJson)?;

    Ok(toml::to_string(&json)?)
}

pub fn generate_configs(preset: &CkksPreset, configs: &Configs) -> CodegenConfigs {
    let prefix = <UserDataEncryptionCkksCircuit as Circuit>::PREFIX;

    let qis_str = join_display(&configs.moduli, ", ");
    let r1_low_bounds_str = join_display(&configs.bounds.r1_low_bounds, ", ");
    let r1_up_bounds_str = join_display(&configs.bounds.r1_up_bounds, ", ");
    let r2_bounds_str = join_display(&configs.bounds.r2_bounds, ", ");
    let p1_bounds_str = join_display(&configs.bounds.p1_bounds, ", ");
    let p2_bounds_str = join_display(&configs.bounds.p2_bounds, ", ");

    format!(
        r#"// SPDX-License-Identifier: LGPL-3.0-only
//
// This file is provided WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE.
//
// Auto-generated by e3-zk-helpers user_data_encryption_ckks codegen.
// Do not hand-edit; regenerate-and-diff is enforced by
// `test_checked_in_configs_match_codegen`.
// CKKS dev preset: N={}, L={}, scale=2^{}, input_bound={}.

use crate::core::threshold::user_data_encryption_ckks_ct0::Configs as UserDataEncryptionCkksCt0Configs;
use crate::core::threshold::user_data_encryption_ct1::Configs as UserDataEncryptionCt1Configs;

// Global configs for the CKKS User Data Encryption circuit
pub global CKKS_N: u32 = {};
pub global CKKS_L: u32 = {};
pub global CKKS_QIS: [Field; CKKS_L] = [{}];

pub global {}_BIT_PK: u32 = {};
pub global {}_BIT_CT: u32 = {};
pub global {}_BIT_U: u32 = {};
pub global {}_BIT_E0: u32 = {};
pub global {}_BIT_M: u32 = {};
pub global {}_BIT_R1: u32 = {};
pub global {}_BIT_R2: u32 = {};
pub global {}_BIT_E1: u32 = {};
pub global {}_BIT_P1: u32 = {};
pub global {}_BIT_P2: u32 = {};

pub global {}_E0_BOUND: Field = {};
pub global {}_U_BOUND: Field = {};
pub global {}_M_BOUND: Field = {};
pub global {}_R1_LOW_BOUNDS: [Field; CKKS_L] = [{}];
pub global {}_R1_UP_BOUNDS: [Field; CKKS_L] = [{}];
pub global {}_R2_BOUNDS: [Field; CKKS_L] = [{}];
pub global {}_E1_BOUND: Field = {};
pub global {}_P1_BOUNDS: [Field; CKKS_L] = [{}];
pub global {}_P2_BOUNDS: [Field; CKKS_L] = [{}];

pub global {}_CT0_CONFIGS: UserDataEncryptionCkksCt0Configs<CKKS_N, CKKS_L>
     = UserDataEncryptionCkksCt0Configs::new(
        CKKS_QIS,
        {}_E0_BOUND,
        {}_U_BOUND,
        {}_M_BOUND,
        {}_R1_LOW_BOUNDS,
        {}_R1_UP_BOUNDS,
        {}_R2_BOUNDS,
    );

// ct1 leg (P3-style): ct1 = pk1*u + e1. Reuses the scheme-generic
// `UserDataEncryptionCt1` core with CKKS moduli and bounds.
pub global {}_CT1_CONFIGS: UserDataEncryptionCt1Configs<CKKS_N, CKKS_L> = UserDataEncryptionCt1Configs::new(
    CKKS_QIS,
    {}_E1_BOUND,
    {}_U_BOUND,
    {}_P1_BOUNDS,
    {}_P2_BOUNDS,
);
"#,
        configs.n,
        configs.l,
        preset.params.scale().log2() as u32,
        preset.input_bound,
        configs.n,
        configs.l,
        qis_str,
        prefix,
        configs.bits.pk_bit,
        prefix,
        configs.bits.ct_bit,
        prefix,
        configs.bits.u_bit,
        prefix,
        configs.bits.e0_bit,
        prefix,
        configs.bits.m_bit,
        prefix,
        configs.bits.r1_bit,
        prefix,
        configs.bits.r2_bit,
        prefix,
        configs.bits.e1_bit,
        prefix,
        configs.bits.p1_bit,
        prefix,
        configs.bits.p2_bit,
        prefix,
        configs.bounds.e0_bound,
        prefix,
        configs.bounds.u_bound,
        prefix,
        configs.bounds.m_bound,
        prefix,
        r1_low_bounds_str,
        prefix,
        r1_up_bounds_str,
        prefix,
        r2_bounds_str,
        prefix,
        configs.bounds.e1_bound,
        prefix,
        p1_bounds_str,
        prefix,
        p2_bounds_str,
        prefix,
        prefix,
        prefix,
        prefix,
        prefix,
        prefix,
        prefix,
        prefix,
        prefix,
        prefix,
        prefix,
        prefix,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::threshold::user_data_encryption_ckks::circuit::insecure_512_ckks;
    use fhe::ckks::{CkksPublicKey, CkksSecretKey};

    #[test]
    fn test_toml_generation_and_structure() {
        let mut rng = rand::rng();
        let preset = insecure_512_ckks().unwrap();
        let sk = CkksSecretKey::random(&preset.params, &mut rng);
        let pk = CkksPublicKey::new(&sk, &mut rng).unwrap();

        let data = UserDataEncryptionCkksCircuitData {
            public_key: pk,
            values: vec![3.75, -12.5],
        };

        let artifacts = UserDataEncryptionCkksCircuit
            .codegen(preset, &data)
            .unwrap();

        let parsed: toml::Value = artifacts.toml.parse().unwrap();
        for key in ["pk0is", "ct0is", "u", "e0", "m", "r1is", "r2is"] {
            assert!(
                parsed.get(key).is_some(),
                "missing key {key} in Prover.toml"
            );
        }

        assert!(artifacts.configs.contains("CKKS_N: u32 = 512"));
        assert!(artifacts
            .configs
            .contains("USER_DATA_ENCRYPTION_CKKS_CT0_CONFIGS"));
    }

    /// Regenerate-and-diff guard: the checked-in `configs/ckks.nr` in the Noir
    /// lib must match what codegen produces for the dev preset.
    #[test]
    fn test_checked_in_configs_match_codegen() {
        let preset = insecure_512_ckks().unwrap();
        let configs = Configs::compute(preset.clone(), &()).unwrap();
        let generated = generate_configs(&preset, &configs);

        let path = concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../circuits/lib/src/configs/ckks.nr"
        );
        let checked_in = std::fs::read_to_string(path)
            .expect("circuits/lib/src/configs/ckks.nr missing; write it from codegen output");

        assert_eq!(
            checked_in, generated,
            "configs/ckks.nr drifted from codegen; regenerate it"
        );
    }
}
