#!/usr/bin/env bash
# SPDX-License-Identifier: LGPL-3.0-only
#
# Deploy the Interfold stack with mocks (which includes CkksMatchingE3Program + its three Honk
# verifiers and ParamSet 5), sync tests/integration/interfold.config.yaml for the ciphernodes,
# and write server/.env from deployed_contracts.json (CRISP `crisp_deploy.sh` +
# `apply_crisp_dev_config_to_server_env`).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ROOT="$(cd "$APP_ROOT/../.." && pwd)"
CONTRACTS="$ROOT/packages/interfold-contracts"

until curl -sf -X POST http://localhost:8545 -H 'Content-Type: application/json' \
  -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' > /dev/null; do
  sleep 1
done

echo "Deploying Interfold + mocks + CkksMatchingE3Program..."
export PRIVATE_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
(cd "$ROOT" && pnpm evm:clean && pnpm evm:deploy)
(cd "$CONTRACTS" && pnpm utils:sync-integration-config)

addr() { python3 -c "import json,sys; d=json.load(open('$CONTRACTS/deployed_contracts.json')); print(d['localhost']['$1']['address'])"; }

INTERFOLD_ADDRESS=$(addr Interfold)
PROGRAM_ADDRESS=$(addr CkksMatchingE3Program)
REGISTRY_ADDRESS=$(addr CiphernodeRegistryOwnable)
FEE_TOKEN_ADDRESS=$(addr MockUSDC)

# deployMocks deploys CkksMatchingE3Program but only registers the Mock/Ps3 CKKS programs on
# Interfold; register the matching gate so `request()` through it is accepted.
(cd "$CONTRACTS" && npx hardhat interfold:enableE3 --e3-address "$PROGRAM_ADDRESS" --network localhost)

cat > "$APP_ROOT/server/.env" <<EOF
# Generated by scripts/deploy.sh — round-opener key (anvil #0). Submissions are NOT signed with it.
PRIVATE_KEY=$PRIVATE_KEY
HTTP_RPC_URL=http://127.0.0.1:8545
WS_RPC_URL=ws://127.0.0.1:8545
CHAIN_ID=31337
INTERFOLD_ADDRESS=$INTERFOLD_ADDRESS
E3_PROGRAM_ADDRESS=$PROGRAM_ADDRESS
CIPHERNODE_REGISTRY_ADDRESS=$REGISTRY_ADDRESS
FEE_TOKEN_ADDRESS=$FEE_TOKEN_ADDRESS
E3_DURATION=${E3_DURATION:-300}
E3_COMMITTEE_SIZE=0
# Where the ciphernodes write the joint relin key the program needs for the
# one ct×ct product (`<dir>/<chain>:<e3>/rlk_level_0.bin`).
# Must match CKKS_RELIN_KEY_DIR exported for the nodes in dev_cipher.sh.
RELIN_KEY_DIR=${CKKS_RELIN_KEY_DIR:-/tmp/ckks-relin-keys}
BIND_ADDR=0.0.0.0:${SERVER_PORT:-8093}
EOF
cp "$APP_ROOT/server/.env" "$APP_ROOT/server/.env.deployed"
echo "server/.env written: program $PROGRAM_ADDRESS, interfold $INTERFOLD_ADDRESS"
