// One-off: generate configs fragment + Prover.toml for the CKKS decrypted
// shares aggregation bin circuit from a real threshold pipeline (T=1 to
// match the active `minimum` committee).
fn main() {
    use e3_zk_helpers::circuits::codegen::CircuitCodegen;
    use e3_zk_helpers::threshold::decrypted_shares_aggregation_ckks::{
        DecryptedSharesAggregationCkksCircuit, DecryptedSharesAggregationCkksCircuitData,
    };
    use fhe::trckks::TRCKKS;

    let mut rng = rand::rng();
    let preset = e3_zk_helpers::threshold::user_data_encryption_ckks::insecure_512_ckks().unwrap();
    let params = preset.params.clone();

    // Committee shape must match the active Noir committee: minimum = (3, 1).
    let (n_parties, threshold) = (3usize, 1usize);
    let trckks = TRCKKS::new(n_parties, threshold, params.clone()).unwrap();

    let sk = fhe::ckks::CkksSecretKey::random(&params, &mut rng);
    let pk = fhe::ckks::CkksPublicKey::new(&sk, &mut rng).unwrap();

    let sk_poly = trckks.coeffs_to_poly(sk.coeffs.as_ref()).unwrap();
    let sk_mats = trckks
        .generate_secret_shares_from_poly(sk_poly, &mut rng)
        .unwrap();
    let es = trckks.generate_smudging_error(20, &mut rng).unwrap();
    let es_poly = trckks.smudging_to_poly(&es).unwrap();
    let es_mats = trckks
        .generate_secret_shares_from_poly(es_poly, &mut rng)
        .unwrap();

    let encoder = fhe::ckks::CkksEncoder::new(&params);
    let pt = encoder.encode(&[42.5, -17.25], 0).unwrap();
    let ct = pk.try_encrypt(&pt, &mut rng).unwrap();

    let parties: Vec<usize> = vec![1, 3];
    let mut d_share_polys = Vec::new();
    for &j in &parties {
        let sk_share = trckks.share_row_to_poly(&sk_mats, j - 1).unwrap();
        let es_share = trckks.share_row_to_poly(&es_mats, j - 1).unwrap();
        let d = trckks
            .decryption_share(&ct, sk_share.into_ntt(), es_share)
            .unwrap();
        d_share_polys.push(d);
    }

    let data = DecryptedSharesAggregationCkksCircuitData {
        threshold,
        d_share_polys,
        reconstructing_parties: parties,
    };

    let artifacts = DecryptedSharesAggregationCkksCircuit
        .codegen(preset, &data)
        .unwrap();

    std::fs::write(
        "circuits/bin/threshold/decrypted_shares_aggregation_ckks/Prover.toml",
        &artifacts.toml,
    )
    .unwrap();
    std::fs::write(
        "circuits/lib/src/configs/ckks_aggregation.nr",
        format!(
            "// SPDX-License-Identifier: LGPL-3.0-only\n//\n// This file is provided WITHOUT ANY WARRANTY;\n// without even the implied warranty of MERCHANTABILITY\n// or FITNESS FOR A PARTICULAR PURPOSE.\n//\n// Auto-generated by e3-zk-helpers decrypted_shares_aggregation_ckks codegen\n// (example gen_ckks_agg_prover). Do not hand-edit.\n\n{}",
            &artifacts.configs
        ),
    )
    .unwrap();
    println!(
        "Prover.toml ({} bytes) + configs fragment written",
        artifacts.toml.len()
    );
}
