// One-off: generate configs + Prover.toml for the CKKS DKG share-computation
// (C2a) bin circuit from real CKKS witnesses. The C2a circuit itself is
// scheme-agnostic; only the constants (QIS, parity matrix, bit widths)
// change. Committee: minimum (3, 1) to match the active Noir committee.
fn main() {
    use e3_zk_helpers::circuits::computation::Computation as _;
    use e3_zk_helpers::circuits::dkg::share_computation::utils::compute_parity_matrix;
    use e3_zk_helpers::circuits::dkg::share_computation_ckks::{
        compute_ckks_share_inputs, generate_ckks_sk_share_data, CkksDkgCommittee,
    };
    use e3_zk_helpers::utils::bigint_to_field;
    use num_bigint::BigInt;

    let preset = e3_zk_helpers::threshold::user_data_encryption_ckks::insecure_512_ckks().unwrap();
    let committee = CkksDkgCommittee { n: 3, threshold: 1 };

    let data = generate_ckks_sk_share_data(&preset, committee).unwrap();
    let inputs = compute_ckks_share_inputs(&preset, &data).unwrap();

    // Prover.toml
    let json = inputs.to_json().unwrap();
    let toml = toml::to_string(&json).unwrap();
    std::fs::write(
        "circuits/bin/dkg/sk_share_computation_ckks/Prover.toml",
        &toml,
    )
    .unwrap();

    // Configs fragment: QIS + parity matrix over the CKKS moduli.
    let moduli = preset.params.moduli();
    let qis_str = moduli
        .iter()
        .map(|q| q.to_string())
        .collect::<Vec<_>>()
        .join(", ");
    let bit_share = moduli
        .iter()
        .map(|&q| e3_zk_helpers::calculate_bit_width(BigInt::from(q - 1)))
        .max()
        .unwrap();

    let parity = compute_parity_matrix(moduli, committee.n, committee.threshold).unwrap();
    let parity_strings: Vec<String> = parity
        .iter()
        .map(|h_mod| {
            let rows: Vec<String> = h_mod
                .data()
                .iter()
                .map(|row| {
                    let vals: Vec<String> = row
                        .iter()
                        .map(|v| bigint_to_field(&BigInt::from(v.clone())).to_string())
                        .collect();
                    format!("[{}]", vals.join(", "))
                })
                .collect();
            format!("[\n        {}]", rows.join(",\n        "))
        })
        .collect();

    let configs = format!(
        "// SPDX-License-Identifier: LGPL-3.0-only\n//\n// This file is provided WITHOUT ANY WARRANTY;\n// without even the implied warranty of MERCHANTABILITY\n// or FITNESS FOR A PARTICULAR PURPOSE.\n//\n// Auto-generated by e3-zk-helpers (example gen_ckks_dkg_prover).\n// CKKS DKG (C2a/C2b) constants: same circuits as BFV DKG, CKKS moduli.\n// Committee: minimum (3, 1). Do not hand-edit.\n\nuse crate::core::dkg::share_computation::Configs as ShareComputationConfigs;\n\npub global CKKS_DKG_N: u32 = {};\npub global CKKS_DKG_L: u32 = {};\npub global CKKS_DKG_QIS: [Field; CKKS_DKG_L] = [{}];\npub global CKKS_DKG_N_PARTIES: u32 = {};\npub global CKKS_DKG_T: u32 = {};\n\npub global CKKS_SHARE_COMPUTATION_BIT_SHARE: u32 = {};\npub global CKKS_SHARE_COMPUTATION_SK_BIT_SECRET: u32 = 1;\n\npub global CKKS_SHARE_COMPUTATION_SK_CONFIGS: ShareComputationConfigs<CKKS_DKG_L> =\n    ShareComputationConfigs::new(CKKS_DKG_QIS);\n\npub global CKKS_PARITY_MATRIX: [[[Field; CKKS_DKG_N_PARTIES + 1]; CKKS_DKG_N_PARTIES - CKKS_DKG_T]; CKKS_DKG_L] = [\n    {}];\n",
        preset.params.degree(),
        moduli.len(),
        qis_str,
        committee.n,
        committee.threshold,
        bit_share,
        parity_strings.join(",\n    "),
    );
    std::fs::write("circuits/lib/src/configs/ckks_dkg.nr", configs).unwrap();

    println!("Prover.toml ({} bytes) + ckks_dkg.nr written", toml.len());
}
