// SPDX-License-Identifier: LGPL-3.0-only
//
// This file is provided WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE.

//! Federated-averaging app (ParamSet 5) tooling:
//!
//! - `configs`: emit `circuits/lib/src/configs/ckks_fedavg_ps5.nr` from
//!   codegen (the Greco `ckks_ps5.nr` is shared with the other ParamSet-5
//!   apps and generated by `gen_ckks_configs_ps`).
//! - `prover <out-dir> [pubkey.bin]`: generate real FIVE-leg witnesses
//!   (Greco ct0/ct1 for the gradient ciphertext, Greco ct0/ct1 for the
//!   count ciphertext, the fedavg validity leg) from TWO encryptions, plus
//!   a `meta.json` the fixture builder reads. Prover.toml files land in
//!   the matching `circuits/bin/threshold/<pkg>/` directories; the Greco
//!   ps5 packages are SHARED with the other ParamSet-5 apps, so their
//!   witnesses are written as `Prover_fedavg_grad.toml` /
//!   `Prover_fedavg_count.toml` (never `Prover.toml`) and the fixture
//!   script selects them with `nargo execute -p`.
//! - `prover-bad <out-dir>`: same, but with an update whose squared norm
//!   EXCEEDS the round bound — the native pre-check is bypassed so the
//!   circuit's own norm check is what rejects it (proving-failure fixture).
//!
//! Usage: cargo run --release -p e3-zk-helpers --example gen_ckks_fedavg_prover -- <configs|prover|prover-bad> ...

use e3_zk_helpers::threshold::ckks_app_validity::{address_to_biguint, field_word_hex};
use e3_zk_helpers::threshold::ckks_fedavg_validity::{
    build_fedavg_submission, compute_m_commitment, fedavg_greco_inputs_with_rng, fedavg_layouts,
    fedavg_preset, generate_fedavg_configs, norm_bound_fixed_point, public_input_words,
    FedAvgConfigs, FedAvgInputs, FixedPointUpdate, FEDAVG_CIRCUIT_PACKAGE, FEDAVG_D,
    FEDAVG_PARAM_SET,
};
use e3_zk_helpers::threshold::user_data_encryption_ckks::generate_toml;
use fhe::ckks::{CkksPublicKey, CkksSecretKey};
use fhe_traits::DeserializeParametrized;

/// Alice (hardhat account #0): the fixture client.
const ALICE: &str = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266";
/// The demo update (`|g_j| <= 1`, squared norm ≈ 2.09).
const DEMO_G: [f64; FEDAVG_D] = [0.5, -0.25, 0.75, -1.0, 0.125, 0.0, -0.5, 0.3];
/// The demo PRIVATE sample count.
const DEMO_COUNT: u32 = 137;
/// The round's public squared-norm bound.
const DEMO_BOUND: f64 = 2.5;
/// Alice's slot index in the fixture round.
const DEMO_INDEX: u32 = 0;

fn write_configs() {
    let preset = fedavg_preset().unwrap();
    let configs = FedAvgConfigs::compute(&preset).unwrap();
    let path = format!("circuits/lib/src/configs/ckks_fedavg_ps{FEDAVG_PARAM_SET}.nr");
    std::fs::write(&path, generate_fedavg_configs(&configs)).unwrap();
    println!("written {path}");
}

fn load_or_generate_pk(path: Option<&String>) -> CkksPublicKey {
    let preset = fedavg_preset().unwrap();
    match path {
        Some(path) => {
            let bytes = std::fs::read(path).unwrap();
            CkksPublicKey::from_bytes(&bytes, &preset.params).unwrap()
        }
        None => {
            let mut rng = rand::rng();
            let sk = CkksSecretKey::random(&preset.params, &mut rng);
            CkksPublicKey::new(&sk, &mut rng).unwrap()
        }
    }
}

struct Legs<'a> {
    grad_toml: &'a str,
    grad_ct: &'a [u8],
    count_toml: &'a str,
    count_ct: &'a [u8],
    inputs: &'a FedAvgInputs,
}

fn write_legs(out_dir: &std::path::Path, legs: Legs<'_>) {
    let configs = FedAvgConfigs::compute(&fedavg_preset().unwrap()).unwrap();
    let inputs = legs.inputs;
    let m_c_g = compute_m_commitment(&inputs.m_grad, configs.m_bit);
    let m_c_c = compute_m_commitment(&inputs.m_count, configs.m_bit);
    let suffix = format!("_ps{FEDAVG_PARAM_SET}");
    let root = concat!(env!("CARGO_MANIFEST_DIR"), "/../../circuits/bin/threshold");
    for leg in ["ct0", "ct1"] {
        let dir = format!("{root}/user_data_encryption_ckks_{leg}{suffix}");
        std::fs::write(format!("{dir}/Prover_fedavg_grad.toml"), legs.grad_toml).unwrap();
        std::fs::write(format!("{dir}/Prover_fedavg_count.toml"), legs.count_toml).unwrap();
    }
    let app_dir = format!("{root}/{FEDAVG_CIRCUIT_PACKAGE}");
    std::fs::write(format!("{app_dir}/Prover.toml"), inputs.to_toml().unwrap()).unwrap();

    std::fs::create_dir_all(out_dir).unwrap();
    std::fs::write(out_dir.join("ciphertext_g.bin"), legs.grad_ct).unwrap();
    std::fs::write(out_dir.join("ciphertext_c.bin"), legs.count_ct).unwrap();
    let words = public_input_words(inputs, configs.m_bit);
    let meta = serde_json::json!({
        "app": FEDAVG_CIRCUIT_PACKAGE,
        "paramSet": FEDAVG_PARAM_SET,
        "d": FEDAVG_D,
        "index": inputs.index,
        "count": inputs.count,
        "update": inputs.update.entries,
        "updateF64": inputs.update.to_f64(),
        "squaredNorm": inputs.update.squared_norm(),
        "squaredNormF64": inputs.update.squared_norm_f64(),
        "normBound": inputs.norm_bound,
        "normBoundWord": words[0],
        "ciphertextGHex": format!("0x{}", hex::encode(legs.grad_ct)),
        "ciphertextCHex": format!("0x{}", hex::encode(legs.count_ct)),
        "mCommitmentG": field_word_hex(&m_c_g),
        "mCommitmentC": field_word_hex(&m_c_c),
        "appPublicInputs": words,
        "extra": {
            "address": ALICE,
            "addressWord": words[1],
            "indexWord": words[2],
        },
    });
    std::fs::write(
        out_dir.join("meta.json"),
        serde_json::to_string_pretty(&meta).unwrap(),
    )
    .unwrap();
    println!(
        "{FEDAVG_CIRCUIT_PACKAGE}: Prover_fedavg_grad.toml + Prover_fedavg_count.toml written for ct0/ct1{suffix}; fedavg leg Prover.toml; meta at {}",
        out_dir.join("meta.json").display()
    );
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let update = FixedPointUpdate::from_f64(&DEMO_G);
    let bound = norm_bound_fixed_point(DEMO_BOUND);
    match args.get(1).map(String::as_str) {
        Some("configs") => write_configs(),
        Some("prover") => {
            let out_dir = std::path::PathBuf::from(args.get(2).expect("out-dir"));
            let pk = load_or_generate_pk(args.get(3));
            let alice = address_to_biguint(ALICE).unwrap();
            let sub =
                build_fedavg_submission(pk, update, DEMO_COUNT, bound, alice, DEMO_INDEX).unwrap();
            write_legs(
                &out_dir,
                Legs {
                    grad_toml: &sub.gradient.greco_toml,
                    grad_ct: &sub.gradient.ciphertext,
                    count_toml: &sub.count.greco_toml,
                    count_ct: &sub.count.ciphertext,
                    inputs: &sub.fedavg_inputs,
                },
            );
        }
        Some("prover-bad") => {
            // Squared norm 2.09 declared against a bound of 1.0: the ONLY
            // thing rejecting it is the circuit's `Σ G_j² <= norm_bound`.
            let out_dir = std::path::PathBuf::from(args.get(2).expect("out-dir"));
            let pk = load_or_generate_pk(args.get(3));
            let alice = address_to_biguint(ALICE).unwrap();
            let configs = FedAvgConfigs::compute(&fedavg_preset().unwrap()).unwrap();
            let (gv, cv) = fedavg_layouts(&update, DEMO_COUNT, configs.n);
            let mut rng = rand::rng();
            let greco_g = fedavg_greco_inputs_with_rng(&pk, &gv, &mut rng).unwrap();
            let greco_c = fedavg_greco_inputs_with_rng(&pk, &cv, &mut rng).unwrap();
            let inputs = FedAvgInputs {
                m_grad: greco_g.m.clone(),
                m_count: greco_c.m.clone(),
                update,
                count: DEMO_COUNT,
                norm_bound: norm_bound_fixed_point(1.0),
                address: alice,
                index: DEMO_INDEX,
            };
            let grad_ct = greco_g.ciphertext.clone();
            let count_ct = greco_c.ciphertext.clone();
            let grad_toml = generate_toml(greco_g).unwrap();
            let count_toml = generate_toml(greco_c).unwrap();
            write_legs(
                &out_dir,
                Legs {
                    grad_toml: &grad_toml,
                    grad_ct: &grad_ct,
                    count_toml: &count_toml,
                    count_ct: &count_ct,
                    inputs: &inputs,
                },
            );
        }
        _ => panic!(
            "usage: gen_ckks_fedavg_prover <configs|prover|prover-bad> [out-dir] [pubkey.bin]"
        ),
    }
}
