// SPDX-License-Identifier: LGPL-3.0-only
//
// This file is provided WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE.

//! Emits SIZING-ONLY bin packages for the committee-side CKKS proof
//! circuits at a chosen ring degree `N` and fixed limb count `L`
//! (`ckks_preset_scaling`), each with a real witness from the production
//! builder, so `scripts/ckks-prove-package.sh` can measure how
//! constraints / compile RAM / prove time grow with `N`.
//!
//! Run (from the repo root):
//!   cargo run --release -p e3-zk-helpers --example gen_ckks_scale_provers -- \
//!     --n 1024 [--l 3] [--special 1] [--circuits c1,c2a,c2b,c6,c7,c8]
//!
//! Writes `circuits/bin/ckks_scaling/<pkg>_scale_n<N>/{Nargo.toml,Prover.toml,src/main.nr,src/configs.nr}`
//! and refreshes the `circuits/bin/ckks_scaling/Nargo.toml` workspace
//! member list. Nothing here is consumed by the node; the packages are
//! measurement fixtures for `docs/THRESHOLD_CKKS_PROVEN_PIPELINE_AT_SECURE_N.md`.

use e3_polynomial::CrtPolynomial;
use e3_zk_helpers::circuits::commitments::{
    compute_share_computation_e_sm_commitment, compute_share_computation_sk_commitment,
};
use e3_zk_helpers::circuits::computation::{Computation, DkgInputType};
use e3_zk_helpers::circuits::dkg::share_computation::utils::compute_parity_matrix;
use e3_zk_helpers::circuits::dkg::share_computation::ShareComputationCircuitData;
use e3_zk_helpers::circuits::dkg::share_computation_ckks::{
    compute_ckks_share_inputs, generate_ckks_sk_share_data, CkksDkgCommittee,
};
use e3_zk_helpers::circuits::threshold::ckks_scaling::{
    ckks_preset_scaling, scaling_package_suffix,
};
use e3_zk_helpers::circuits::threshold::user_data_encryption_ckks::CkksPreset;
use e3_zk_helpers::math::array2_u64_to_bigint;
use e3_zk_helpers::utils::{bigint_to_field, calculate_bit_width};
use fhe::ckks::{CkksEncoder, CkksPublicKey, CkksSecretKey};
use fhe::trckks::{CkksCrp, TRCKKS};
use num_bigint::BigInt;
use std::path::{Path, PathBuf};

const HEADER: &str = "// SPDX-License-Identifier: LGPL-3.0-only\n//\n// This file is provided WITHOUT ANY WARRANTY;\n// without even the implied warranty of MERCHANTABILITY\n// or FITNESS FOR A PARTICULAR PURPOSE.\n//\n// SIZING FIXTURE (not a production shape). Generated by\n// `cargo run -p e3-zk-helpers --example gen_ckks_scale_provers`.\n// Do not hand-edit.\n";

struct Args {
    n: usize,
    l: usize,
    special: usize,
    circuits: Vec<String>,
    out_dir: PathBuf,
}

fn parse_args() -> Result<Args, Box<dyn std::error::Error>> {
    let args: Vec<String> = std::env::args().collect();
    let arg = |name: &str| {
        args.iter()
            .position(|a| a == name)
            .and_then(|i| args.get(i + 1))
            .cloned()
    };
    let root = PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/../.."));
    Ok(Args {
        n: arg("--n").unwrap_or_else(|| "1024".into()).parse()?,
        l: arg("--l").unwrap_or_else(|| "3".into()).parse()?,
        special: arg("--special").unwrap_or_else(|| "1".into()).parse()?,
        circuits: arg("--circuits")
            .unwrap_or_else(|| "c1,c2a,c2b,c6,c7,c8".into())
            .split(',')
            .map(|s| s.trim().to_string())
            .collect(),
        out_dir: arg("--out-dir")
            .map(PathBuf::from)
            .unwrap_or_else(|| root.join("circuits/bin/ckks_scaling")),
    })
}

fn write_package(
    dir: &Path,
    name: &str,
    main_nr: &str,
    configs_nr: &str,
    prover_toml: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    std::fs::create_dir_all(dir.join("src"))?;
    std::fs::write(
        dir.join("Nargo.toml"),
        format!(
            "[package]\nname = \"{name}\"\ntype = \"bin\"\nauthors = [\"Gnosis Guild / Interfold\"]\n\n[dependencies]\nlib = {{ path = \"../../../lib\" }}\n"
        ),
    )?;
    std::fs::write(dir.join("src/main.nr"), main_nr)?;
    std::fs::write(dir.join("src/configs.nr"), configs_nr)?;
    std::fs::write(dir.join("Prover.toml"), prover_toml)?;
    println!(
        "  wrote {} ({} bytes of Prover.toml)",
        dir.display(),
        prover_toml.len()
    );
    Ok(())
}

/// Turn a generated `circuits/lib/src/configs/*.nr` body into a package-local
/// `src/configs.nr` module: the lib config files import `crate::core::…`,
/// which becomes `lib::core::…` inside a bin package.
fn localize(nr: String) -> String {
    let body = nr.replace("use crate::", "use lib::");
    // Drop the lib file's own SPDX header; the sizing header replaces it.
    let start = body.find("use lib::").unwrap_or(0);
    format!("{HEADER}\n{}", &body[start..])
}

fn refresh_workspace(out_dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let mut members: Vec<String> = std::fs::read_dir(out_dir)?
        .filter_map(|e| e.ok())
        .filter(|e| e.path().join("Nargo.toml").is_file())
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .collect();
    members.sort();
    let list = members
        .iter()
        .map(|m| format!("    \"{m}\","))
        .collect::<Vec<_>>()
        .join("\n");
    std::fs::write(
        out_dir.join("Nargo.toml"),
        format!("[workspace]\nmembers = [\n{list}\n]\n"),
    )?;
    Ok(())
}

// ----------------------------------------------------------------------------
// C1-CKKS (pk share well-formedness)
// ----------------------------------------------------------------------------
fn gen_c1(preset: &CkksPreset, args: &Args) -> Result<(), Box<dyn std::error::Error>> {
    use e3_zk_helpers::circuits::threshold::pk_generation_ckks::{
        compute_pk_share, generate_configs_nr, sample_pk_share_error, CkksPkGenerationData,
        Configs, Inputs, CKKS_PK_GENERATION_SMUDGING_BITS,
    };
    let params = preset.params.clone();
    let mut rng = rand::rng();
    let crp = CkksCrp::from_seed(&params, [42u8; 32])?;
    let sk = CkksSecretKey::random(&params, &mut rng);
    let e = sample_pk_share_error(&params, &mut rng);
    let pk_share = compute_pk_share(&params, &crp, sk.coeffs.as_ref(), &e)?;
    let trckks = TRCKKS::new(3, 1, params.clone())?;
    let e_sm: Vec<i64> = trckks
        .generate_smudging_error(CKKS_PK_GENERATION_SMUDGING_BITS, &mut rng)?
        .iter()
        .map(i64::try_from)
        .collect::<Result<_, _>>()?;
    let data = CkksPkGenerationData {
        crp,
        pk_share,
        sk_coeffs: sk.coeffs.to_vec(),
        e_coeffs: e,
        e_sm_coeffs: e_sm,
    };
    let configs = Configs::compute(preset.clone(), &())?;
    let inputs = Inputs::compute(preset.clone(), &data)?;
    let toml_str = toml::to_string(&inputs.to_json()?)?;
    let name = format!("pk_generation_ckks{}", scaling_package_suffix(args.n));
    let main = format!(
        r#"{HEADER}
mod configs;

use configs::{{
    PK_GENERATION_CKKS_BIT_E_SM, PK_GENERATION_CKKS_BIT_EEK, PK_GENERATION_CKKS_BIT_PK,
    PK_GENERATION_CKKS_BIT_R1, PK_GENERATION_CKKS_BIT_R2, PK_GENERATION_CKKS_BIT_SK,
    PK_GENERATION_CKKS_CONFIGS, PK_GENERATION_CKKS_L, PK_GENERATION_CKKS_N,
}};
use lib::core::threshold::pk_generation_ckks::PkGenerationCkks;
use lib::math::polynomial::Polynomial;

fn main(
    a: [Polynomial<PK_GENERATION_CKKS_N>; PK_GENERATION_CKKS_L],
    eek: Polynomial<PK_GENERATION_CKKS_N>,
    sk: Polynomial<PK_GENERATION_CKKS_N>,
    e_sm: [Polynomial<PK_GENERATION_CKKS_N>; PK_GENERATION_CKKS_L],
    r1is: [Polynomial<(2 * PK_GENERATION_CKKS_N) - 1>; PK_GENERATION_CKKS_L],
    r2is: [Polynomial<PK_GENERATION_CKKS_N - 1>; PK_GENERATION_CKKS_L],
    pk0is: [Polynomial<PK_GENERATION_CKKS_N>; PK_GENERATION_CKKS_L],
) -> pub (Field, Field, Field) {{
    let pk_generation: PkGenerationCkks<PK_GENERATION_CKKS_N, PK_GENERATION_CKKS_L, PK_GENERATION_CKKS_BIT_EEK, PK_GENERATION_CKKS_BIT_SK, PK_GENERATION_CKKS_BIT_E_SM, PK_GENERATION_CKKS_BIT_R1, PK_GENERATION_CKKS_BIT_R2, PK_GENERATION_CKKS_BIT_PK> =
        PkGenerationCkks::new(PK_GENERATION_CKKS_CONFIGS, a, eek, sk, e_sm, r1is, r2is, pk0is);
    pk_generation.execute()
}}
"#
    );
    write_package(
        &args.out_dir.join(&name),
        &name,
        &main,
        &localize(generate_configs_nr(0, &configs)),
        &toml_str,
    )
}

// ----------------------------------------------------------------------------
// C2a / C2b (scheme-agnostic DKG share computation at CKKS moduli)
// ----------------------------------------------------------------------------
fn c2_configs_nr(
    preset: &CkksPreset,
    committee: CkksDkgCommittee,
    bit_share: u32,
    e_sm_bit_secret: u32,
) -> Result<String, Box<dyn std::error::Error>> {
    let moduli = preset.params.moduli();
    let qis = moduli
        .iter()
        .map(|q| q.to_string())
        .collect::<Vec<_>>()
        .join(", ");
    let parity = compute_parity_matrix(moduli, committee.n, committee.threshold)?;
    let parity_strings: Vec<String> = parity
        .iter()
        .map(|h_mod| {
            let rows: Vec<String> = h_mod
                .data()
                .iter()
                .map(|row| {
                    let vals: Vec<String> = row
                        .iter()
                        .map(|v| bigint_to_field(&BigInt::from(v.clone())).to_string())
                        .collect();
                    format!("[{}]", vals.join(", "))
                })
                .collect();
            format!("[\n        {}]", rows.join(",\n        "))
        })
        .collect();
    Ok(format!(
        "{HEADER}\nuse lib::core::dkg::share_computation::Configs as ShareComputationConfigs;\n\n\
pub global CKKS_DKG_N: u32 = {};\n\
pub global CKKS_DKG_L: u32 = {};\n\
pub global CKKS_DKG_QIS: [Field; CKKS_DKG_L] = [{qis}];\n\
pub global CKKS_DKG_N_PARTIES: u32 = {};\n\
pub global CKKS_DKG_T: u32 = {};\n\n\
pub global CKKS_SHARE_COMPUTATION_BIT_SHARE: u32 = {bit_share};\n\
pub global CKKS_SHARE_COMPUTATION_SK_BIT_SECRET: u32 = 1;\n\
pub global CKKS_SHARE_COMPUTATION_E_SM_BIT_SECRET: u32 = {e_sm_bit_secret};\n\n\
pub global CKKS_SHARE_COMPUTATION_SK_CONFIGS: ShareComputationConfigs<CKKS_DKG_L> =\n    ShareComputationConfigs::new(CKKS_DKG_QIS);\n\
pub global CKKS_SHARE_COMPUTATION_E_SM_CONFIGS: ShareComputationConfigs<CKKS_DKG_L> =\n    ShareComputationConfigs::new(CKKS_DKG_QIS);\n\n\
pub global CKKS_PARITY_MATRIX: [[[Field; CKKS_DKG_N_PARTIES + 1]; CKKS_DKG_N_PARTIES - CKKS_DKG_T]; CKKS_DKG_L] = [\n    {}];\n",
        preset.params.degree(),
        moduli.len(),
        committee.n,
        committee.threshold,
        parity_strings.join(",\n    "),
    ))
}

fn bit_share(preset: &CkksPreset) -> u32 {
    preset
        .params
        .moduli()
        .iter()
        .map(|&q| calculate_bit_width(BigInt::from(q - 1)))
        .max()
        .unwrap_or(0)
}

/// Fixed-bound smudging share data (2^20 like the demo C1 witness): the
/// flooding calculator refuses every N=512-class shape at lambda >= 50, and
/// the circuit cost does not depend on the bound's value, only on its bit
/// width — which is what the config pins.
fn c2b_data(
    preset: &CkksPreset,
    committee: CkksDkgCommittee,
    sm_bits: usize,
) -> Result<ShareComputationCircuitData, Box<dyn std::error::Error>> {
    let params = preset.params.clone();
    let mut rng = rand::rng();
    let trckks = TRCKKS::new(committee.n, committee.threshold, params.clone())?;
    let parity_matrix = compute_parity_matrix(params.moduli(), committee.n, committee.threshold)?;
    let es_coeffs = trckks.generate_smudging_error(sm_bits, &mut rng)?;
    let es_poly = trckks.smudging_to_poly(&es_coeffs)?;
    let sss_u64 = trckks.generate_secret_shares_from_poly(es_poly, &mut rng)?;
    let secret_sss: Vec<_> = sss_u64.iter().map(array2_u64_to_bigint).collect();
    let mut secret_crt = CrtPolynomial::from_mod_q_polynomial(&es_coeffs, params.moduli());
    secret_crt.center(params.moduli())?;
    Ok(ShareComputationCircuitData {
        dkg_input_type: DkgInputType::SmudgingNoise,
        secret: secret_crt,
        secret_sss,
        parity_matrix,
        n_parties: committee.n as u32,
        threshold: committee.threshold as u32,
    })
}

/// The witness builder hashes the smudging secret at the bit width of its
/// LARGEST centered coefficient; the circuit constant must match exactly.
fn e_sm_bit_secret(preset: &CkksPreset, data: &ShareComputationCircuitData) -> u32 {
    let moduli = preset.params.moduli();
    let mut secret = data.secret.clone();
    secret.reduce(moduli).expect("reduce");
    let max_centered = secret
        .limbs
        .iter()
        .zip(moduli.iter())
        .flat_map(|(l, &qi)| {
            let q = BigInt::from(qi);
            let half = (&q - 1) / 2;
            l.coefficients().iter().map(move |c| {
                if c > &half {
                    (c - &q).magnitude().clone()
                } else {
                    c.magnitude().clone()
                }
            })
        })
        .max()
        .unwrap_or_default();
    calculate_bit_width(BigInt::from(max_centered))
}

fn gen_c2(
    preset: &CkksPreset,
    args: &Args,
    smudging: bool,
) -> Result<(), Box<dyn std::error::Error>> {
    let committee = CkksDkgCommittee { n: 3, threshold: 1 };
    let data = if smudging {
        c2b_data(preset, committee, 20)?
    } else {
        generate_ckks_sk_share_data(preset, committee)?
    };
    let inputs = compute_ckks_share_inputs(preset, &data)?;
    // Sanity: the commitment the circuit recomputes matches the witness.
    let e_sm_bits = if smudging {
        let b = e_sm_bit_secret(preset, &data);
        let mut secret = data.secret.clone();
        secret.reduce(preset.params.moduli())?;
        let _ = compute_share_computation_e_sm_commitment(&secret, b);
        b
    } else {
        let _ = compute_share_computation_sk_commitment(data.secret.limb(0), 1);
        1
    };
    let toml_str = toml::to_string(&inputs.to_json()?)?;
    let configs = c2_configs_nr(preset, committee, bit_share(preset), e_sm_bits)?;
    let (short, main) = if smudging {
        (
            "e_sm_share_computation_ckks",
            format!(
                r#"{HEADER}
mod configs;

use configs::{{
    CKKS_DKG_L, CKKS_DKG_N, CKKS_DKG_N_PARTIES, CKKS_DKG_T, CKKS_PARITY_MATRIX,
    CKKS_SHARE_COMPUTATION_BIT_SHARE, CKKS_SHARE_COMPUTATION_E_SM_BIT_SECRET,
    CKKS_SHARE_COMPUTATION_E_SM_CONFIGS,
}};
use lib::core::dkg::share_computation::SmudgingNoiseShareComputation;
use lib::math::polynomial::Polynomial;

fn main(
    expected_secret_commitment: pub Field,
    e_sm_secret: [Polynomial<CKKS_DKG_N>; CKKS_DKG_L],
    y: [[[Field; CKKS_DKG_N_PARTIES + 1]; CKKS_DKG_L]; CKKS_DKG_N],
) -> pub [[Field; CKKS_DKG_L]; CKKS_DKG_N_PARTIES] {{
    let computation: SmudgingNoiseShareComputation<CKKS_DKG_N, CKKS_DKG_L, CKKS_DKG_N_PARTIES, CKKS_DKG_T, CKKS_SHARE_COMPUTATION_E_SM_BIT_SECRET, CKKS_SHARE_COMPUTATION_BIT_SHARE> = SmudgingNoiseShareComputation::new(
        CKKS_SHARE_COMPUTATION_E_SM_CONFIGS,
        expected_secret_commitment,
        e_sm_secret,
        y,
        CKKS_PARITY_MATRIX,
    );
    computation.execute()
}}
"#
            ),
        )
    } else {
        (
            "sk_share_computation_ckks",
            format!(
                r#"{HEADER}
mod configs;

use configs::{{
    CKKS_DKG_L, CKKS_DKG_N, CKKS_DKG_N_PARTIES, CKKS_DKG_T, CKKS_PARITY_MATRIX,
    CKKS_SHARE_COMPUTATION_BIT_SHARE, CKKS_SHARE_COMPUTATION_SK_BIT_SECRET,
    CKKS_SHARE_COMPUTATION_SK_CONFIGS,
}};
use lib::core::dkg::share_computation::SecretKeyShareComputation;
use lib::math::polynomial::Polynomial;

fn main(
    expected_secret_commitment: pub Field,
    sk_secret: Polynomial<CKKS_DKG_N>,
    y: [[[Field; CKKS_DKG_N_PARTIES + 1]; CKKS_DKG_L]; CKKS_DKG_N],
) -> pub [[Field; CKKS_DKG_L]; CKKS_DKG_N_PARTIES] {{
    let computation: SecretKeyShareComputation<CKKS_DKG_N, CKKS_DKG_L, CKKS_DKG_N_PARTIES, CKKS_DKG_T, CKKS_SHARE_COMPUTATION_SK_BIT_SECRET, CKKS_SHARE_COMPUTATION_BIT_SHARE> = SecretKeyShareComputation::new(
        CKKS_SHARE_COMPUTATION_SK_CONFIGS,
        expected_secret_commitment,
        sk_secret,
        y,
        CKKS_PARITY_MATRIX,
    );
    computation.execute()
}}
"#
            ),
        )
    };
    let name = format!("{short}{}", scaling_package_suffix(args.n));
    write_package(&args.out_dir.join(&name), &name, &main, &configs, &toml_str)
}

// ----------------------------------------------------------------------------
// C6-CKKS / C7-CKKS (one decryption: share proof + aggregation proof)
// ----------------------------------------------------------------------------
fn gen_c6_c7(
    preset: &CkksPreset,
    args: &Args,
    want_c6: bool,
    want_c7: bool,
) -> Result<(), Box<dyn std::error::Error>> {
    use e3_zk_helpers::circuits::threshold::decrypted_shares_aggregation_ckks::{
        generate_configs_nr_for_param_set as agg_configs_nr, Configs as AggConfigs,
        DecryptedSharesAggregationCkksCircuitData, Inputs as AggInputs,
    };
    use e3_zk_helpers::circuits::threshold::share_decryption_ckks::{
        generate_configs_nr_for_param_set as c6_configs_nr, CkksShareDecryptionData,
        Configs as C6Configs, Inputs as C6Inputs,
    };
    let params = preset.params.clone();
    let mut rng = rand::rng();
    let (n_parties, threshold) = (3usize, 1usize);
    let trckks = TRCKKS::new(n_parties, threshold, params.clone())?;
    let sk = CkksSecretKey::random(&params, &mut rng);
    let pk = CkksPublicKey::new(&sk, &mut rng)?;
    let sk_poly = trckks.coeffs_to_poly(sk.coeffs.as_ref())?;
    let sk_mats = trckks.generate_secret_shares_from_poly(sk_poly, &mut rng)?;
    let es = trckks.generate_smudging_error(20, &mut rng)?;
    let es_poly = trckks.smudging_to_poly(&es)?;
    let es_mats = trckks.generate_secret_shares_from_poly(es_poly, &mut rng)?;
    let encoder = CkksEncoder::new(&params);
    let pt = encoder.encode(&[0.5, -0.25], 0)?;
    let ct = pk.try_encrypt(&pt, &mut rng)?;

    if want_c6 {
        let sk_share = trckks.share_row_to_poly(&sk_mats, 0)?;
        let es_share = trckks.share_row_to_poly(&es_mats, 0)?;
        let d_share =
            trckks.decryption_share(&ct, sk_share.clone().into_ntt(), es_share.clone())?;
        let data = CkksShareDecryptionData {
            ciphertext: ct.clone(),
            sk_poly: sk_share,
            es_poly: es_share,
            d_share,
            domain_hi: 7,
            domain_lo: 13,
        };
        let configs = C6Configs::compute(preset.clone(), &())?;
        let inputs = C6Inputs::compute(preset.clone(), &data)?;
        let toml_str = toml::to_string(&inputs.to_json()?)?;
        let name = format!("share_decryption_ckks{}", scaling_package_suffix(args.n));
        let main = format!(
            r#"{HEADER}
mod configs;

use configs::{{
    SHARE_DECRYPTION_CKKS_BIT_CT, SHARE_DECRYPTION_CKKS_BIT_D, SHARE_DECRYPTION_CKKS_BIT_D_NATIVE,
    SHARE_DECRYPTION_CKKS_BIT_E_SM, SHARE_DECRYPTION_CKKS_BIT_R1, SHARE_DECRYPTION_CKKS_BIT_R2,
    SHARE_DECRYPTION_CKKS_BIT_SK, SHARE_DECRYPTION_CKKS_CONFIGS, SHARE_DECRYPTION_CKKS_L,
    SHARE_DECRYPTION_CKKS_N,
}};
use lib::core::threshold::share_decryption::ShareDecryption;
use lib::math::polynomial::Polynomial;

fn main(
    expected_sk_commitment: pub Field,
    expected_e_sm_commitment: pub Field,
    ct_commitment: pub Field,
    domain_hi: pub Field,
    domain_lo: pub Field,
    ct0: [Polynomial<SHARE_DECRYPTION_CKKS_N>; SHARE_DECRYPTION_CKKS_L],
    ct1: [Polynomial<SHARE_DECRYPTION_CKKS_N>; SHARE_DECRYPTION_CKKS_L],
    sk: [Polynomial<SHARE_DECRYPTION_CKKS_N>; SHARE_DECRYPTION_CKKS_L],
    e_sm: [Polynomial<SHARE_DECRYPTION_CKKS_N>; SHARE_DECRYPTION_CKKS_L],
    r1: [Polynomial<(2 * SHARE_DECRYPTION_CKKS_N) - 1>; SHARE_DECRYPTION_CKKS_L],
    r2: [Polynomial<SHARE_DECRYPTION_CKKS_N - 1>; SHARE_DECRYPTION_CKKS_L],
    d: [Polynomial<SHARE_DECRYPTION_CKKS_N>; SHARE_DECRYPTION_CKKS_L],
    d_native_trunc: [Polynomial<SHARE_DECRYPTION_CKKS_N>; SHARE_DECRYPTION_CKKS_L],
) -> pub Field {{
    let _ = (domain_hi, domain_lo);
    let share_decryption: ShareDecryption<SHARE_DECRYPTION_CKKS_N, SHARE_DECRYPTION_CKKS_N, SHARE_DECRYPTION_CKKS_L, SHARE_DECRYPTION_CKKS_BIT_CT, SHARE_DECRYPTION_CKKS_BIT_SK, SHARE_DECRYPTION_CKKS_BIT_E_SM, SHARE_DECRYPTION_CKKS_BIT_R1, SHARE_DECRYPTION_CKKS_BIT_R2, SHARE_DECRYPTION_CKKS_BIT_D, SHARE_DECRYPTION_CKKS_BIT_D_NATIVE> = ShareDecryption::new(
        SHARE_DECRYPTION_CKKS_CONFIGS,
        expected_sk_commitment,
        expected_e_sm_commitment,
        ct_commitment,
        ct0,
        ct1,
        sk,
        e_sm,
        r1,
        r2,
        d,
        d_native_trunc,
    );
    share_decryption.execute()
}}
"#
        );
        write_package(
            &args.out_dir.join(&name),
            &name,
            &main,
            &localize(c6_configs_nr(0, &configs)),
            &toml_str,
        )?;
    }

    if want_c7 {
        let parties: Vec<usize> = vec![1, 3];
        let mut d_share_polys = Vec::new();
        for &j in &parties {
            let sk_share = trckks.share_row_to_poly(&sk_mats, j - 1)?;
            let es_share = trckks.share_row_to_poly(&es_mats, j - 1)?;
            d_share_polys.push(trckks.decryption_share(&ct, sk_share.into_ntt(), es_share)?);
        }
        let data = DecryptedSharesAggregationCkksCircuitData {
            threshold,
            d_share_polys,
            reconstructing_parties: parties,
            // Scaling fixture: shape only, not a chain-bound proof.
            domain_hi: 1,
            domain_lo: 2,
        };
        let configs = AggConfigs::compute(preset.clone(), &())?;
        let inputs = AggInputs::compute(preset.clone(), &data)?;
        let toml_str = toml::to_string(&inputs.to_json()?)?;
        let name = format!(
            "decrypted_shares_aggregation_ckks{}",
            scaling_package_suffix(args.n)
        );
        let main = format!(
            r#"{HEADER}
mod configs;

use configs::{{
    DECRYPTED_SHARES_AGGREGATION_CKKS_BIT_D_NATIVE, DECRYPTED_SHARES_AGGREGATION_CKKS_CONFIGS,
    DECRYPTED_SHARES_AGGREGATION_CKKS_L, DECRYPTED_SHARES_AGGREGATION_CKKS_N,
}};
use lib::core::threshold::decrypted_shares_aggregation_ckks::DecryptedSharesAggregationCkks;
use lib::math::polynomial::Polynomial;

/// Committee threshold of the sizing witness (n = 3, t = 1), NOT the
/// active committee: C7's size depends on T and L, not on N.
pub global T: u32 = {threshold};

fn main(
    expected_d_commitments: pub [Field; T + 1],
    party_ids: pub [Field; T + 1],
    domain_hi: pub Field,
    domain_lo: pub Field,
    decryption_shares: [[Polynomial<DECRYPTED_SHARES_AGGREGATION_CKKS_N>; DECRYPTED_SHARES_AGGREGATION_CKKS_L]; T + 1],
    u_global: pub Polynomial<DECRYPTED_SHARES_AGGREGATION_CKKS_N>,
    crt_quotients: [Polynomial<DECRYPTED_SHARES_AGGREGATION_CKKS_N>; DECRYPTED_SHARES_AGGREGATION_CKKS_L],
) {{
    let _ = (domain_hi, domain_lo);
    let aggregation: DecryptedSharesAggregationCkks<DECRYPTED_SHARES_AGGREGATION_CKKS_N, DECRYPTED_SHARES_AGGREGATION_CKKS_L, T, DECRYPTED_SHARES_AGGREGATION_CKKS_BIT_D_NATIVE> = DecryptedSharesAggregationCkks::new(
        DECRYPTED_SHARES_AGGREGATION_CKKS_CONFIGS,
        expected_d_commitments,
        decryption_shares,
        party_ids,
        u_global,
        crt_quotients,
    );
    aggregation.execute();
}}
"#
        );
        write_package(
            &args.out_dir.join(&name),
            &name,
            &main,
            &localize(agg_configs_nr(0, &configs)),
            &toml_str,
        )?;
    }
    Ok(())
}

// ----------------------------------------------------------------------------
// C8-hybrid per digit (relin ceremony round 1, one gadget digit)
// ----------------------------------------------------------------------------
fn gen_c8(preset: &CkksPreset, args: &Args) -> Result<(), Box<dyn std::error::Error>> {
    use e3_zk_helpers::circuits::threshold::relin_round1_hybrid_ckks::{
        compute_round_1_share, sample_round_1_secrets, CkksHybridRelinRound1Data, Configs,
    };
    use e3_zk_helpers::circuits::threshold::relin_round1_hybrid_ckks_digit::{
        compute_digit_inputs, generate_configs_nr_for_param_set,
    };
    let params = preset.params.clone();
    let mut rng = rand::rng();
    let sk = CkksSecretKey::random(&params, &mut rng);
    let crp = CkksCrp::vec_from_seed_qp(&params, [9u8; 32])?;
    let (u, e0, e1) = sample_round_1_secrets(&params, &mut rng);
    let share = compute_round_1_share(&params, &crp, sk.coeffs.as_ref(), &u, &e0, &e1)?;
    let data = CkksHybridRelinRound1Data {
        crp,
        share,
        sk_coeffs: sk.coeffs.to_vec(),
        u_coeffs: u,
        e0_coeffs: e0,
        e1_coeffs: e1,
    };
    let configs = Configs::compute(preset.clone(), &())?;
    let inputs = compute_digit_inputs(preset, &data, 0)?;
    let toml_str = toml::to_string(&inputs.to_json())?;
    let name = format!(
        "relin_round1_hybrid_ckks_digit{}",
        scaling_package_suffix(args.n)
    );
    let main = format!(
        r#"{HEADER}
mod configs;

use configs::{{
    RELIN_ROUND1_HYBRID_CKKS_BIT_A, RELIN_ROUND1_HYBRID_CKKS_BIT_E, RELIN_ROUND1_HYBRID_CKKS_BIT_H,
    RELIN_ROUND1_HYBRID_CKKS_BIT_R1, RELIN_ROUND1_HYBRID_CKKS_BIT_R2,
    RELIN_ROUND1_HYBRID_CKKS_BIT_SK, RELIN_ROUND1_HYBRID_CKKS_BIT_U,
    RELIN_ROUND1_HYBRID_CKKS_CONFIGS, RELIN_ROUND1_HYBRID_CKKS_D, RELIN_ROUND1_HYBRID_CKKS_LT,
    RELIN_ROUND1_HYBRID_CKKS_N,
}};
use lib::core::threshold::relin_round1_hybrid_ckks_digit::RelinRound1HybridDigit;
use lib::math::polynomial::Polynomial;

fn main(
    s_commitment: pub Field,
    u_commitment: pub Field,
    digit: pub Field,
    a: [Polynomial<RELIN_ROUND1_HYBRID_CKKS_N>; RELIN_ROUND1_HYBRID_CKKS_LT],
    s: Polynomial<RELIN_ROUND1_HYBRID_CKKS_N>,
    u: Polynomial<RELIN_ROUND1_HYBRID_CKKS_N>,
    e0: Polynomial<RELIN_ROUND1_HYBRID_CKKS_N>,
    e1: Polynomial<RELIN_ROUND1_HYBRID_CKKS_N>,
    r1_h0: [Polynomial<(2 * RELIN_ROUND1_HYBRID_CKKS_N) - 1>; RELIN_ROUND1_HYBRID_CKKS_LT],
    r2_h0: [Polynomial<RELIN_ROUND1_HYBRID_CKKS_N - 1>; RELIN_ROUND1_HYBRID_CKKS_LT],
    r1_h1: [Polynomial<(2 * RELIN_ROUND1_HYBRID_CKKS_N) - 1>; RELIN_ROUND1_HYBRID_CKKS_LT],
    r2_h1: [Polynomial<RELIN_ROUND1_HYBRID_CKKS_N - 1>; RELIN_ROUND1_HYBRID_CKKS_LT],
    h0: [Polynomial<RELIN_ROUND1_HYBRID_CKKS_N>; RELIN_ROUND1_HYBRID_CKKS_LT],
    h1: [Polynomial<RELIN_ROUND1_HYBRID_CKKS_N>; RELIN_ROUND1_HYBRID_CKKS_LT],
) -> pub Field {{
    let relin_digit: RelinRound1HybridDigit<RELIN_ROUND1_HYBRID_CKKS_N, RELIN_ROUND1_HYBRID_CKKS_D, RELIN_ROUND1_HYBRID_CKKS_LT, RELIN_ROUND1_HYBRID_CKKS_BIT_A, RELIN_ROUND1_HYBRID_CKKS_BIT_SK, RELIN_ROUND1_HYBRID_CKKS_BIT_U, RELIN_ROUND1_HYBRID_CKKS_BIT_E, RELIN_ROUND1_HYBRID_CKKS_BIT_R1, RELIN_ROUND1_HYBRID_CKKS_BIT_R2, RELIN_ROUND1_HYBRID_CKKS_BIT_H> = RelinRound1HybridDigit::new(
        RELIN_ROUND1_HYBRID_CKKS_CONFIGS,
        s_commitment,
        u_commitment,
        digit,
        a,
        s,
        u,
        e0,
        e1,
        r1_h0,
        r2_h0,
        r1_h1,
        r2_h1,
        h0,
        h1,
    );
    relin_digit.execute()
}}
"#
    );
    write_package(
        &args.out_dir.join(&name),
        &name,
        &main,
        &localize(generate_configs_nr_for_param_set(0, &configs)),
        &toml_str,
    )
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args = parse_args()?;
    let want = |c: &str| args.circuits.iter().any(|x| x == c);
    println!(
        "CKKS scaling fixtures: N={} L={} special={} circuits={:?} -> {}",
        args.n,
        args.l,
        args.special,
        args.circuits,
        args.out_dir.display()
    );
    std::fs::create_dir_all(&args.out_dir)?;
    let plain = ckks_preset_scaling(args.n, args.l, 0)?;
    if want("c1") {
        gen_c1(&plain, &args)?;
    }
    if want("c2a") {
        gen_c2(&plain, &args, false)?;
    }
    if want("c2b") {
        gen_c2(&plain, &args, true)?;
    }
    if want("c6") || want("c7") {
        gen_c6_c7(&plain, &args, want("c6"), want("c7"))?;
    }
    if want("c8") {
        let hybrid = ckks_preset_scaling(args.n, args.l, args.special)?;
        gen_c8(&hybrid, &args)?;
    }
    refresh_workspace(&args.out_dir)?;
    println!(
        "workspace refreshed: {}",
        args.out_dir.join("Nargo.toml").display()
    );
    Ok(())
}
