#!/usr/bin/env sh

pnpm lint
pnpm check:pnpm
pnpm check:license
pnpm check:committee
pnpm check:docs
pnpm check:addresses
pnpm check:invariants
pnpm generate:verifiers --preset insecure --committee minimum --on-chain --check --no-compile
